### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#100]
Where in Kitsu is the best place for metadata?

I've seen other trackers support custom attributes on entities, which can be manage by an administrator.

**Comment by frankrousseau** [comment]
There is a field for that at the entity level on the server side. But currently there is no way to take advantage of it in Kitsu. Four studios asked me for that one, so I guess it's something interesting to add to Kitsu.

https://github.com/cgwire/zou/blob/master/zou/app/models/entity.py#L87

**Comment by frankrousseau** [comment]
TNZPV studio ordered a similar feature. It should be implemented this month. We'll inform you when it will be released.

**Comment by frankrousseau** [comment]
This feature is now available for shots and assets in the last version of Kitsu.

**Comment by tokejepsen** [comment]
Is it possible to have metadata on projects?

**Comment by frankrousseau** [comment]
Not for the moment. What kind of metadata you want on projects?

**Comment by frankrousseau** [comment]
What about having a dedicated UI that lists available software for the studio and for the project?

**Comment by tokejepsen** [comment]
We already have that with Avalon, and it's toml files and application actions.

The idea was for coordinators and supervisors to choose what software versions are locked down on a project and store that data in Kitsu, so other users' launcher will reference that when displaying applications to use.

Is a project just another entity where you can store the metadata on?
Since we will be needing to reference the Avalon applications available, we will probably need a custom UI for when supervisors locked down application versions.

**Comment by frankrousseau** [comment]
This issue seems to be fixed:
https://github.com/cgwire/zou/blob/master/zou/app/models/project.py#L33

Feel free to reopen the issue if I'm wrong.

**Comment by tokejepsen** [comment]
The free [data column for project](https://github.com/cgwire/zou/blob/master/zou/app/models/project.py#L30), certainly fixes the issue with being able to add any metadata.

The issue would be how someone like a supervisor or manager could edit that data without needing to code. For now we could probably make a custom action for this, but maybe in the future and json editor for metadata would be good for non-coding edits.

**Comment by frankrousseau** [comment]
I think that supervisors can modify this data.

**Comment by tokejepsen** [comment]
> I think that supervisors can modify this data.

Sorry, did I miss something in Kitsu where you can modify this json data without coding?

**Comment by frankrousseau** [comment]
Yes you can create metadata columns in the asset and shot lists to access them.

**Comment by frankrousseau** [comment]
But it's not possible for sequences and episodes.

**Comment by tokejepsen** [comment]
> But it's not possible for sequences and episodes.

Or projects.

Specifically for Avalon there are project based configurations like which applications to use, that a supervisor needs to access.
Maybe the metadata could be exposed in Kitsy with a json editor somehow?
Again we can probably solve this with a custom action for now.

**Comment by frankrousseau** [comment]
Ok sorry, I missed "the project" part of your comment. We are overwhelmed by feature requests, but we'll keep the json editor id in mind.

**Comment by tokejepsen** [comment]
Thanks @frankrousseau !
