### ISSUE TITLE
When creating a new asset, the global page gets sorted in descending alphabetical order.

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#1001]
**Context**

Studio name: gwen
Kitsu version: 0.15.40
Production type: short film

**Describe the bug**

When we create a new asset on the global asset page, once the creation is done, the global asset page is displayed as "sorted by". The asset types are now in descending alphabetical order.

**Screenshots**

![image](https://user-images.githubusercontent.com/42962633/214057715-e245140f-337a-4514-864b-8b27ca3bc79d.png)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 109.0.5414.75 (Build officiel) (64 bits)

**Comment by frankrousseau** [comment]
@gwendupre do you still face the bug?

**Comment by gwendupre** [comment]
It's fixed, thanks
