### ISSUE TITLE
On the sequence page, we can create a sequence with the same name that one already created

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#1002]
**Context**

Studio name: Gwen
Kitsu version: 0.15.40
Production type: short film

**Describe the bug**

On the sequence page, we can create a sequence with any name. If we create a sequence that has already been created, kitsu doesn't give any error message. The sequence will be created with the same name, but the task won't be created.

**Screenshots**

![image](https://user-images.githubusercontent.com/42962633/214059485-e832cfc8-8354-48b5-a4c1-2966547fc35a.png)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 109.0.5414.75 (Build officiel) (64 bits)

**Comment by NicoPennec** [comment]
Hi @gwendupre,

This issue should be resolved with the latest version of Kitsu (>= 0.16.7)
Could you please confirm if the issue has been resolved on your side?
