### ISSUE TITLE
how to set the correct servername in slack 

### ISSUE THREAD

**Issue by eugen666-wq** [cgwire/kitsu#1006]
hi , i dont know how to set my slack so the links point to my website running kitsu and not to localhost :8080.... how can i do it ? 

![Capture](https://user-images.githubusercontent.com/73670051/214371755-ea2c44c0-cb98-4328-bfe1-9b8061ad7a43.PNG)
ty! 

&  Thank you very much for the coolest software on earth !

**Comment by EvanBldy** [comment]
Hi @eugen666-wq, 
You have to set DOMAIN_NAME environment variable on Zou side,
Cordially

**Comment by eugen666-wq** [comment]
hi evan i tried this 
![Capture](https://user-images.githubusercontent.com/73670051/214599005-74703a52-d857-4c32-9921-7116b8ddd160.PNG)

but no luck for me ...also placed it into the zou.service ... but that didnt work either. any hints ?

**Comment by EvanBldy** [comment]
Do you have restart the services ? 
Cordially

**Comment by eugen666-wq** [comment]
i restarted my linux box . that should be enough , no ?

**Comment by eugen666-wq** [comment]
> Do you have restart the services ? Cordially

yes have also tried restarting  the service zou and zou.events and also nginx .. but the link still shows up as localhost:8080 am i missing something ?

**Comment by eugen666-wq** [comment]
for some reason i did not restart the service properly ... but works now thanks !
