### ISSUE TITLE
Request for information - How to update Kitsu without initializing data

### ISSUE THREAD

**Issue by rsSPSolution** [cgwire/kitsu#1009]
Is there an explanation for this somewhere? I'm having trouble with 0.15.33 (Adding text markup is creating an error
<img width="379" alt="Kitsu error" src="https://user-images.githubusercontent.com/32621282/215188329-1893f1d9-592e-497b-ab60-ee26e7e90402.png">

**Comment by frankrousseau** [comment]
Hello @wildsync, you should move to 0.15.41. We faced many issues with your build system. The last version is much more stable. There is only a bug left when moving several annotations at the same time.

**Comment by rsSPSolution** [comment]
Thank you!.. I'm running a dev docker instance. Is there simple way to update to that instance without initializing zou and preview data?

**Comment by rsSPSolution** [comment]
@frankrousseau - I'm hoping there is an easier way to backup, delete, and restore than writing an API script. I having trouble understanding the CLI approach through Docker. Thanks for the heads up on 0.15.33.

**Comment by frankrousseau** [comment]
You should not use Docker for installing Kitsu. The Docker is only for test purposes. 
Please follow the documentation for the installation: https://zou.cg-wire.com/
