### ISSUE TITLE
Project/Episode/Sequence Tasks

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#101]
**Goal**

Feature to add tasks to project, episodes and sequence, similar to shots.

**Motivation**

Not all tasks are on a shot level, for example ```editing``` happens on an project/episode/sequence level.

**Comment by frankrousseau** [comment]
I like the idea to add tasks at the sequence level. Two studios already asked for it. 

At the episode level, I don't have any example yet of tasks that could be applied. At the project level I'm not sure it's useful. It's going to add complexity without adding much value. Do you have any use case for project and episode tasks?

**Comment by tokejepsen** [comment]
> Do you have any use case for project and episode tasks?

We have been using ```editing``` or ```ingest``` tasks on both the project and episode level. For initial implementation I think tasks on a sequence level would suffice.

**Comment by frankrousseau** [comment]
Ok thank you for this new input.

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/casting/p/projectepisodesequence-tasks
