### ISSUE TITLE
FPS table not auto-generated when entering data

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#1012]
**Context**

Studio name: Ember Light
Kitsu version: 0.15.43

**Describe the bug**
Adding FPS to a shot does not generate the table in the shots view like it does if you add In/Out or any other preset-data
If you manually create the FPS table you now have two tables called FPS.
If you delete the table you created both tables gets deleted including the FPS data you entered.

**Screenshots**

https://user-images.githubusercontent.com/49758407/216591992-0c92f5d6-78a7-4885-8022-63588cc0c099.mp4

**Desktop (please complete the following information):**

 - OS: Hosted on a Synology nas
 - Browser Firefox
 - Version 109.0.1

**Comment by frankrousseau** [comment]
Thank you @EmberLightVFX for the report.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
