### ISSUE TITLE
https vs. http 

### ISSUE THREAD

**Issue by eugen666-wq** [cgwire/kitsu#1014]
hello , maybe someone here could help me ? 
where do i change the protocol and certificate to a valid  https . at the moment i am running http but my browser complains. 
best, eugen

**Comment by frankrousseau** [comment]
Setting https is a little bit tedious. It requires to load a Let's encrypt certificate and some Nginx configuration.
You can find information about it there:
https://mindsers.blog/post/https-using-nginx-certbot-docker/

**Comment by frankrousseau** [comment]
Sorry but this question should be asked on the Zou repository. I close it.
