### ISSUE TITLE
Kitsu does not handle the 502 error when connecting

### ISSUE THREAD

**Issue by nledez** [cgwire/kitsu#1017]
Kitsu API is not working

Kitsu version: 0.15.45

If I try to connect and the backend returns a 502 error. Kitsu seems to be waiting for something from the server.

![2023-02-15 10 03 29](https://user-images.githubusercontent.com/247138/218982388-49e60287-a4a0-44c7-8075-3c413be4aba5.gif)

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu >= 0.17.28
