### ISSUE TITLE
Per shot tasks.

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#102]
**Goal**

Feature to choose what tasks are applied to which shots.

**Motivation**

Often shots have different requirements which means different tasks per shot.

To reduce the visual clutter and clarify what is required from a shot.

**Comment by flablog** [comment]
So far I think it’s not possible
So what we did in our case is a custom task status ‘OMMIT’ with a black
background
So it’s obvious graphists should not work on that.

Le jeu. 5 juil. 2018 à 09:42, Toke Jepsen <notifications@github.com> a
écrit :

**Comment by tokejepsen** [comment]
Yeah, I think maybe the layout needs a little adjusting to accommodate this.

Maybe its even worth introducing a tree like view.

**Comment by frankrousseau** [comment]
For that I would like to: 

* Make it easy to remove useless tasks
* Allow to create tasks only for current filter
* Display columns only if there is a at least one of the current shot with a task from the column

**Comment by BigRoy** [comment]
>     * Make it easy to remove useless tasks

I believe you are now able to delete tasks completely from a Shot or Asset. Select the tasks in the column and at the top left choose the option to "Delete Tasks".

>     * Display columns only if there is a at least one of the current shot with a task from the column

This is implemented. Now tasks columns are filtered from the view in Kitsu when none of the currently listed assets/shots have the task.

>     * Allow to create tasks only for current filter

This I'm not too sure of whether it already works. I tried quickly apply a filter to my current view and then do "add task" that is at the top of the columns and it applied it also to those shots outside of my filter (to everything)

**Comment by frankrousseau** [comment]
> > Allow to create tasks only for current filter

> This I'm not too sure of whether it already works. I tried quickly apply a filter to my current view and then do "add task" that is at the top of the columns and it applied it also to those shots outside of my filter (to everything)

You're right, it is not implemented for the moment.

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/asset-and-shot-tables/p/allow-to-create-tasks-only-for-current-filter
