### ISSUE TITLE
Adding a new sequence breaks ability to assign shots to a sequence on the shots page

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1024]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.15.47
Production type: Short

**Describe the bug**

Adding a new sequence breaks ability to assign shots to a sequence on the shots pagedescription of what the bug is.

Steps to reproduce issue:
1. Add a sequence
2. Add shots
3. Leave the Create Shot dialog, go back to shots page
4. Go to the seqeuences page
5. Add a new sequence
6. Go to the shots page, open "Edit Shot" dialog
7. Try to assign shot to a sequence
8. Sequence dropdown is empty ( see screenshot )

**Screenshots**

![grafik](https://user-images.githubusercontent.com/58070351/221546491-66c83cea-c070-41fe-8ac7-a0262fae1c1e.png)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome / Firefox

**Comment by NicoPennec** [comment]
Fixed on Kitsu [v0.16.4](https://github.com/cgwire/kitsu/releases/tag/v0.16.4)
