### ISSUE TITLE
Client can see full name of artist assigned to a shot

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu#1028]
Studio name: Imaginary Pixels
Kitsu version: 0.15.29 
Production type: Feature Film

When, as a client, you go to a playlist -> click a shot on the playlist -> open comments panel -> click on one of the revisions - then you land on a shot page, and at the top you can see Assignees - which are clickable, directing to artists shot list, showing his full name.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
