### ISSUE TITLE
Tasks deletion

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#103]
How do you delete tasks?

**Comment by frankrousseau** [comment]
You can delete a task only if there is no  comment on it. To remove the task you have to go inside the task page and click on the trash button on the right top of the page.

You can do it via a Python script too.

**Comment by gwendupre** [comment]
Hi Tokejepsen, 
you can also find a documentation about Kitsu here : 
https://kitsu.cg-wire.com/#getting-started/

Let us know if this issue is solved!

**Comment by tokejepsen** [comment]
Yeah, that solves the issue.
