### ISSUE TITLE
Smoother, more responsive playback controls

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu#1035]
Whould be nice if the video player playback controls would allow to scrub through the timeline. Currently it's not possible, and even jumping between frames - by clicking or with keyboard - takes a while. In SyncSketch for example the player is super responsive, you can scrub through the time line without any delays.

**Comment by frankrousseau** [comment]
Thank you for the report. To be honest, I don't know how they do. The HTML video player is not very responsive. Maybe they fallback on an image sequence. 
The video quality seems to be lower too (we send very big files).

**Comment by frankrousseau** [comment]
If you have any hints it would be very helpful. That said the Syncsketch UI manages much less information, there is not a full production tracker loaded at the same time. But I'm not sure it's related.

**Comment by lukas-remis** [comment]
I did a test, and replaced the preview file, with one that has no sound, and that helps a bit. It's less laggy with scrubbing and switching frames with keyboard, but still not as responsive as Syncsketch.
However the change is quite noticable, so perhaps it would be good to have an option, in project settings, not to encode sound track? For me, working on VFX, we don't use sound.

**Comment by frankrousseau** [comment]
Ok, that's good to know. There is a thing too: Syncsketch uses 720p videos by default which are faster on Kitsu too. Still there is a lag in Kitsu like if the scrubbing is overflowed. 
It's true too that syncksetch separates audio and video files.

**Comment by lukas-remis** [comment]
Actually I've been testing Syncsketch on a 1080p video, and it's been very smooth.

**Comment by frankrousseau** [comment]
I found the issue: it was due to the keyframes. The current encoding don't set enough keyframes. We'll fix that this wee.

**Comment by frankrousseau** [comment]
We published a new release. Can you update your installation, upload a new video and try again?

**Comment by frankrousseau** [comment]
Did you upload a new video?

**Comment by frankrousseau** [comment]
Can you send me  the video in any way?

**Comment by frankrousseau** [comment]
You need the 0.16.15 version of the API.

**Comment by lukas-remis** [comment]
Hi,
I've got Zou at version 0.16.19, Kitsu 0.16.14
Still scrubing or using cursor key has lag.
I'm in Highdef, as lowdef version is unuasble, it's completely pixelated.
But, in lowdef scrubing works quite well.

Here's a example video: https://ds.imaginary-pixels.com:6661/sharing/mLezQxthL

**Comment by frankrousseau** [comment]
On high-def, I'm not sure it's possible to do better for this quality. The browser doesn't seem to manage it properly.

Can you explain me how you display HD video with high bitrate on Syncsketch? Every time I push something it turns it into a 768p video with a low bitrate.

**Comment by frankrousseau** [comment]
I think I found a solution: being extreme with parameters: set a keyframe for each frame. The files will be much bigger but you will be able to scrub them more efficiently.

**Comment by frankrousseau** [comment]
We made a new release with a bigger bitrate for the lowdef (6MB) and a keyframe per frame. The files will be much bigger but the scrubbing should be better in high def. I hope it will work better for you because I think we cannot do better.

**Comment by lukas-remis** [comment]
Thank you Frank!
It's not perfect but it's a significant improvement! Works much better now.

**Comment by frankrousseau** [comment]
Ok great let's close this issue! Feel free to reopen it if you feel the need for it.
Thank you for your help. It's a very tough problem. I'm glad we were able to improve the situation.

**Comment by tetsuoanimation** [comment]
Additional info for future ref: This is also impacted to your system config and browser.
- I get better / faster scrubbing overall in chrome vs. firefox
- Playing back / scrubbing on my workstation is _much_ faster and very smooth compared to my ( older ) laptop where it lags behind a fair bit.
