### ISSUE TITLE
Live review room not working after upgrading to latest version

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu#1036]
**Context**

Studio name: Imaginary Pixels
Kitsu version: 0.16.2
Zou version: 0.16.7 

After upgrading to latest version of Kitsu and Zou the live review room is not working anymore, the "Join Review Room" button has no reaction. Before upgrade it was working fine.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try it again?

**Comment by lukas-remis** [comment]
Yes, it works now. Thank you very much!
