### ISSUE TITLE
Display issue on the episode stats page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#1043]
**Context**

Studio name: Gwen
Kitsu version: 0.16.3
Production type: TvShow

When we are at the episode stat page data = retake, and we went to expand an episode, we can see that the column of the task type are moved to the right and not aligned anymore

**Screenshots**

![image](https://user-images.githubusercontent.com/42962633/225301927-3af95199-9841-410c-838a-e3cb0ad46563.png)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 111.0.5563.65 (Build officiel) (64 bits)

**Comment by frankrousseau** [comment]
Thx it will be fixed in next release.
