### ISSUE TITLE
Users who are not Supervisors don't see the "My Checks" page

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1050]
**Context**

Studio name: Tetsuo Animation 
Kitsu version: 0.16.3
Production type: Short

**Describe the bug**
"My Checks" is not available in the Sidebar Menu. 
Often times, users have and need higher permissions but still regularly review work in their department - Add the new "My Checks" page to the sidebar so these users can use it too.

**Comment by frankrousseau** [comment]
Sorry but the My Checks page makes only sense for supervisors. I don't see what we can do for this.

**Comment by tetsuoanimation** [comment]
In small studios, studio managers are often also supervisors – can we enable my-checks for studio managers for everything that needs review on a project or add studio managers to a department where they are treated like supervisors?

 �

**Comment by NicoPennec** [comment]
Since Kitsu 0.19.2, the studio and production managers are allowed to access to "My checks" page.
