### ISSUE TITLE
Email notifications enable, but don't work.

### ISSUE THREAD

**Issue by AndreyGorodilov** [cgwire/kitsu#1051]
Studio name: Studio34
Kitsu version: 0.16.4
Production type: TVshow

Email notifications don't work. 
Emails are not being sent from Kitsu. 
Notifications are enabled in the profile settings. 
Meanwhile emails arrive when you change your password, invite and with two-factor authentication to the mail.

 - OS: MacOS 11.7.3
 - Browser chrome
 - Version 111.0.5563.64 (Official Build) (x86_64)

**Comment by AndreyGorodilov** [comment]
> Hello @AndreyGorodilov,
> It seems there is an issue in your configuration. Did you set up properly emails environment variables?

Hello, Frank! if the error was in setting up emails configuration, then notifications about changing the password would not come, but they do. Or am I wrong?

**Comment by frankrousseau** [comment]
Did you setup the job queue properly?

**Comment by AndreyGorodilov** [comment]
> Did you setup the job queue properly?

I took the job-queue settings from the documentation.
![PXL_20230515_114252581.MP.jpg](https://github.com/cgwire/kitsu/assets/28741632/e95f573d-b612-4dba-a892-7b688ee12fdb)

**Comment by AndreyGorodilov** [comment]
> Did you setup the job queue properly?

added email settings to job-queue and everything worked! Thank you, Frank!
