### ISSUE TITLE
Edit Comment popup scales beyond window bounds

### ISSUE THREAD

**Issue by elias-schwarze** [cgwire/kitsu#1052]
**Context**

Studio name: Balance Film GmbH
Kitsu version: 0.16.3
Production type: TV Show

**Describe the bug**

When editing a comment of any asset or shot, the edit popup window may scale beyond the bounds of the browser window, especially if the text box is large enough, the checklist has many items or the list of attachments gets too long.
Since the popup cannot be scrolled, this means the confirm and cancel buttons may end up outside of the window, which makes it impossible for the user to click them.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/85888167/227530455-02a7ef22-d7b5-422b-9a10-33816830a321.png)

**Desktop:**

 - OS: Windows 10 22H2
 - Browser: Tested both Firefox and Chrome
 - Version: Firefox 111.0.1; Chrome 111.0.5563.111

**Comment by NicoPennec** [comment]
Thank you @elias-schwarze for your report. It will be fixed on the next release.

**Comment by NicoPennec** [comment]
Fixed on Kitsu [v0.16.5](https://github.com/cgwire/kitsu/releases/tag/v0.16.5)
