### ISSUE TITLE
Show / Hide annotation while playing movies button not working

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1055]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.16.4
Production type: Short

**Describe the bug**

Usually the Show / Hide annotaiton while playing movies button toggles the annotations when the movie is played. We use this for some crude 2d animation suggestions. This feature stopped working in playlists as well as the sidebar.

Recreate the bug:
1. Upload movie
2. Add annotation drawings
3. Press play
4. Press stop
5. Toggle 'Hide / Show annotations while playing movie' button
6. Press play again - the annotations are not visible

**Screenshots**

![grafik](https://user-images.githubusercontent.com/58070351/227915835-f0126d32-9e82-42e8-a306-8f0012f43009.png)

**Desktop (please complete the following information):**

 - OS: Windows 
 - Browser both, Chrome and Firefox

**Comment by tetsuoanimation** [comment]
I was wrong - there are two buttons that do this and both need to be enabled. Is this by design?
![grafik](https://user-images.githubusercontent.com/58070351/227944201-e02e5745-723d-46f9-a3d6-1929a8e12ef0.png)

**Comment by frankrousseau** [comment]
Yes, the right button is for showing annotations. The left button is for showing annotations while playing.
