### ISSUE TITLE
Checklist UI breaks when deleting last checklist item in Edit Comment popup

### ISSUE THREAD

**Issue by elias-schwarze** [cgwire/kitsu#1059]
**Context**

Studio name: Balance Film GmbH
Kitsu version: 0.16.4
Production type: TV Show

**Describe the bug**

In the Edit Comment popup, when trying to edit the checklist items, if no checklist items are present besides the "New Item..." entry, hitting backspace on it while the name is already empty removes the checklist item completely and also removes the function to add new checklist items again. It stays like until the Edit Comment window is closed and reopened.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/85888167/229468885-e133d542-9fc1-407d-824d-9f6320d1ff3c.png)

After pressing backspace once:

![grafik](https://user-images.githubusercontent.com/85888167/229467767-eeb62d0c-45cd-4b8d-9495-a92585f0d307.png)

**Desktop (please complete the following information):**

- OS: Windows 10 22H2
- Browser: Tested both Firefox and Chrome
- Version: Firefox 111.0.1; Chrome 111.0.5563.111

**Comment by frankrousseau** [comment]
It should be fixed. Can you try
