### ISSUE TITLE
drawings scaled wrong chrome 

### ISSUE THREAD

**Issue by eugen666-wq** [cgwire/kitsu#1069]
**Context**

<html><body>

name | "Zou"
-- | --
version | "0.15.27"
database-up | true
key-value-store-up | true
event-stream-up | true
job-queue-up | false

</body>
</html>

**Describe the bug**
if i paint in fullscreen or other scaling the drawing appears in wrong place and wrong scale when back in default framesize .. 
it only happens in chrome (am on windows 10)   works perfectly in firefox. 

**Screenshots**

**Desktop (please complete the following information):**

**Comment by frankrousseau** [comment]
Hello Eugen,

Your installation is outdated. Please update to the last version, the problem should be fixed.
