### ISSUE TITLE
Clients account can see list of names of the artists involved in the project

### ISSUE THREAD

**Issue by Naolito** [cgwire/kitsu#1072]
**Context**
Studio name: Naolito animation studio
Kitsu version: 0.16.5
Production type: Advertisement

**Describe the bug**
While making a comment using @, client accounts are able to see the full list of artist involved on a project, which can be problematic for small productions where the studio can be bypassed and for retention of talent.

**Screenshots**
I

**Desktop (please complete the following information):**

 - OS: windows 11
 - Browser: All browsers

**Comment by Naolito** [comment]
In addition to the mentioned above, when you access to individual revisions with a client account, you also have access to the artists assigned to that task. If you click over the artist avatar, you can access to his kitsu profile and full name. 

![imagen](https://user-images.githubusercontent.com/74182389/235439407-6736a595-a41c-4e4a-9848-e15fc78f2555.png)

**Comment by frankrousseau** [comment]
Ok noted. It will be fixed in the next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by Naolito** [comment]
It's working now! Thank you so much @frankrousseau!
