### ISSUE TITLE
Automatically changing to publish revision tab

### ISSUE THREAD

**Issue by Maxiriton** [cgwire/kitsu#1098]
Studio name: 3.0 Studio 
Kitsu version: 0.16.14
Production type: Feature Film

**Describe the bug**

We are encountering a strange bug on our production : when we click on atask, the lateral panel appears on the post comment tab. We then click on the list button and type a first item and then change a task status , it a automatically switches the view to the publish revision tab. And if we go back to the post comment tab, the list item is gone. 

What is weird is that it doesn't always behave like that. Generally it is the first task after loading the shot page, but after a few tasks we have the correct behavior (no tab switching).   

**Screenshots**

We click on a tab and start an item list : 

<img width="391" alt="image" src="https://github.com/cgwire/kitsu/assets/10707113/f0282271-2b44-4778-be79-e40f424dd0ff">

We change the status, it automatically switches to Publish Revision : 

<img width="386" alt="image" src="https://github.com/cgwire/kitsu/assets/10707113/a03a1685-a721-4457-8f91-4149b6837ac3">

We go back to the Post Comment tab, the list item is gone : 

<img width="386" alt="image" src="https://github.com/cgwire/kitsu/assets/10707113/cbd47816-af77-496f-a722-29d0c9836935">

**Desktop (please complete the following information):**

 - OS: MacOS 13.0.1
 - Browser Firefox 113
 - Version 113

**Comment by frankrousseau** [comment]
Hello, it's not a bug. It simply put you in the right mode depending on what you are supposed to do.

**Comment by Maxiriton** [comment]
Thanks for the quick reply. :) 

How is that not a bug ? Changing status doesn't imply Publishing Revision, right ? So it should'nt force us to jump to the publish revision tab. 

Also, if we write some text that is is lost without us cancelling it, it seems like a bug to me.

**Comment by Maxiriton** [comment]
Oh I see. Thanks for the explanation ! I guess we have some clean up to do on our task status list. :)

Thanks !
