### ISSUE TITLE
Notifications on discord not working after Discord migration to new Nickname system

### ISSUE THREAD

**Issue by Naolito** [cgwire/kitsu#1111]
Recently Discord is forcing to change usernames from their #number based system that allowed for multiple people with the same name, to a system with unique nicknames without #. Notifications continue to work for those who still didn't make the switch, but everyone who made the switch is not getting the notifications (we tried updating our kitsu setting with the new unique nickname)

Studio name: Naolito
Kitsu version:  0.16.5
Production type: Animation

Applies to all OS and systems.

@EvanBldy

**Comment by EvanBldy** [comment]
Hi @Naolito,
It should be fixed by this commit https://github.com/cgwire/zou/commit/44a31b55ed9ba4e6ffcb4e8089dc5945ed8fff8d
It's in the last version of Zou (0.17.11).
Thanks for the the report !
Have a nice day
