### ISSUE TITLE
23.976 fps invalid error

### ISSUE THREAD

**Issue by henrybennettfr** [cgwire/kitsu#1127]
Kitsu version: 0.17.7
Zou version is: {"api": "Zou", "version": "0.17.11"}
Production type: VFX

Hi there, we are trying to use a frame rate required for our project which is 23.976 (an industry standard fps), however Kitsu flags this as invalid, requiring 23 or 24.  Could this please be added as a valid frame rate?

<img width="340" alt="Screenshot_2023-07-10_at_2 36 47_PM" src="https://github.com/cgwire/kitsu/assets/133737659/7d6c42cb-0d78-42e8-bf44-344f1073d115">

OS: Windows Server 2019 Datacenter
Browser Chrome Version 113.0.5672.128 (Official Build) (64-bit)

Thanks very much,
Henry

**Comment by NicoPennec** [comment]
Thanks @henrybennettfr for your report 🙏 
It will be fixed in the next release (Kitsu > 0.17.7)

**Comment by NicoPennec** [comment]
Issue fixed in [Kitsu >= 0.17.8](https://github.com/cgwire/kitsu/releases).
