### ISSUE TITLE
Not works with Yandex Browser

### ISSUE THREAD

**Issue by morevnaproject** [cgwire/kitsu#1128]
**Context**

Studio name: Morevna Project
Kitsu version: 0.16.4
Production type: Animation

**Describe the bug**
Kitsu not working in Yandex Browser - it shows error, which is bloking access (see attached screenshot). Yandex Browser is based on Chromium, so it should be compatible.

**Screenshots**

![Без имени](https://github.com/cgwire/kitsu/assets/332868/fb21f170-36d4-4c62-9cf1-a884b9041e0d)

**Desktop (please complete the following information):**

 - OS: Linux / Windows
 - Browser: Yandex Browser
 - Version: any

**Comment by frankrousseau** [comment]
Sorry, but we can only afford to support Chrome and Firefox.

**Comment by morevnaproject** [comment]
Hi! THank you for reviewing. I just want to point out that Yandex Browser has same engine as Chrome/Chromium. So it should work the same way as Chrome and wouldn't require extra support effort.
