### ISSUE TITLE
Keep index when switching versions

### ISSUE THREAD

**Issue by NTKKS** [cgwire/kitsu#1144]
When revision has multiple images and I am on frame 4/6 and switch the view to a different version, keep the same index instead of switching to 1/6.
Same should apply in the comparison mode.

![image](https://github.com/cgwire/kitsu/assets/43784192/61676650-e9cf-49fb-9f2f-560a79d4c52f)

Studio name: Qink
Kitsu version: 0.17.13

**Comment by NTKKS** [comment]
also in fullscreen mode I am unable to switch between versions

**Comment by frankrousseau** [comment]
It should work can you try again?

**Comment by NTKKS** [comment]
@frankrousseau Hi, sorry for late reply, we finally deployed Kitsu properly and this fix is working, thank you.
