### ISSUE TITLE
Replying to any comment results in a notification for yourself

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1148]
If you use the Reply feature in any comment in a task, you will get a notification that you have replied to it. 

Expectation: No notification.

**Comment by frankrousseau** [comment]
Thank you for the report. @EvanBldy will have a look at it.

**Comment by EvanBldy** [comment]
Hi @PeteDraper, I have done a PR for that :) 
It should be fixed in the next release. 
Can you close this issue after testing that it works well?

**Comment by PeteDraper** [comment]
sure will do
