### ISSUE TITLE
Searchbar and capital letters

### ISSUE THREAD

**Issue by larsdpeder** [cgwire/kitsu#1151]
**Context**

Studio name: none
Kitsu version: Kitsu 0.17.15
Production type: test of vfx workflow

**Describe the bug**

The searchbar and the "name" of sequences don't agree on the small letter or capital letters, so when i search my sequence name "sequence1" as its being shown in the list nothing shows, but if i change it to "SEQUENCE1" then it shows in the search.

**Screenshots**

<img width="568" alt="Screenshot 2023-08-17 at 12 47 27" src="https://github.com/cgwire/kitsu/assets/32838004/d47ca4bf-dea4-4d60-ac7a-d19796bdaf05">

**Desktop (please complete the following information):**

 - OS: macOS 13.4.1 
 - Browser: Chrome Version 116.0.5845.96 (Official Build) (x86_64)

**Comment by NicoPennec** [comment]
Hi,
The search functionality has been updated since this old release, and it is now case-insensitive.
