### ISSUE TITLE
Unable to set work days on Saturday or Sunday

### ISSUE THREAD

**Issue by aramadan0096** [cgwire/kitsu#1166]
**Context**

Studio name: Self Employed
Kitsu version: 0.15.11
Production type: VFX

**Describe the bug**

When I select a shot task to set a "start date" and "due date" I'm not allowed to select Saturday or Sunday, is there a way to change or remove these days?

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/57462754/0dd77ce1-e159-4ec3-8607-ec6953f8fb9a)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser Chrome
 - Version 116.0.5845.141

**Comment by Chantology** [comment]
I agree, but this probably has to be enabled before because this is a rare case. For us it might happen to work during the weekend as well if the client pays for it and it's also approved by the artist. Then we would like to track this as well.

**Comment by NicoPennec** [comment]
Thank you for this proposal.
You can upvote for a similar request on our Canny page: https://cgwire.canny.io/schedule/p/ability-to-choose-off-days-in-the-calendar

**Comment by NicoPennec** [comment]
follow the request on Canny
