### ISSUE TITLE
Uploaded Revision via Gazu with No Re-Encode results in Incorrect Start Frame & Hold End Frame

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1168]
Publishing a revision clip using Gazu with no-re-encode results in the first frame being omitted in playback and duplicate last frame.

If the same clip is downloaded and re-uploaded (and re-encoded) the file is ok. Also, if the re-uploaded clip is compared with the original (with the re-uploaded clip as the primary revision), we can see frame 1 of the Gazu upload.

If we flip between the re-upload and the Gazu upload, both 1st frames are shown. Scrubbing forward on the Gazu one and back again, results in the first frame being dropped again.

**Comment by frankrousseau** [comment]
Thank you for the report. But sorry but we don't provide maintenance for encoding managed on your side.
