### ISSUE TITLE
Compare button not visible

### ISSUE THREAD

**Issue by NTKKS** [cgwire/kitsu#1185]
**Context**

Studio name: Qink
Kitsu version: latest
Production type: Assets only

**Describe the bug**

When I click on the task and I am in split screen view I can click fullscreen mode and there is a compare button.
But when I first go from split screen to full task screen and then go fullscreen there is no compare button.
Hope I am describing correctly.

**Screenshots**
icon to go to full task view:
![image](https://github.com/cgwire/kitsu/assets/43784192/cc61e0ee-83c5-4662-aef3-e1708ca6ded7)
compare icon:
![image](https://github.com/cgwire/kitsu/assets/43784192/a402b6aa-9244-4a54-bbb6-b3abdd7f923f)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] - win10
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - latest

**Comment by NicoPennec** [comment]
Thanks @NTKKS 🙏 
The issue will be fixed in the upcoming release (> v0.17.23)
