### ISSUE TITLE
Cannot change another user's password

### ISSUE THREAD

**Issue by furrykef** [cgwire/kitsu#1191]
**Context**

Studio name: Team Sea3on
Kitsu version: 0.17.19
Production type: 

**Describe the bug**

We currently have only the admin user and want to add more users. Our webhost does not allow running an SMTP server, and we don't currently have an external one set up, so our Kitsu installation can't send invite emails. So for now we want to create users manually and give them temporary passwords using the Studio > People menu.

I create a new user and I try to set a password for them, but no matter what password I use, I get the message, "An error occurred while changing password. Please verify the new password." I can change the password on my own account this way, but not on the new accounts I am trying to create.

gunicorn_access.log shows that 403 Forbidden errors are being generated when we try to change passwords this way, e.g.:

127.0.0.1 - - [16/Sep/2023:16:57:26 +0000] "POST //actions/persons/0f544199-4932-4a65-afea-06670310d8a1/change-password HTTP/1.0" 403 138 "https://[redacted]/people?search=&department=&role=all" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/536006/a1ac7af8-ba92-4658-901f-9da9de394692)

**Desktop (please complete the following information):**

 - OS: Linux Mint 20.3
 - Browser: Chromium
 - Version: 117.0.5938.62 (Official Build) for Linux Mint (64-bit)

**Comment by NicoPennec** [comment]
Hi @furrykef,
It looks like an installation configuration issue.
Can you join us on Discord? https://discord.com/invite/VbCxtKN
We have a "Kitsu Support" section. It will be smoother to discuss with you 😉

**Comment by furrykef** [comment]
Why was this closed? We still have the issue. I just haven't gotten around to joining the Discord yet since I've been busy with other things. I will try to do that soon if this issue isn't resolved here.

I will add that we did get mail working and new users are unable to reset their own passwords either. They get the same or a similar error message.

**Comment by furrykef** [comment]
I rebooted the server and creating accounts via invites works correctly now. I still get the same error when resetting another user's password myself, though.

**Comment by frankrousseau** [comment]
The bug cannot be reproduced. It seems related to your installation.
