### ISSUE TITLE
Webhook issues

### ISSUE THREAD

**Issue by nervYu** [cgwire/kitsu#1240]
https://github.com/cgwire/kitsu/blame/a8f7a823cbd3d2857d7669682181b6d26b3f89e5/src/components/pages/Settings.vue#L181

**Comment by nervYu** [comment]
this line will cause other type webhook not work like this

**Comment by nervYu** [comment]
https://www.feishu.cn/flow/api/trigger-webhook/59606dd](https://www.feishu.cn/flow/api/trigger-webhook/xxxxxxxxx

**Comment by frankrousseau** [comment]
Hello @nervYu,
Can you be more specific about what you are trying to do?

**Comment by nervYu** [comment]
I'm trying to send wehook from kitsu to feishu(an im software like slack) but no w i stack @ wehook address if you can make a choices on link choose it will be nice

**Comment by frankrousseau** [comment]
This feature request should appear on Canny. I let you open a ticket.
