### ISSUE TITLE
@frame / frame is not calculated correctly in playlist view

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1263]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.17.52
Production type: Short

**Describe the bug**

Using @frame generates different results depending on watching the shot in Shots panel vs in a playlist panel. The Framenumber on the timeline shows the same behaviour.

This offsets where an @frame link jumps in a shot when it is clicked.

Example - these two notes are on the same frame in the video:
```
- v1 00:00.367 (012) Note on the shots panel
- v1 00:00.400 (013) Note in playlist
```

Using the 'clock' to add the time in a checklist exhibits the same behaviour difference between shots panel and playlist panel

How to reproduce:
- Find a frame in a shot on the shots panel ( other than 0/1 )
- Type @frame and remember the time that kitsu adds into the text box
- Go to the same shot in a playlist and repeat. The frametext genereated is now +1 frame
- Timecode is also offset

I think there was an old bug where this offset happened in _all_ panels and the shotpanel might have been fixed with the playlist not getting updated.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
