### ISSUE TITLE
Incorrect timecode displayed in preview

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1264]
Currently the timecode is using a non-standard format and not adhering to standard SMPTE standards:

hh:mm:ss:ff based on the project's frame rate.

eg 100 frames **starting from frame 0** would be displayed as

24fps
00:00:04:03

25fps
00:00:03:24

30fps
00:00:03:09

It would also be preferred if the TC baked into the uploaded clip is maintained as this is often referred to in edit, esp if picture starts at 1 hour.

**Comment by frankrousseau** [comment]
Thank you for stating the discussion about timecodes. I have a question If 0 is the first frame, 4:00 should be the 26th frame.

**Comment by PeteDraper** [comment]
if first frame is 0, 100 frames will be 3s24f
if first frame is 1, 100 frames will be 4s00f

@25fps.

**Comment by PeteDraper** [comment]
I'll edit the initial comment to avoid confusion.

**Comment by frankrousseau** [comment]
The rendering should be fixed, can you try again?

About the frame counting, I think we do it right, so I didn't change it.

**Comment by PeteDraper** [comment]
frame count is ok as normal. The timecode makes no sense to anyone working in video, sorry. If I asked anyone in media what the frame number was for a TC of  00:00:00:80, they wouldn't say frame 21 when working in a 25fps project - I'd get blank looks.
![Screenshot 2023-12-21 at 19 11 45](https://github.com/cgwire/kitsu/assets/55868068/fd27c58e-1f4f-4048-97e8-dee9a21d41ac)

**Comment by frankrousseau** [comment]
Sorry, but it's very hard to understand what you expect. A frame length is 0.04s. The first frame is at 0. So 21, is 0.80 (20 x 0.04 + 1).

**Comment by PeteDraper** [comment]
It should be displayed in smpte format ie 00:00:00:21, not in this decimal format. Open up resolve, blender, premiere, avid, Final Cut, it’s all done in smpte, not in the fractional format currently displayed.

**Comment by flablog** [comment]
Indeed, last digit is usually the frame within the second displayed (so
it’s depending on the frame rate too). Not the decimal of the second.


exceptionally is here the link to the French Wikipedia article as the
English one is more technical and doesn’t even really explain the format.
https://fr.m.wikipedia.org/wiki/Timecode_(indicateur)

But there are many resources explaining it like
https://www.acclaim-media.com/blog/what-is-timecode-in-video-editing-timecode-explained


Then they are many other rules for TC. For example they usually do not
start at 00:00:00:00
Movies uploaded by studios could even get their own TC locked on the
project timeline in some cases. But that might be very hard to handle
properly.
But if you ask me you can go for the simple version (starting a 0) ! :)



Le sam. 23 déc. 2023 à 20:33, PeteDraper ***@***.***> a
écrit :

**Comment by PeteDraper** [comment]
a lot do still start at 00:00:00:00 , however most start prior to 1 hour with bars & tone and slate. I would suggest utilising the tc which is embedded in the uploaded file and the frame counter number starting from 0 (or 1) - this could be a project preferences setting. Most DCCs export with a TC option - even if you take a shot from an edit with picture starting at 1 hour, this TC will be included and pulled from an ffprobe.

**Comment by frankrousseau** [comment]
Thank you for the additional information. I will push a new proposal for this soon.

**Comment by frankrousseau** [comment]
We pushed a new version displaying the timecode like you ask: 'HH:MM:SS:FF'. Can you confirm that it works as expected?

**Comment by PeteDraper** [comment]
looks good to me - to avoid any issue with the start frame, I would suggest adding the ability to mend the start frame value in the TC in the project's settings, in case the user wants to start it at frame 1 for example.
