### ISSUE TITLE
"an error occurred when adding concept" message when submitting Concept art

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1275]
Kitsu version: 0.17.55
Production type: Film / TV

uploading a new image for concept works ok, but on clicking submit "an error occurred when adding concept" error message appears with the following in JS console in Chrome

Concepts.vue:456 TypeError: crypto.randomUUID is not a function
    at Store.newConcept (concepts.js:90:20)
    at Array.<anonymous> (vuex.esm.js:851:23)
    at Store.dispatch (vuex.esm.js:516:14)
    at Store.dispatch (vuex.esm.js:406:21)
    at concepts.js:82:42
    at Array.map (<anonymous>)
    at Store.newConcepts (concepts.js:82:30)
    at Array.<anonymous> (vuex.esm.js:851:23)
    at Store.dispatch (vuex.esm.js:516:14)
    at Store.dispatch (vuex.esm.js:406:21)

**Comment by NicoPennec** [comment]
Hi @PeteDraper, thanks for the bug report.
Can you give us the name and version of your web browser?

**Comment by PeteDraper** [comment]
OSX Chrome Version 120.0.6099.199 (Official Build) (arm64)

**Comment by NicoPennec** [comment]
Good, you are up-to-date. Your browser must therefore support the "crypto.randomUUID" function.

- Are you on a web page with an `http://` or `https://` URL?
- Do you use your browser's private mode? or a browser extension for privacy? (like *DuckDuckGo Privacy Essentials*)

**Comment by PeteDraper** [comment]
our setup is using http through a vpn. Uploading other files is no issue in other areas of Kitsu. Not using private browsing

**Comment by PeteDraper** [comment]
I think this is solved - can I mark it as closed?

**Comment by EvanBldy** [comment]
Yes :)
