### ISSUE TITLE
@frame behaves weirdly

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1284]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.18.01
Production type: Short

**Describe the bug**

Using the @frame syntax makes the following text up until the next linebreak/line return the clickable link, It does this even if it contains another @frame link - This makes text very hard to read and breaks the link.

When using a list and making sure there is an actual linebreak, the link still works ( but the text is a little harder to read than before )

The old way of only having the time clickable worked better overall ( but that's a design decision so you might think differently )

**How to reproduce**

1. Create a new review with a video
2. Add a comment to the video using two times of the @frame syntax to mark a specific frame, for example `test 123 @frame test 456 @frame test 789`
3. Submit comment
4. Try to use the link to navigate to the time

**Screenshots**

**Input**
![grafik](https://github.com/cgwire/kitsu/assets/58070351/4cfd4c2f-d68f-4fbc-8b7f-6e9ba213d153)

**Output**
![grafik](https://github.com/cgwire/kitsu/assets/58070351/1b92723e-19ef-4cf4-98e1-b59c5511608b)

**Comment by NicoPennec** [comment]
Thanks for your report @tetsuoanimation 🙏 
We will fix this point.

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu v0.18.2
