### ISSUE TITLE
New Asset Page status timeline always shows latest status instead of comment status

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1285]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.18.01
Production type: Short

**Describe the bug**

The new timeline on the asset page shows the latest status for all points in the timeline instead of the status of the comment. ( Best explained by the screenshot )

The actual status in this timeline was wip - review - revise - wip - review - revise but it looks like all comments were 'revise' ( just like the latest comment )

**Screenshots**

![grafik](https://github.com/cgwire/kitsu/assets/58070351/be5f2df5-618c-4044-862a-7991292e988d)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
