### ISSUE TITLE
Development Documentation Typo

### ISSUE THREAD

**Issue by scottmcdonnell** [cgwire/kitsu#1287]
**Context**
Studio name:  JAM Media
Kitsu version: 0.18.2

**Describe the bug**

In [DEVELOPMENT.md](https://github.com/cgwire/kitsu/blob/master/DEVELOPMENT.md?plain=1#L15) - `KITSU_EVENTS_TARGET` should read `KITSU_EVENT_TARGET`

**Comment by NicoPennec** [comment]
Hi @scottmcdonnell 
Thank you for the report 🙏 
This typo will be fixed in the next release.
