### ISSUE TITLE
@frame takes last number in timecode as framenumber

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#1293]
**Context**

Studio name: Ember Light
Kitsu version: 1.18.3

**Describe the bug**

When clicking a @frame link it seems the playlist takes the last number in @frame's timecode and go to that frame instead of the frame number
00:00:02:02 (51) goes to frame 2 but should go to frame 51
00:00:01:14 (39) goes  to frame 14 but should go to frame 39
00:00:01:00 (025) goes  to frame 0 but should go to frame 25

**Video**

https://github.com/cgwire/kitsu/assets/49758407/d83d0b09-70be-40fb-aea1-077258ef0651

**Comment by NicoPennec** [comment]
Fixed in Kitsu 0.18.4.
Let me know if it's good for you now.

**Comment by EmberLightVFX** [comment]
Tested and now works as expected! Great work!
