### ISSUE TITLE
Thumbnail error when the published version is a picture and the "use current frame" option is checked.

### ISSUE THREAD

**Issue by ChristopheMoreau** [cgwire/kitsu#1303]
Studio name: Terminus
Kitsu version: 0.18.4
Production type: Animation

Hi, I was facing a weird bug, but I found the answer in the log, maybe it might be useful to have a warning message when users trying to set the thumbnail from a jpg file, with the "use current frame" option or maybe this option should be unavailable if the media is not a gif nor mov file ?

![image_2024-01-23_132516317](https://github.com/cgwire/kitsu/assets/10652764/44c1cb6d-a63e-43a5-8db1-1d63d006af71)

 - OS: Windows10
 - Opera One(version : 106.0.4998.52)

**Comment by NicoPennec** [comment]
@ChristopheMoreau Thanks for your bug report.
It's fixed on Kitsu 0.19.5, the "use current frame" is only available for video preview.

**Comment by ChristopheMoreau** [comment]
Thanks Nico !
