### ISSUE TITLE
Clicking on same entry multiple times in Notifications advances frames in multiples of 2 in preview window

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1306]
Kitsu version: 0.18.6

clicking on the same entry multiple times in the Notification page, that has a video preview, advances the video every click by 2 frames

 - OS: osx
 - Browser: chrome
 - Version: 120.0.6099.234 (arm64)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
