### ISSUE TITLE
Inconsistencies in UI Design, Selection, Rollover, highlight, UI shading etc.

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1307]
Kitsu version: 0.18.6

Throughout Kitsu, there are multiple different ways which the system showcases rollover shading and selected items, eg in the News feed it's grey bar rollovers and blue selection, whereas in Notifications it's blue rollovers and blue frame selection. This needs to be unified across the platform for consistency.

Additionally, in the Task page (shots, assets etc) the selected task not only needs to be selected, but the entire shot should be highlighted across all tasks (albeit muted) to indicate that this is the shot which is chosen, again, akin to that in the News feed.

The UI design of the Notifications page also needs consolidating or rearranging somewhat as it is wasting space.

News feed needs rearranging also to compensate for larger task names as it moves text across. Thumbnails need to be moved to the left, after the project icon so it is formatted more neatly. The words "commented on" aren't needed as it is always a comment, thus:

time (icon) (thumbnail) ep/scene/shot (task) (status) (avatar) Name

same can be used for Notification page, except with the comment text added underneath.

Again, all of this is to ensure a conformity across the platform, making it feel more polished.

Thanks - Pete

 - OS: osx
 - Browser: chrome
 - Version: 120.0.6099.234 (arm64)

**Comment by frankrousseau** [comment]
We made a new version covering most of the aspects you mention. 
Notifications will require more work.
