### ISSUE TITLE
Preview player - remember last settings to keep comments panel open

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1314]
As mentioned, please allow for the preview window's last settings for the comments. Exiting full screen and then re-entering forgets them, even in the same task.

**Comment by frankrousseau** [comment]
What do you mean by settings?

**Comment by PeteDraper** [comment]
genuinely can't remember - I logged this in Jan. I've slept since then...! :D remove it - if it comes up again, I'll log it. Marking as closed
