### ISSUE TITLE
project icon doesn't update if already added without something else changing in the project settings page

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1319]
kitsu 0.18.6

OSX Chrome

after adding an icon to the project, changing the icon has no effect unless another item in the project settings is adjusted, eg Homepage - changing from Assets to Shots.

Haven't tried with other filetypes, but have noticed this today with pngs

**Comment by PeteDraper** [comment]
not sure if it's related, but if you have the Productions list and/or the My Productions page open in another tab, it doesn't update, even if you manage to update the icon. Refreshing doesn't work and need to close the page and re-open. Not sure if it's a cache issue or if it's related to the icon not updating, or if said Productions page being open is causing the icon to not update.

**Comment by NicoPennec** [comment]
Thanks for the report.
Issue fixed on Kitsu >= 0.20.0
