### ISSUE TITLE
clicking on a production in Production list only takes you to Assets page

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1320]
**Context**

Studio name: 
Kitsu version: 0.18.6

clicking on a production in Production list only takes you to Assets page, despite if you have set Shots as your homepage. The correct ability only seems to work from the My Productions page.

Not a major issue, just a heads up :)

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu >= 0.19.1
Let me know if it works for you.
