### ISSUE TITLE
changing project icon stays when changing projects in menu

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1321]
Kitsu version: 18.6

When changing an icon in the project's settings (and applying), changing a project from the pulldown menu changes the page info, but does not clear out the Change Picture image chosen. If you change any item in the second project and click OK, the icon will be changed to the previous project's one

**Comment by NicoPennec** [comment]
Thanks for the report.
Issue fixed on Kitsu >= 0.20.0
