### ISSUE TITLE
unable to upgrade-db and thus make production

### ISSUE THREAD

**Issue by comicsserg** [cgwire/kitsu#1325]
**Context**

Studio name: 
Kitsu version: 0.18.9
Production type: 

**Describe the bug**
I am getting  An error occurred while creating the production 
![Screenshot from 2024-01-31 22-14-40](https://github.com/cgwire/kitsu/assets/63783506/7abe39cf-79c7-4f82-aa13-36f641dc35eb)

I tried to run upgrade-db like this:
DB_PASSWORD=mysecretpassword /opt/zou/zouenv/bin/zou upgrade-db

and it gives me this error at the end:

Link set default roles_for_board
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/cli.py", line 108, in upgrade_db
    telemetry_services.send_main_infos()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/telemetry_services.py", line 26, in send_main_infos
    "organisation_id": str(organisation.id),
AttributeError: 'NoneType' object has no attribute 'id'

I was following this manual:
https://zou.cg-wire.com/#deploying-kitsu

***Desktop (please complete the following information):**

 - OS: Ubuntu 22.04.3 LTS
 - Browser firefox
 - Version 116.0.2

**Comment by EvanBldy** [comment]
Hi @comicsserg, thanks for the report ! 
I have done a fix for that, I will do a new release for Zou in like 1 hour, can you try with this release and close the issue if it's good for you ?

**Comment by comicsserg** [comment]
@EvanBldy thank you for the fix.
I updated zou by running:
`sudo /opt/zou/zouenv/bin/python -m pip install --upgrade zou`

Update database schema
`DB_PASSWORD=mysecretpassword /opt/zou/zouenv/bin/zou upgrade-db`

Finally, restart the Zou service:
```
sudo systemctl restart zou
sudo systemctl restart zou-events
```
I am running: 0.18.6

I am able to upgrade-db now and when click to create production it goes good but then I only see white screen and cannot choose anything from the drop down
![Screenshot from 2024-02-01 07-28-57](https://github.com/cgwire/kitsu/assets/63783506/a464a4bf-76b3-4e90-b11c-df23aa3ded3b)

Not sure if I maybe need to clear everything from the database and start from scratch?

**Comment by comicsserg** [comment]
I cleared db and upgraded and then initialised and now it working :)

```
DB_PASSWORD=mysecretpassword /opt/zou/zouenv/bin/zou clear-db
DB_PASSWORD=mysecretpassword /opt/zou/zouenv/bin/zou upgrade-db
DB_PASSWORD=mysecretpassword /opt/zou/zouenv/bin/zou init-data
```

**Comment by comicsserg** [comment]
thank you
