### ISSUE TITLE
Calender shows one day less than it should

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#1328]
Studio name: Ember Light AB
Kitsu version: 0.18.9

**Describe the bug**

If I set a task to 1 or 2 days it only shows up as 1 day in the artists calendar. If I set the task to 3 days, it shows as 2 days and so on

**Screenshots**

https://github.com/cgwire/kitsu/assets/49758407/a806ff8a-bdfc-45e4-901e-d29d0399f6d4

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser Firefox and Edge
 - Version Firefox 122, Edge 121

**Comment by frankrousseau** [comment]
Thank you for the report!

**Comment by NicoPennec** [comment]
@EmberLightVFX thanks. Fixed on Kitsu [0.18.10](https://github.com/cgwire/kitsu/releases/tag/v0.18.10)
