### ISSUE TITLE
Notification comment panel is not resizable

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1331]
Kitsu version: 0.18.8

in the task view (eg shots) page you can expand the comments panel to make ti bigger or smaller, however in the Notifications page we can't amend the size. However, it does adopt the size that you last set the panel to, either in the task page or news page.

**Comment by frankrousseau** [comment]
Thank you for the report Pete

**Comment by NicoPennec** [comment]
Fixed on Kitsu >= 0.19.x
