### ISSUE TITLE
Using the filter windows only kept one filter

### ISSUE THREAD

**Issue by ChristopheMoreau** [cgwire/kitsu#1338]
The "second filter" is not working
If I'm using the filter windows, add the status filter and the priority filter and clic confirm, there's only the second filter in the text line

![image](https://github.com/cgwire/kitsu/assets/10652764/4ad9d48e-b5ab-459e-b31a-58b1833aa69a)
![image](https://github.com/cgwire/kitsu/assets/10652764/4863c116-4464-4ebf-95bc-fb424461c7d5)

**Comment by NicoPennec** [comment]
@ChristopheMoreau  Thank you for reporting the bug  🙏 

Issue fixed on Kitsu >= 0.19.10
