### ISSUE TITLE
[localCompare in sorting] Wrong sorting when values are numeric

### ISSUE THREAD

**Issue by lesmoutonssauvages** [cgwire/kitsu#1353]
**Describe the bug**
Hello!

I want to use numeric value in my shot name.

<img width="168" alt="Capture d’écran 2024-02-22 à 10 48 51" src="https://github.com/cgwire/kitsu/assets/40919200/5c076008-a1cd-462c-8142-2fe9b9fdec2a">

You use localcompare to sort them: So "10" is before "8".

If you use ```a.name.localeCompare(b.name, undefined, { numeric: true })```
<img width="472" alt="Capture d’écran 2024-02-22 à 11 04 51" src="https://github.com/cgwire/kitsu/assets/40919200/81ae1e82-ae0c-4fa0-a719-5d01f13741b6">

Sorts are corrects for numeric values AND your nominal behavior
 
<img width="165" alt="Capture d’écran 2024-02-22 à 10 48 58" src="https://github.com/cgwire/kitsu/assets/40919200/0337eb4f-49e9-4dc5-b477-081a80eff36b">
<img width="181" alt="Capture d’écran 2024-02-22 à 10 49 07" src="https://github.com/cgwire/kitsu/assets/40919200/f577416b-6da8-4063-8200-81f6cb52d90f">

Just tested for sequences and shots, i guess it's the same for other entities (edits, assets, etc)

**Comment by NicoPennec** [comment]
Thanks @lesmoutonssauvages 🙏 
It seems a smart proposal. We will look to implement this soon.

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu >= 0.19.11
