### ISSUE TITLE
Add ability to copy/forward client notes to artist

### ISSUE THREAD

**Issue by tpolson** [cgwire/kitsu#1364]
I understand the issues with sending client notes to artist, but sometime it makes life a lot easier. If client sends a markup or good notes, it takes a lot of time to save the their markup and reload and copy and paste their notes.

Something as simple as forwarding the note with option to edit it to anyone in the production would be great. 

https://cgwire.canny.io doesn't seem to be working.

**Comment by frankrousseau** [comment]
There is already a button to push a client comment into the comment area. Could it work for you?
