### ISSUE TITLE
android chrome mobile - cannot login but in desktop mode login works

### ISSUE THREAD

**Issue by PeterisSudakovs** [cgwire/kitsu#1372]
**Context**

Studio name:  Filmu Studija Lokomotive
Kitsu version:  0.19.12
Production type:  self-hosted

**Describe the bug**

android chrome mobile - cannot login but switching the tab to desktop mode = login works ok
after login - switching back to regular mode = works ok

/opt/zou/logs/gunicorn_access.log

failed login:
127.0.0.1 - - [07/Mar/2024:20:35:05 +0200] "GET //data/organisations HTTP/1.0" 200 364 "https://test.example.com/login" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:35:10 +0200] "POST //auth/login HTTP/1.0" 200 1736 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:35:11 +0200] "GET //auth/authenticated HTTP/1.0" 401 114 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:35:11 +0200] "GET //data/organisations HTTP/1.0" 200 364 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36"

success:
127.0.0.1 - - [07/Mar/2024:20:36:13 +0200] "GET //config HTTP/1.0" 200 67 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:36:15 +0200] "POST //auth/login HTTP/1.0" 200 1296 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:36:16 +0200] "GET //auth/authenticated HTTP/1.0" 200 1310 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:36:16 +0200] "GET //data/user/context HTTP/1.0" 200 6923 "https://test.example.com/login?redirect=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
127.0.0.1 - - [07/Mar/2024:20:36:16 +0200] "GET //pictures/thumbnails/organisations/210fecff-57a3-4093-9bb4-60aa6bc88040.png HTTP/1.0" 304 0 "https://test.example.com/open-productions" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/53

**Screenshots**

![Screenshot_20240307_202804_Chrome](https://github.com/cgwire/kitsu/assets/46196343/7322671d-e2e6-490f-b30c-31acb4065788)

then selecting the "desktop site" in the options:

![Screenshot_20240307_202813_Chrome](https://github.com/cgwire/kitsu/assets/46196343/c9a2745e-edf2-429e-b491-8e50f6ba204e)

login works:
![Screenshot_20240307_202825_Chrome](https://github.com/cgwire/kitsu/assets/46196343/4573f552-1bab-4ed8-94d8-c76d5443b2bf)

Hosted on:
Ubuntu 22.04.4 LTS
{"api":"Zou","version":"0.19.12"}
NginxProxyManager v2.11.1

**Mobile:**
 - OS: Android 13, Samsung One UI 5.1
 - Browser: Chrome 
 - Version 122.0.6261.91

**Comment by NicoPennec** [comment]
Thanks for your report @PeterisSudakovs 👍 
Issue fixed on [Zou 0.19.13](https://github.com/cgwire/zou/releases/tag/v0.19.13)
