### ISSUE TITLE
http Link in description

### ISSUE THREAD

**Issue by ChristopheMoreau** [cgwire/kitsu#1377]
**Context**

Studio name: Terminus
Kitsu version: 0.19.6
Production type: VFX

**Describe the bug**

When you have an internet link inside the description, when you clic on it, the web browser open only the "preview" string not the full link. and also opening in the same tab, it would be nice if the link open in a new one.

Kitsu visible description
![image](https://github.com/cgwire/kitsu/assets/10652764/17c55bb2-bccc-4826-9d4a-210fea73f210)

Link open in the browser
![image](https://github.com/cgwire/kitsu/assets/10652764/aa24c814-9924-42e4-84d1-79c098c834a0)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] chrome & opera & Edge

**Comment by NicoPennec** [comment]
Thanks for your bug report @ChristopheMoreau
I pushed a fix in the latest version (Kitsu >= 0.19.19).
The link should not be directly clickable on the shortened description, but a click on it will open a pop-up with the full description (with working links).
