### ISSUE TITLE
Unable to join translation

### ISSUE THREAD

**Issue by uuiid** [cgwire/kitsu#1387]
**Describe the bug**
I want to contribute to translation, but I am unable to join

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/46096697/54ece8a7-33d0-4b74-894d-734639dfe2fb)

**Comment by frankrousseau** [comment]
Hello @uuiid, thank you for reporting. We'll check that soon.

**Comment by frankrousseau** [comment]
It seems to be fixed.
