### ISSUE TITLE
UI Theme : the confirm button is not always the 'default' button

### ISSUE THREAD

**Issue by developer-cube-creative** [cgwire/kitsu#139]
When suppressing an asset, the 'cancel' button is green, while when creating it the 'confirm' button is green. 

That's confusing :)

![confirm-01](https://user-images.githubusercontent.com/26791257/46490181-97afb080-c807-11e8-9b26-2a529194fad2.PNG)

![confirm-02](https://user-images.githubusercontent.com/26791257/46490184-9aaaa100-c807-11e8-91e9-a84db411a1dd.PNG)

**Comment by frankrousseau** [comment]
Thank you for reporting this issue. We'll fix that soon!

**Comment by frankrousseau** [comment]
We changed the color scheme for deletion windows. Can you check again and tell us what you think about it?

**Comment by developer-cube-creative** [comment]
That's perfect ! Thank you
