### ISSUE TITLE
Comments: dot separted numbers generates the creation of an ordered list when comment is posted

### ISSUE THREAD

**Issue by mdk-man** [cgwire/kitsu#1396]
**Context**

Studio name: independant
Kitsu version: 0.18.10
Production type: 

**Describe the bug**

When adding a comment on a task, typing numbers separated by a dot on a new line will generate an ordered list (ol tag).
Typed numbers are replaced by an automatic and random numbering (displayed information is different from the written content). 

Users can't reference shots as "xx. yyy" (where xx is seq nb, yyy shot nb) in a comment. As a workaround users can use a coma instead.

**Screenshots**

See attachment

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Firefox
 - Version 124

![kitsu_figures_bug](https://github.com/cgwire/kitsu/assets/73103726/521984e5-b87b-49ba-97e1-d8929ccb877d)

**Comment by NicoPennec** [comment]
The comment is parsed as a markdown text, so the "number + dot" notation generates an ordered list.

The workaround is to escape the dot with a reverse slash as below to rendering 1\. 3\. 15\. 20

```md
1\. 3\. 15\. 20
```

**Comment by tetsuoanimation** [comment]
Please don't remove markdown 😉 - we use it a lot!

Maybe parsing as a list can be constrained to a newline before the number or a dash?

( Related when implementing this might be that a simple <enter> newline is not parsed as a newline in comments - you need to press it twice and have a blank line right now )

**Comment by frankrousseau** [comment]
The @NicoPennec looks good.
