### ISSUE TITLE
Increase the number of productions visible in the pull-down menu to a larger amount, or give ability for the user to define this

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1398]
Currently the pull-down menu in the Task page (etc) only gives a maximum of 5 visible entires - any more and you have to scroll down. Please increase this to a larger number or give the user the ability to amend the amount visible. 

Additionally, having the ability to jump to a project by hitting the character of the start of the project, eg T for Toy Story would jump to that entry. Would also be useful in the Productions page esp with a lot of active & inactive projects

**Comment by PeteDraper** [comment]
The Productions list works great - seems to be set to 1/2 the height of the page. If possible, please apply the same logic to the Episodes pull-down menu

**Comment by frankrousseau** [comment]
It will be fixed in the next release.
