### ISSUE TITLE
Can't remove Task from project if it is Archived

### ISSUE THREAD

**Issue by BenoitGielly** [cgwire/kitsu#1418]
**Context**

Studio name: Stim Studio
Kitsu version: Kitsu 0.19.23
Production type: Any

**Describe the bug**

If you globally archived a task type, it is not possible to remove it from a Project in which it was used.
When clicking "Confirm" it does nothing and there's an error in the browser console (see screenshot).
If I unarchive the task type, then I can remove it (but I have to archive it again)

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/17833821/ed57642d-d088-4e01-8a25-d9ba636d1a41)

**Desktop (please complete the following information):**

 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 123.0.6312.124

**Comment by NicoPennec** [comment]
Thanks for the report @BenoitGielly 🙏  
I reproduced the issue. We'll take a look.

**Comment by NicoPennec** [comment]
Fixed on [Kitsu v0.19.27](https://github.com/cgwire/kitsu/releases/tag/v0.19.27)
