### ISSUE TITLE
Can't restore a shot after deletion as a supervisor

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#142]
Issue : As a supervisor I can delete a shot the first time (the shot is crossed), but I can't delete it for good, I have an error message
![error](https://user-images.githubusercontent.com/42962633/46535870-f54a0880-c8ac-11e8-9eba-069dd6e6bd85.PNG)

**Comment by frankrousseau** [comment]
It should be fixed. Can you check again?

**Comment by gwendupre** [comment]
It works thanks
