### ISSUE TITLE
"All" and "Main pack" missing from episode dropdown under Assets

### ISSUE THREAD

**Issue by MadsHangaard** [cgwire/kitsu#1428]
**Context**

Studio name: Mint Copenhagen
Kitsu version: 0.19.28
Production type: Animation

**Describe the bug**

When loading the URL. Clicking on the project icon under "My productions" on the front page (domain.cg-wire.com/open-productions). This takes me to the asset page. Then unfolding the episode dropdown, the option for "all" and "main pack" is missing. The options return if you reload the page.

**Screenshots**

<img width="748" alt="image" src="https://github.com/cgwire/kitsu/assets/64668067/9ad2bd8e-368e-4584-b495-f85d40dac944">

**Desktop (please complete the following information):**

 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version: 124.0.6367.72

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in the next release.

**Comment by NicoPennec** [comment]
Fix pushed on Kitsu 0.19.54
