### ISSUE TITLE
Unable to add new departments into production

### ISSUE THREAD

**Issue by Haika-IT** [cgwire/kitsu#1429]
Studio name: IT
Kitsu version: OpenSource
Production type: Animation and VFX 

Only the default Departments are shown in the dropdown menu in the shots page of kitsu. New user added departments are not shown.
Edited: We can only add departments by adding the studio task types with those departments in the production.
Current Solution: But for metadata, we have to create a temporary task type with that department and then add the department in the addMetadataBlock

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser chrome

**Comment by NicoPennec** [comment]
hi @Haika-IT ,

This dropdown menu is a department filter that lists only the departments used in task types linked to the current production.
I'm not certain I understand your request. Could you provide a specific example to help me understand better?

**Comment by frankrousseau** [comment]
It's the expected behaviour. A department must have related task types to be active in the production.
