### ISSUE TITLE
Text Out of Bounds

### ISSUE THREAD

**Issue by Haika-IT** [cgwire/kitsu#1431]
**Context**

Studio name: IT
Kitsu version: Open Source
Production type: Film

**Describe the bug**
Text Out of Bounds in Artists' production page in a text field for metadata(Both given and user created)

**Desktop (please complete the following information):**

 - OS: Multiple OS in both windows and ubuntu
 - Browser: chrome

**Comment by NicoPennec** [comment]
Hi @Haika-IT,

The text field for metadata has no size limit.

Is your text exceeding the limits in the database or visually?
What versions of Kitsu and Zou (KitsuAPI) are you using?
