### ISSUE TITLE
Automation not working

### ISSUE THREAD

**Issue by NTKKS** [cgwire/kitsu#1435]
**Context**

Studio name: Quanti s.r.o.
Kitsu version: Kitsu 0.19.17

**Describe the bug**

Hi, I set up automation and added it to my project but it is not being triggered
When I set animation to edit it wont change UE_shot status

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/43784192/b104ff4e-f768-4207-8855-59b1e5425dd2)

**Desktop (please complete the following information):**

 - OS: Win 11 Pro
 - Browser: Chrome

**Comment by EvanBldy** [comment]
Hi @NTKKS,
Can you please upgrade to the latest versions of Kitsu and Zou ?
When you upgrade Zou do also a `zou upgrade-db`.
