### ISSUE TITLE
Increase the space to drop files

### ISSUE THREAD

**Issue by Chantology** [cgwire/kitsu#1438]
Studio name: Woodblock
Kitsu version: 0.19.12
Production type: Short

This is just an enhancement. In the past I was often asked if drag and drop works. It works but the space where to place the files is quite small. Is it possible to increase it? Some other online pages change the whole area to a "Drop here" so it doesn't happen that you drop the file next to it and then it opens a new tab showing the file. 

![Screenshot 2024-04-30 151349](https://github.com/cgwire/kitsu/assets/50327807/3d08910b-afd5-454e-94de-829ac788f9c9)

**Desktop (please complete the following information):**

 - OS: Windows 
 - Browser Chrome 
 - Version 124.0.6367.208

**Comment by aka-anoop** [comment]
I am a little confused about the requirement. The Modal already shows a "Drop here" overlay when you drag things above it
(video attached).
https://github.com/user-attachments/assets/3c56aa35-c3a1-4e33-a924-182640ee64a3
Does it mean it is fixed, but the ticket is still open?

**Comment by Chantology** [comment]
true, do you use a newer version? Maybe this is already fixed then.

**Comment by frankrousseau** [comment]
It's fixed in the latest version.
