### ISSUE TITLE
Sequence description error (size limit reached)

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#1443]
**Context**

Studio name: Les Fées Spéciales
Kitsu version: 0.19.28
Production type: Feature

**Describe the bug**

When editing the description of a Sequence in the sequence page, if the description is too long there is an error message. But the error message does not suggest it's a size issue, but a sequence name issue (see screenshot 1).
But when enough characters are removed (with a maxium of something close to 1200 - it did not look a fixed number in our different tests), the text is saved.
That said, the response in the developer tools, already explains it's something relatad to text size (see screenshot 2).

We could have a character counter displayed when we are at 80% of the limit, and then an error message related to the text size. It will help non technical users to understand the issue.

have a good day !

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/870195/da3876e0-afb7-495b-b36c-de21fc835393)
![image](https://github.com/cgwire/kitsu/assets/870195/e32df41f-2af3-41fe-a597-2cfd4fd84a17)

**Desktop (please complete the following information):**

 - OS: All
 - Browser Firefox/Chrome
 - Version [latest]

**Comment by EvanBldy** [comment]
Hi @flablog,
Thanks for the report, 
I have allowed to set a description of any length in this PR https://github.com/cgwire/zou/pull/812.
