### ISSUE TITLE
Comment edition gives a blank page

### ISSUE THREAD

**Issue by developer-cube-creative** [cgwire/kitsu#147]
Hello,

We tried to edit a comment that has an image attached to it.
When clicking "confirm" the page turns blank ...

* Step 1
![step-1](https://user-images.githubusercontent.com/26791257/47653485-fce98e00-db88-11e8-8807-22db6b37c37f.JPG)

* Step 2
![step-2](https://user-images.githubusercontent.com/26791257/47653491-feb35180-db88-11e8-94b8-0f0576f9ea0f.JPG)

* Step 3
![step-3](https://user-images.githubusercontent.com/26791257/47653494-ffe47e80-db88-11e8-99e1-b93c89736c9e.JPG)

Thank you

**Comment by gwendupre** [comment]
It should be fixed, could you retry and let us know?

**Comment by developer-cube-creative** [comment]
Yes ! Thank you very much !
