### ISSUE TITLE
Dark theme: Markdown table row unreadable on hover, headers hard to read

### ISSUE THREAD

**Issue by Plyrolith** [cgwire/kitsu#1471]
**Context**

Kitsu version: 0.19.30

**Description**

When "Dark Theme" is selected, markdown formatted table rows are rendered with white-on-white text when hovered.
Table headers and headers in general are also hard to read, since they're drawn in dark grey (on lighter gray).

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/49444317/12f0b8f0-b340-40a9-b372-9e4b11277264)

**Desktop:**

 - OS: Fedora Linux 40, AlmaLinux 9
 - Browser: Chrome, Chromium, Firefox
 - Version: Latest

**Comment by NicoPennec** [comment]
Thanks for the report @Plyrolith  👍 
This issue will be fixed in the next release of Kitsu (> 0.19.45)
