### ISSUE TITLE
Cannot add Task Status options for Concept

### ISSUE THREAD

**Issue by jason-mightynice** [cgwire/kitsu#1472]
**Context**

Studio name:  Mighty Nice
Kitsu version: 0.19.43
Production type:  2d/3d Animation

**Describe the bug**

 In the Task Status settings, we can see Task Status for Entities, and underneath is Task Status for Concepts. At the top is the Add New Task Status, but that only adds it to the Entities list .

**Screenshots**

**Desktop (please complete the following information):**

 - OS: All
 - Browser  Chrome
 - Version 126.0.6478.127

**Comment by frankrousseau** [comment]
Concepts have no customisable status.
