### ISSUE TITLE
Image annotations not showing

### ISSUE THREAD

**Issue by developer-cube-creative** [cgwire/kitsu#148]
Hello,

Images annotations are really great but there seems to be a bug.

To reproduce
- add an image to a comment
- draw on top of it
- go back to asset view
- the drawings have desappeared

Tested on chrome and firefox

Also, when you switch to full screen and interact with the view, drawings show up, I suspect a (z-order bug, maybe related to the fact that the image is a fixed widget on the canevas ?)

Here is a GIF illustrating the process

![anotations-ticket](https://user-images.githubusercontent.com/26791257/47654580-67033280-db8b-11e8-8f7a-ed363c24d717.gif)

Thank you

**Comment by gwendupre** [comment]
Hi, it should be fixed now, could you try again and let us know?

**Comment by developer-cube-creative** [comment]
Yes ! Thank you very much !
