### ISSUE TITLE
Wrong production style displayed in the production edit web page

### ISSUE THREAD

**Issue by hww-clementpoulain** [cgwire/kitsu#1507]
Hi Nicolas,
As per Discord, here is a github issue regarding bellow bug from the web interface:
WQhile being in a production edit page web page, its style is always displayed as "2d Animation" even though it's set actually to something else, like "Commercial".

Kitsu 0.19.53
Ubuntu 22.04.4
Chrome 124.0.6367.60 (Official Build) (64-bit)

**Comment by NicoPennec** [comment]
Hi Clement,
A fix is ready and will be shipped on the next release of Kitsu >= 0.19.54 (see https://github.com/cgwire/kitsu/pull/1506)

**Comment by NicoPennec** [comment]
Fix pushed on Kitsu 0.19.54
