### ISSUE TITLE
23.976 fps preview videos are incorrect

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu#1520]
**Context**

Studio name: Imaginary Pixels
Kitsu version: 0.19.53
Production type: Ffeature film

**Describe the bug**

When a MOV with 23.976 fps is uploaded to Kitsu the first frame gets doubled and last frame cut of.

**Desktop (please complete the following information):**

 - OS: Ubuntu 
 - Browser Chrome
 - Version 128.0.6613.84

**Comment by lukas-remis** [comment]
Ahh, sorry. I though my previous issue report was gone. I didn't notice I posted the other one for zou. Feel free to close one of those.

**Comment by NicoPennec** [comment]
@lukas-remis We have transferred the issue to the right repository 😉
