### ISSUE TITLE
Shots no longer availabe after re open closed project

### ISSUE THREAD

**Issue by hnegadi** [cgwire/kitsu#1523]
Hello.
We had to reopen a closed project. We were using 0.19.8 when we closed it
Until then we ran a few updates up to 0.19.47
Now we tried to reopen the project with v 0.19.47 and we no longer have neither shots nor playlists available.

Thankfully we kept an old VM with v 0.19.8 running our project but we would need to import that data into our production VM which runs 0.19.47.

Thank you.

**Comment by NicoPennec** [comment]
Hi @hnegadi,
Have you also updated Zou, the Kitsu API component?
If yes, from which version to which version?

In addition, if your Kitsu appears to be functioning but no data is loading, you need to check the Zou error logs on your VM (see [documentation](https://zou.cg-wire.com/troubleshooting/#error-logs)).

**Comment by hnegadi** [comment]
Yes we've updated zou before updating kitsu.
I worked fine for all others projects except this closed one.
We run the update script attached once every two months
![Screenshot 2024-09-04 131934](https://github.com/user-attachments/assets/efb34e72-1f16-41e8-88dc-cf09804f6347)

**Comment by NicoPennec** [comment]
Ok, it looks good for Zou's update 👍 

Have you checked your Zou error logs?
