### ISSUE TITLE
Fullscreen video not scaled properly if annotated

### ISSUE THREAD

**Issue by developer-cube-creative** [cgwire/kitsu#153]
When a video is anotated, its not showing properly on fullscreen mode

![image](https://user-images.githubusercontent.com/26791257/48147422-91ee3480-e2b7-11e8-845c-1cae73446fbc.png)

Thank you

**Comment by frankrousseau** [comment]
Thank you for the bug report. It should be fixed. Can you try again?

**Comment by developer-cube-creative** [comment]
It seems ok (Chrome & Firefox) ! Thank you very much !
