### ISSUE TITLE
Department tags aren't in popup if you're a member of the same department

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1538]
Kitsu version: 0.19.59

Example:
Am a member of a dept called Production. If I want to tag the dept in a post, @Production will not appear in the user / departments list that pops up when typing, suggesting it's not possible to tag your own dept. 

workaround - type the full name out, ensuring case sensitivity - eg @Production will work while @production will not.

**Comment by NicoPennec** [comment]
Hi @PeteDraper,

I attempted to reproduce the bug, but was unsuccessful.
Do you have an error message in your [web developer console](https://screenful.com/guide/how-to/how-to-open-the-browser-developer-console)?

We will need additional details, please.
What browser do you use?
Are you on a specific page or section of Kitsu?
Does the department name have non-Latin characters?

**Comment by PeteDraper** [comment]
browser: chrome
section - task page

I am a member of the Production group, not the Conformation group (see attached video)

https://github.com/user-attachments/assets/3f5944ec-b6c9-4014-93d0-0e6a82651868


no non-latin characters

**Comment by NicoPennec** [comment]
In fact, the list of proposed departments in the popup doesn't depend on your departments, but on the departments associated with the task types of the current production.

Are there any task types associated with your production that don't have departments?

**Comment by PeteDraper** [comment]
There are people from other departments in some groups. As those in the production group (studio level) are not associated with that task / not have tasks assigned, this may be the issue.

**Comment by NicoPennec** [comment]
It's should be fixed on Kitsu >= 0.19.75

I'll let you check and close this bug report if everything looks correct now.
