### ISSUE TITLE
'My Checks' page doesn't updte with 'Sorted By'

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1540]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.19.58
Production type: Short

**Describe the bug**

On the 'My Checks' Page, the list doesn'tupdate when changing the fields 'sorted by'. It gets updated as soon as any other field is changed.

**Desktop:**

 - OS: Windows 10 + Windows 11
 - Browser Chrome

**Comment by NicoPennec** [comment]
Thanks @tetsuoanimation for the bug report 🙏 
It's fixed on Kitsu 0.19.72
