### ISSUE TITLE
Summary Graphs on the Productions Page are incorrect / visuals don't match data

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1543]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.19.58
Production type: Short

**Describe the bug**
Data in the Productions stats is wrong ( or displayed wrong ) and include deleted or closed shots / episodes.
I wrote the numbers of the tasks as in the screenshot below. Could it be that this counts alltask changes ever instead of thw current project status?

**Screenshots**
![grafik](https://github.com/user-attachments/assets/efa2284e-c145-47b6-b50b-6e7c39d8f9b4)

**Desktop (please complete the following information):**

 - OS: Windows 10+11
 - Browser Chrome

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in the next release.
