### ISSUE TITLE
Assets breakdown : missing asset types in drop down

### ISSUE THREAD

**Issue by manuelrais** [cgwire/kitsu#1545]
**Context**

Studio name: TNZPV
Kitsu version: 0.19.61
Production type: TV Show

**Describe the bug**

On the breakdown page, when choosing asset type in drop down, almost every asset types are missing except one.

Here is the asset types list in instance settings : 
![asset_types](https://github.com/user-attachments/assets/bc84e9dc-13b3-4274-829a-4890e8fc3421)
Here is the drop down in the breakdown page :
![image](https://github.com/user-attachments/assets/5b4272d2-9400-4bf3-8c51-a39dcbb43d31)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] Rocky Linux 9.3
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 115.10.0esr

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu 0.19.63
