### ISSUE TITLE
Documentation - 404 - Broken Links

### ISSUE THREAD

**Issue by websterek** [cgwire/kitsu#1548]
**Describe the bug**

Some links in the Kitsu Documentation are broken. I have found three of them at: https://kitsu.cg-wire.com/short/:
- [Studio Workflow](https://kitsu.cg-wire.com/first_production/README_configure_Kitsu.html#studio-workflow)
- [Import asset](https://kitsu.cg-wire.com/batch-action/#create-assets-from-a-csv-spreadsheet-file)
- [Import shot](https://kitsu.cg-wire.com/batch-action/#create-shots-from-a-csv-spreadsheet-file)

**Screenshots**

![image](https://github.com/user-attachments/assets/3071632c-1b5f-4d48-80f8-fd217507d65f)

**Desktop (please complete the following information):**

 - OS: Windows/Linux/Android
 - Browser: Chrome/Edge

**Comment by NicoPennec** [comment]
Thanks @websterek for the report 👍 
The links have been fixed.
