### ISSUE TITLE
Thumbnail Generates a Frame Early

### ISSUE THREAD

**Issue by makermatic** [cgwire/kitsu#1566]
**Context**

Kitsu version: 0.19.69
Production type: Feature Film

**Describe the bug**

When I open the playhead for an asset

**Screenshots**
<img width="1913" alt="Screenshot 2024-10-29 at 1 42 37 PM" src="https://github.com/user-attachments/assets/5d5de8d1-8df3-428e-bfdf-9c7e082ce3a0">

**Desktop (please complete the following information):**

 - OS: MacOS
 - Browser Edge

**Comment by NicoPennec** [comment]
Have you checked the "Use current frame" checkbox before clicking on the "Set current preview as thumbnail" button?

**Comment by makermatic** [comment]
Thats what I've been doing. But it still captures a frame early.

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in the next release.

**Comment by NicoPennec** [comment]
Fix available on Kitsu >= 0.20.1
