### ISSUE TITLE
How to delete the Production project completely?

### ISSUE THREAD

**Issue by ashutosh-sm** [cgwire/kitsu#1567]
**Context**

Kitsu version: 0.19.69
Production type: 

**Describe the bug**

I cannot delete the Production project I created for testing as there is no delete button!

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser: chrome

**Comment by NicoPennec** [comment]
Go to section Studio > Productions, edit your project with status=closed, and then you can delete this project from the "closed" project list.

**Comment by ashutosh-sm** [comment]
![kitsu](https://github.com/user-attachments/assets/029ef60e-821f-46a8-b357-6058ad01bebd)
I'm at the studio section, but I don't see any production button here..

**Comment by ashutosh-sm** [comment]
sorry, now I found what you were saying. Thanks a lot
