### ISSUE TITLE
Display cannot show more than 60 assets

### ISSUE THREAD

**Issue by CeliaCsn** [cgwire/kitsu#157]
Hello again !

The display on the main view of a project cannot show more than 60 assets for the moment. 
Would it be possible to increase that number so we can have an overview of all our assets needed on the project ? 

![display](https://user-images.githubusercontent.com/44972777/48352151-5cb55e00-e68c-11e8-8834-cad96e03c059.JPG)

Here I can only look till F, and not after :'(
Thanks !

**Comment by gwendupre** [comment]
it's fixed!
