### ISSUE TITLE
When Kitsu is switched to Japanese, a piece of the personal menu remains displayed

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#1571]
**Context**

Studio name: gwen
Kitsu version:  0.19.72
Production type: all

**Describe the bug**

When you change Kitsu's language to Japanese (and only Japanese), you'll immediately see the bottom menu appear below the avatar, and will remain present on all Kitsu pages.

**Screenshots**

![bug-japonais](https://github.com/user-attachments/assets/5566b966-3f89-486f-8be2-058b6754ec8a)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome
 - Version 130.0.6723.92 (Build officiel) (64 bits)

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu v0.19.73
