### ISSUE TITLE
Changing Project on Playlist page doesn't update playlist & shots list.

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1586]
More often than not, changing projects (tv shows) doesn't update the shot list in a selected playlist. 

eg we have one playlist selected in project A. Switch to project B. Playlist list (most of the time) updates. Select a playlist from an episode. Result: no shots visible in playlist. We have to refresh the page and reselect the playlist for the shots to be visible.

kitsu 0.19.73 - chrome

**Comment by NicoPennec** [comment]
Hi @PeteDraper 

I don't reproduce this behavior in Kitsu v0.20.4
Could you please check again on the latest release?

**Comment by PeteDraper** [comment]
confirmed - I think it has been resolved. Marking as closed - will re-submit if it comes back.
