### ISSUE TITLE
Preview is not the last if older preview is pinned

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#1587]
**Context**

Studio name: Les Fees Speciales
Kitsu version: 0.19.66
Production type: *

**Describe the bug**

On the asset page, when clicking on a task, you may not have the last preview revision displayed by default if an older comment WITH a revision is pinned.
in that case, the pinned comment revision is displayed by default, which is confusing for the artists.

**Screenshots**
in this screenshot, the comment wiht revision 2, is older, but pinned. SO it's displayed on the top of the comment list. But the movie selected by default is also the pinned one as the order of the revisions is altered on the selector 
![image](https://github.com/user-attachments/assets/7ec3749f-4ffb-441b-8830-34ecc06e7e0f)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] Any
 - Browser [e.g. chrome, safari] any

**Comment by NicoPennec** [comment]
Fixed on Kitsu 0.19.75
