### ISSUE TITLE
Editing additional information field after shot creation doesn't update it

### ISSUE THREAD

**Issue by johhnry** [cgwire/kitsu#1592]
**Context**

Studio name: Welcome To Love
Kitsu version: 0.19.65
Production type: Short

**Describe the bug**

Just after creating a shot in the `Shots` page, if I have the `Show additional information` button toggled and I want to change the value of the `RESOLUTION` field then refresh the page, it doesn't keep the change and doesn't update it.

It should update the shot when the field changes (or even better debounce the input so only one update is performed in the database after the user finishes typing multiple digits for frame start/end for example).

**Screenshots**

![image](https://github.com/user-attachments/assets/32f9842e-5cc8-4019-887e-bc886f3dbbe9)

**Desktop:**

 - OS: Windows
 - Browser: Firefox
 - Version: 132.0.2 (64 bits)

**Comment by NicoPennec** [comment]
Yes, it's available in Kitsu >= 0.20.0

Thank you for your crystal-clear bug report. It was very helpful!
