### ISSUE TITLE
Playlist Add Text Bug In Review Room

### ISSUE THREAD

**Issue by darkprince334455** [cgwire/kitsu#1599]
**Context**

Studio name: Monsta SDN BHD
Kitsu version: 0.19.73
Production type: TV Show

**Describe the bug**

Trying to type a text requires us to click the created text box multiple times due to typing one alphabet causing the text box to deselect. Only happens in Join Room Review

**How to replicate the issue**

Create a playlist with an image or video > Join Room Review > Use the add text feature on image or video > Type one alphabet 

**Desktop (please complete the following information):**

 - OS: [Windows 10 pro]
 - Browser [Chrome]
 - Version [131.0.6778.87 (Official Build) (64-bit)]

**Comment by NicoPennec** [comment]
Hi @darkprince334455
It will fixed on a next release.
I will keep you updated.

**Comment by NicoPennec** [comment]
Fix available on Kitsu >= 0.20.3
