### ISSUE TITLE
Changing projects clears out the episodes list. Selecting an episode says no shots present. Page refresh needed

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1609]
**Context**

Studio name: Ryff
Kitsu version: 0.20.1
Production type: 

While inside a project, selecting another project results in the Episodes list defaulting to a blank entry with the green animated logo in the page just spinning endlessly. 

Pulling down the episodes menu gives the correct list of episodes for that project, however selecting one results in a page saying "no shots present - how about creating some?". A page refresh is needed to display the shots.

**Comment by NicoPennec** [comment]
Thank you @PeteDraper 🙏 
Fixed on Kitsu >= v0.20.2
