### ISSUE TITLE
Playlist Scroller UI responsiveness Issue

### ISSUE THREAD

**Issue by darkprince334455** [cgwire/kitsu#1618]
**Context**

Studio name: Monsta SDN BHD
Kitsu version: 0.19.73
Production type: TV Show

**Describe the bug**

Inaccurate mouse detection box for up and down scroller in playlist add asset/shot. It only happens on the maximum screen. The first image is the mouse on the bottom right side scroller and no detection. The second image is the position that the mouse is detected

**Screenshots**

![image](https://github.com/user-attachments/assets/ceb13973-ee73-4222-9d03-f556afe13ae3)
![image](https://github.com/user-attachments/assets/90738676-77d1-4da0-bbff-8a3f820f7f90)

**Desktop (please complete the following information):**

- OS: [Windows 10 pro]
- Browser [Chrome]
- Version [131.0.6778.87 (Official Build) (64-bit)]

**Comment by NicoPennec** [comment]
Hi @darkprince334455,
Thanks for the report.
The issue has already been fixed on Kitsu >= 0.20
