### ISSUE TITLE
Switching episodes in Task view doesn't section off Sequences (page refresh needed)

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1619]
**Context**

Studio name: Ryff
Kitsu version: 0.20.2
Production type: TV Show

Changing from one episode in the same project to another causes the 2nd episode's shot list to be all bunched together, irrespective of sequence name - they aren't sectioned off by Sequence. A page refresh is needed.

**Comment by NicoPennec** [comment]
Thanks @PeteDraper 🙏 

Fix available on Kitsu >= 0.20.4
