### ISSUE TITLE
Can't edit past timesheets at all anymore

### ISSUE THREAD

**Issue by MaximeGrosmaire** [cgwire/kitsu#1622]
**Context**

Studio name: Upsurge Studios
Kitsu version: checked 0.20.2 and 0.20.5
Production type: 

**Describe the bug**

We can't edit past timesheets at all anymore. 

I've checked with 'Lock artist timesheets older than 1 week' option toggled on and off and get the same behavior.

**Screenshots**

Screenshot from December 18th, artists and managers can't open any past timesheets.
![image](https://github.com/user-attachments/assets/8c46795c-a7ba-42df-adbe-fdacae3f5d05)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Firefox
 - Version: Firefox 133.0

**Comment by NicoPennec** [comment]
Thanks @MaximeGrosmaire 🙏 

Issue fixed on Kitsu >= 0.20.6
