### ISSUE TITLE
Deleted shot still visible in "Create Shots" Shots section

### ISSUE THREAD

**Issue by johhnry** [cgwire/kitsu#1627]
**Context**

Studio name: Welcome To Love
Kitsu version: 0.19.65
Production type: Short

**Describe the bug**

I have the following shots: `SH01`, `SH02`, `SH03`. If I click on the `+ Create Shots` button I can see the current shots in the `Shots` section (after clicking on the sequence).

Now if I delete a shot, for example `SH03`, then it's still visible in the `Shots` section.

**Screenshots**

![Screenshot_11](https://github.com/user-attachments/assets/c037c3bf-c279-465a-9568-8b5c0e026f14)

**Steps to reproduce**

1. Open the `+ Create Shots` popup
2. See that you have all the shots when clicking on a sequence
3. Completely remove a shot
4. Re open the create shots popup again and see that the list didn't changed

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Firefox
 - Version: 133.0.3

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu >= 0.20.9

Thank you for the report 🙏

**Comment by johhnry** [comment]
My bad thanks, I'll update!

**Comment by johhnry** [comment]
@NicoPennec I just tested it on `0.20.8` and it still doesn't work can you test on your side?
