### ISSUE TITLE
Cannot Create or add extra entries to List of Values or Checkbox custom metadata types

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#1628]
**Context**

Studio name: Ryff
Kitsu version: 0.20.8
Production type: Tv show / Films

While we can choose from the existing set of values of previously created field & checklist custom metadata types, editing existing ones to add new values or creating new fields doesn't add them to the custom field.

**Comment by NicoPennec** [comment]
Issue fixed on Kitsu >= 0.20.9

Thank you for the report 🙏
