### ISSUE TITLE
Error when deleting a user who was previously assigned

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#163]
Error when deleting a user who was previously assigned, and then removed of a task

![image](https://user-images.githubusercontent.com/42962633/48794663-ef907100-ecfa-11e8-953c-6a29392f3422.png)

**Comment by frankrousseau** [comment]
Do you still experience this issue?

**Comment by frankrousseau** [comment]
I think it's related to notifications and search filters. I have to dig in this.

**Comment by gwendupre** [comment]
Once the artist is not assigned anymore, and remove of the team, we can delete it! thx!
