### ISSUE TITLE
Unable to add new Tags in the Shots Page

### ISSUE THREAD

**Issue by makermatic** [cgwire/kitsu#1633]
**Context**

Studio name: PP
Kitsu version: 0.20.5
Production type: Feature Film

**Describe the bug**

When you edit a tag column and try to add new tags. the new tags don't populate onto the list. When I hit the confirm button, I don't see them too

**Screenshots**
![Recording 2024-12-20 at 14 12 33](https://github.com/user-attachments/assets/293fe38f-8420-4dc3-8e42-848130b0edb5)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser Edge
 - Version 24

**Comment by NicoPennec** [comment]
Hi @makermatic 
This issue has already been fixed in Kitsu >= 0.20.9
Thanks for reporting it to us 😉

**Comment by makermatic** [comment]
Oops my b, thanks so much @NicoPennec !
