### ISSUE TITLE
Unable to select uploaded 3d background on uploaded revision

### ISSUE THREAD

**Issue by darkprince334455** [cgwire/kitsu#1635]
**Context**

Studio name: Monsta SDN BHD
Kitsu version: 0.20.10
Production type: TV Show

**Describe the bug**

Uploaded HDR cant be seen or selected in revision even though multiple HDR has been uploaded and inserted in production 3d background

**Screenshots**

![image](https://github.com/user-attachments/assets/ff7d3b08-481b-416d-be83-0286b2e31d04)
![image](https://github.com/user-attachments/assets/20dfde44-372a-4a0d-9251-918e5d9fb6f9)

**Desktop (please complete the following information):**

- OS: [Windows 10 pro]
- Browser [Chrome]
- Version [131.0.6778.87 (Official Build) (64-bit)]

**Comment by NicoPennec** [comment]
HI @darkprince334455 
I can find an issue on Kitsu 0.20.x (a patch is coming), but not on Kitsu 0.19.77.
Are you sure about the version?

**Comment by darkprince334455** [comment]
> HI @darkprince334455 I can find an issue on Kitsu 0.20.x (a patch is coming), but not on Kitsu 0.19.77. Are you sure about the version?

Sorry, I misstated the version. The actual version is 0.20.10

**Comment by NicoPennec** [comment]
Fixed on Kitsu v0.20.11
