### ISSUE TITLE
Production Setting is incorrect

### ISSUE THREAD

**Issue by darkprince334455** [cgwire/kitsu#1639]
Context

Studio name: Monsta SDN BHD
Kitsu version: 0.20.10
Production type: TV Show

Describe the bug

The production setting's Start Date and End Date automatically show the current (Today) date. When the details were change, saved then refresh it still shows today's date.

Screenshots
![image](https://github.com/user-attachments/assets/b1675247-4d8f-4cb4-a4ac-583ba004f9f0)

Desktop (please complete the following information):

- OS: [Windows 10 pro]
- Browser [Chrome]
- Version [131.0.6778.87 (Official Build) (64-bit)]

**Comment by NicoPennec** [comment]
Thanks @darkprince334455
I'm checking this issue.

**Comment by NicoPennec** [comment]
Fixed on Kitsu v0.20.11
