### ISSUE TITLE
Filter disappears when going on a task page @Cube

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#166]
When going form the asset list, with saved filters, to a detail asset page, or a task page, then use the "back to list" button, the saved filters disappear, and the search bar is empty on the asset list page

**Comment by gwendupre** [comment]
Do you still experience this issue?

**Comment by gwendupre** [comment]
the filter is still disappearing

**Comment by frankrousseau** [comment]
Can you try again?
