### ISSUE TITLE
Show date with comment

### ISSUE THREAD

**Issue by CeliaCsn** [cgwire/kitsu#169]
Hello there !

Would it be possible to put after the comment the publish date instead of how many days ago it was publish ? This would be more precise for us, and would prevent some mistakes.

Thanks a lot !
![capture](https://user-images.githubusercontent.com/44972777/49727878-9bc9d580-fc71-11e8-9f8b-1de6cdbdacf4.JPG)

**Comment by gwendupre** [comment]
Yes! We will do and release this modification during the week.

**Comment by frankrousseau** [comment]
We fixed that in our latest release. Do you still experience the problem?

**Comment by CeliaCsn** [comment]
It's perfect, thanks a lot !

**Comment by frankrousseau** [comment]
Great!
