### ISSUE TITLE
Can't delete a shot

### ISSUE THREAD

**Issue by g-LuL** [cgwire/kitsu#173]
When trying to delete a shot, firefox raise an error 500. This happens since kitsu 0.8.31-build.
Log is attached to this issue.
[gunicorn_error.log](https://github.com/cgwire/kitsu/files/2702035/gunicorn_error.log)

**Comment by frankrousseau** [comment]
Thank you @g-LuL for reporting! We'll probably fix that next week.

**Comment by frankrousseau** [comment]
I was able to fix it easily. Can you update Kitsu and try again?

**Comment by g-LuL** [comment]
Working ! Thanks
