### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by Narendhar5622** [cgwire/kitsu#178]
Whatever changes i made its not reflecting in front end. is their any solution...

**Comment by frankrousseau** [comment]
Hello @Narendhar5622, 

Thank you for your interest in Kitsu. I suggest that first you refer to the development guide. If you face any issues, please post a detailed scenario of what is happening and include error message to your post. 

https://kitsu.cg-wire.com/development-environment/

**Comment by frankrousseau** [comment]
Can I close this issue?

**Comment by Narendhar5622** [comment]
yeah please....
