### ISSUE TITLE
ffmepg 

### ISSUE THREAD

**Issue by sanghwarhee** [cgwire/kitsu#179]
hi~
I found that kitsu only allow ffmpeg encoded mov files as previews uploads.
however normally vfx artists use quicktime codecs.

**Comment by frankrousseau** [comment]
Hello @sanghwarhee,

Thank you for reporting. Can you provide a sample file so we can study the problem?

**Comment by sanghwarhee** [comment]
Hi Frank!
I just found that it was about the size of the file more than 1 mega byte
file with less than 1 mega byte was ok.
Iam sending you the file anyway
all the best~

2019년 1월 9일 (수) 오후 7:15, Frank Rousseau <notifications@github.com>님이 작성:

**Comment by frankrousseau** [comment]
You can change the Nginx configuration. Make sure it allows bigger files. You will be able to upload bigger videos

**Comment by sanghwarhee** [comment]
Yes I added 'client_max_body_size 100M;' and everthing was ok!!
Thanks!!

**Comment by frankrousseau** [comment]
Awesome! You're welcome!

**Comment by sanghwarhee** [comment]
I have a question if you don't mind.
When I upload a clip, Kitsu convert it to mp4 file with ffmpeg right?
Does kitsu throw it away original clip? or it is somewhere in database?

**Comment by frankrousseau** [comment]
The original file is thrown away.
