### ISSUE TITLE
Departments

### ISSUE THREAD

**Issue by Narendarvfx** [cgwire/kitsu#185]
How to enable Departments section in kitsu?

**Comment by frankrousseau** [comment]
Hello @Narendarvfx,

There is no department section in Kitsu. It's something that requires development. I can add it to the feature request list if you want.

**Comment by Narendarvfx** [comment]
ok sure...
and i deployed kitsu in ubuntu and when iam browsing from windows, its getting login error login credentials failure.

**Comment by frankrousseau** [comment]
It's probably because there is an issue with the database. Can you check the error log file?

**Comment by Narendarvfx** [comment]
ok the issue was fixed.,,
but where to configure email to figure out the forgot password

**Comment by frankrousseau** [comment]
You must set environment variable listed there: https://zou.cg-wire.com/configuration/#emails

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/people/p/allow-to-group-users-by-department
