### ISSUE TITLE
Editing multiline Description of shots and assets is problematic

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#186]
When writing a description on the multiline widget made for it, typing enter or shift+enter creates the new line but also save/send the form and close the edition window. So you have to reopen it to continue the next line.

**Comment by gwendupre** [comment]
Thanks for the report, it's a bug, we are looking into it, sorry about that.

**Comment by frankrousseau** [comment]
@flablog It was fixed in the last release. Can you confirm?

**Comment by flablog** [comment]
Indeed ! Thanks !
