### ISSUE TITLE
Total Hours

### ISSUE THREAD

**Issue by Narendarvfx** [cgwire/kitsu#187]
How to get total hours for a particular shots....

**Comment by frankrousseau** [comment]
Hello @Narendarvfx 

What do mean by total hours ? Do you mean total hour spents by CG artists working on this shot?

**Comment by Narendarvfx** [comment]
Yeah total hours for particular shot done by assigned CG artists..

**Comment by frankrousseau** [comment]
You cannot see it through the interface. You must rely on the Python client to fetch it. There the time-spents route that returns all the time recorded for a given task:

```python
time_spents = gazu.cilent.fetch_all("time-spents?task_id=%s" task["id"])
total = 0
for time_spent in time_spents:
     total += time_spent.duration
```

**Comment by frankrousseau** [comment]
Total hours is now available on the asset and shot pages. Is it what you expected?
