### ISSUE TITLE
search automatically save filter

### ISSUE THREAD

**Issue by CeliaCsn** [cgwire/kitsu#190]
Hello !

Had some trouble recently, every time we're looking for something, CGWire automatically save it as filter.
An to erase them, you have to clic twice on the symbol, which will fisrt lead you to the filter instead of delated it.

Thanks !
![capture](https://user-images.githubusercontent.com/44972777/52423636-c9f45600-2af8-11e9-812c-85ef5960c73f.JPG)

**Comment by frankrousseau** [comment]
Thank you @CeliaCsn for reporting. We'll fix this very soon.

**Comment by frankrousseau** [comment]
Hello @CeliaCsn, I can't reproduce the bug. Can you tell us what is your navigator?

**Comment by CeliaCsn** [comment]
hello @frankrousseau I'm using Firefox 65.0
Thanks !

**Comment by frankrousseau** [comment]
Can you try with Chrome and tell me if the problem still happens (NB: I'm not telling you to use Chrome for Kitsu, I'm just trying to understand what is happening)?

**Comment by CeliaCsn** [comment]
heyyy @frankrousseau 
I think I found the problem. I press enter after typing my search, so it saves it. If I only type, and do not press enter, everything is fine. Sorry about that !

**Comment by frankrousseau** [comment]
Great! It's the expected behavior!
