### ISSUE TITLE
Nothing happens when creating a new task status [cube]

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#194]
When we try to create a new status, nothing happens when we click on the "confirm" button.

![image](https://user-images.githubusercontent.com/42962633/52701972-9f345280-2f7b-11e9-8992-0cf1fe36f912.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again ?

**Comment by gwendupre** [comment]
It's working! thx
