### ISSUE TITLE
Removing Playlist confirmation hangs after deleting last existing playlist

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#197]
### Issue

When trying to remove a *Playlist* it will show the following confirmation:

![delete_01](https://user-images.githubusercontent.com/2439881/52788173-6fab4600-3060-11e9-8b30-05c6a2b9cc60.png)

When clicking confirm it deletes the playlist but the pop-up remains open, then showing:

![delete_02](https://user-images.githubusercontent.com/2439881/52788189-7b970800-3060-11e9-8978-de4b50e3bb6b.png)

> Are you sure you want to remove **Please select a playlist on the left.** from your database?

It seems it gets stuck on a "No playlist selected" kind of status. This will only happen when there's only one playlist and you are removing this last existing one. When another remains (there was more than one playlist) then it works as expected.

Whenever it's in this stage the *Cancel* button of the Window doesn't work. It just remains open. Pressing *Confirm* in this broken state gives: "An error occured while deleting this playlist."

_Tested in both Firefox and Chrome - both have the issue._

### To Reproduce

1. In a project with no playlists, create one playlist.
2. Select the playlist and delete it.

Note: Refreshing the page fixes it because it reopens the page without the pop-up.

**Comment by frankrousseau** [comment]
Ok thank you for reporting, we'll fix that next week.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by BigRoy** [comment]
Yes, seems to work as expected now with: https://github.com/cgwire/kitsu/pull/200
