### ISSUE TITLE
Uploading .m4v video attachment fails to play video and breaks comment submission

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#198]
### Issue

When uploading a .m4v video file the upload starts and then ends up responding with `$t('comments.error')` below the comment block.

The posted comment and video don't show. However, when refreshing the page the comment does show yet the video file does not work. Going to History shows the new "revision" of the attachment, again with a video that does not play. Trying to download the video there gives an `.mp4` which also doesn't work.

_Artist was working in Chrome, not sure if related._

### Proposal

When the video conversion fails or comment submission fails it should not post the comment and video in this broken state. Basically it should remain on the same page, keep the message that you typed and tell you why it failed so you can fix it without your message disappearing. 

Also the `$t('comments.error')` should actually be a valid readable response value. :)

**Comment by BigRoy** [comment]
Note: The `.m4v` doesn't show by default under valid extensions when browsing - the Artist stated he just changed the filter to "All files". So I guess Kitsu knows it likely can't handle the `.m4v` but this is how he managed to upload it.

**Comment by frankrousseau** [comment]
Thank you for reporting, we will handle that next week.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by BigRoy** [comment]
Yes, seems to be fixed with:

- https://github.com/cgwire/kitsu/pull/200
- https://github.com/cgwire/zou/pull/132
