### ISSUE TITLE
Switching project when on Playlist view doesn't update page

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#202]
### Issue

When you are in the Playlist page of a Project and you use the top left project drop-down to switch to another project the page does not refresh. The URL does seem to change, but it doesn't show the playlists of the other project.

- Refreshing the page (like pressing F5) does load the correct page.
- Switching pages in other views than Playlist do seem to work as expected. I'm only seeing this behavior with the Playlists page.

It's a bit confusing that it looks like it switches/updates (since the URL changes) but the displayed content remains the same.

_Tested in both Firefox and Chrome on Windows_

**Comment by gwendupre** [comment]
It should be fixed now, can you confirm it's good now?

**Comment by BigRoy** [comment]
Seems to be fixed, I think through this PR https://github.com/cgwire/kitsu/pull/211 with this commit https://github.com/cgwire/kitsu/pull/211/commits/0f3afd463fb807d381a570d1984302400fba4c16
