### ISSUE TITLE
Search filter for assets on Breakdown page does nothing

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#204]
### Issue

When on the **Breakdown view** for a Project the right hand side shows "All Available Assets" with a search field underneath. It seems however typing something there does not filter or change anything.

_Tested in both Firefox and Chrome on Windows._

**Comment by gwendupre** [comment]
The filter is now activated on the breakdown page, can you confirm it's working?

**Comment by BigRoy** [comment]
Yes, working as expected!

Should be fixed with this PR https://github.com/cgwire/kitsu/pull/211 and this commit https://github.com/cgwire/kitsu/pull/211/commits/e5d22032fc6fb6b746ac28b80c78c666c30471f3
