### ISSUE TITLE
Playlist deletion isn't possible when shots assigned to it got deleted

### ISSUE THREAD

**Issue by jdrese** [cgwire/kitsu#205]
# Issue

If you create a playlist and assign shots to it and later on those shots get delete it you can't delete the playlist later on. The ui won't show you the delete button anymore

# steps to reproduce

1. create a shot
2. create a playlist
3. assign the shot to the playlist
4. delete the show
5. try to delete the playlist

**Comment by frankrousseau** [comment]
Thank you @jdrese for reporting!

**Comment by gwendupre** [comment]
If a shot assigned on a playlist is deleted, the playlist can't be read anymore.
![image](https://user-images.githubusercontent.com/42962633/53444620-f40da980-3a0e-11e9-9a2c-e56cc7bc3f9f.png)

**Comment by gwendupre** [comment]
it should be fixed now, can you confirm it's working properly?

**Comment by jdrese** [comment]
Hello @gwendupre 

I will try this tomorrow and will let you know.

**Comment by jdrese** [comment]
This seems to work now. Many thanks.

**Comment by frankrousseau** [comment]
Thx @jdrese !
