### ISSUE TITLE
Artist Cannot Change Status

### ISSUE THREAD

**Issue by swamiforlife** [cgwire/kitsu#208]
I have just built a ubuntu server 18 vm with Kitsu. 
Everything seems to be working fine but,
Artists cannot change the Status of Tasks assigned to them.  The drop down menu with the status options wont  drop down to show any options. It is just static on clicking it. 
If i make the user a supervisor then they can make the status changes. 
The custom action drop down is also not working. 
What could be the reason?

**Comment by frankrousseau** [comment]
Hello @swamiforlife,

  It's a bug we introduced in a recent release of Kitsu (0.9.22). It's fixed in the last release (0.9.23). Can you upgrade Kitsu (the frontend part) and try again?

**Comment by frankrousseau** [comment]
Btw, we have a Slack too where you can meet CG Professionals : https://slack.cg-wire.com

**Comment by swamiforlife** [comment]
Ok it works now. 
Thanks

**Comment by frankrousseau** [comment]
You're welcome!
