### ISSUE TITLE
Cannot Upload video attachments

### ISSUE THREAD

**Issue by swamiforlife** [cgwire/kitsu#210]
Every time i try to upload .mov files in a comment. I get the below error
An error occured while posting comment

After that i refresh the page and i see the comment that i wrote but the Video preview is blank. 
When i click download i get an error saying the below 
{"error": true, "message": "File not found for: previews 3840fe89-2111-408c-b8e3-0e63ef9050ab"}

IT seems that the file is not uploading at all. I have tried files as small as 800kb to 10MB all are failing.
Photos like jpg files are uploading correctly. 
What could be the problem?

**Comment by frankrousseau** [comment]
Ok. I have two questions:

* What is the version of ffmpg on the server? It must be version 4.
* Are you sure that your Nginx configuration is correct ?

**Comment by swamiforlife** [comment]
Sorry it was my mistake,
I did not install FFmpeg in the server. I missed that step in the instructions. 
I have installed it and now i can upload videos and everything is working normally. 
Thanks

**Comment by frankrousseau** [comment]
You're welcome. It was missing in the documentation. I figured it out yesterday and fixed it in the documentation.
