### ISSUE TITLE
Switching project when on asset/shot page shift the column display

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#212]
When you are in the asset or shot page of a Project without a custom column and you use the top left project drop-down to switch to another project with a custom column, the display of all the columns is shifted

* Refreshing the page (like pressing F5) loads the correct page.

![image](https://user-images.githubusercontent.com/42962633/53508567-45bf3e00-3aba-11e9-91bf-d9c9a44eacf4.png)

**Comment by frankrousseau** [comment]
I think that this bug is fixed. Can you try it again?
