### ISSUE TITLE
Discrepancy of display on the deleted item

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#213]
Sometimes the asset or shots are immediately deleted, and can't be reloaded.
Sometimes the entities are crossed and stay at her position, but some other times they are sent to the end of the list.
I can't reproduce it for now.

**Comment by frankrousseau** [comment]
I think shots are directly deleted when there are no task linked to it. Can you confirm?

**Comment by gwendupre** [comment]
Indeed, when not related to a task the entity is directly deleted.

**Comment by frankrousseau** [comment]
Can we close this one?

**Comment by gwendupre** [comment]
Yes
