### ISSUE TITLE
Breakdown view Sequence list breaks when moving between views when Shot was selected

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#216]
### Issue

An interesting issue I'm seeing is that whenever you go into a project and go to Breakdown everything is fine. However, when you select a Shot on left-hand side, then go to another view (like Assets) and back to Breakdown then the Sequence list is totally empty.

To reproduce:

1. Go in Project to Breakdown View
2. Select a Shot on left hand side.
3. Go to Asset view (or any other view)
4. Go back to Breakdown view.

_OR_

1. Go in Project to Breakdown View.
2. Select a Shot on left hand side.
3. Switch to another Project.

The issue _only happens_ whenever you leave the Breakdown view with a Shot selected. So whenever you go back to Breakdown view, by default it deselects your current shot selection. So switching to Asset view again (without reselecting a Shot) and then going back to Breakdown view another time it fixes it.

Here's an image of the empty Sequence list:

![empty_sequence_list](https://user-images.githubusercontent.com/2439881/53954679-34d48500-40d7-11e9-8d5c-a6d11651e3bb.png)

---

_Tested in Firefox_

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll have a look at it for the next release.

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll have a look at it for the next release.

**Comment by frankrousseau** [comment]
It's hard to reproduce. I was only able to reproduce it one time. Do you have any idea about how to reproduce it more consistently

**Comment by BigRoy** [comment]
> It's hard to reproduce. I was only able to reproduce it one time.

Interesting, for me the steps to reproduce as described in the issue reproduces it _every time_. You **must** select a Shot under _Shots_ on the left hand side in the Breakdown view for the issue to happen. So select a Shot, do the switch as described (either by switching Project, or switching to another view and back to Breakdown)

Just tested it in Chrome too, same issue.

**Comment by frankrousseau** [comment]
It should be fixed. Can you confirm?

**Comment by BigRoy** [comment]
Can't seem to reproduce it anymore with the steps set out in the issue. As such, this seems fixed.
