### ISSUE TITLE
The preview for studio logo is broken after uploading a new icon

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#225]
On the settings page, when you upload a new company logo, the logo appears as broken (even if the uploading worked). 
The preview for the studio logo is properly displayed after refreshing the page.

NB: In the sidebar, the logo is properly changed.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
