### ISSUE TITLE
Hide additional information hide also minimize task type columns

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#227]
When you are on a global page (asset or shot), with a minimized task type column, if you click on the  "hide additional information" button, it will hide them, but also the minimized task type column.

The issue also appears when you already hide the additional information and want to minimize a task type column. The minimized task type column will disappear.

A refresh of the page with F5, will display the missing column maximized.

**Comment by frankrousseau** [comment]
It should be fixed. A minimized column is still hidden after refreshing the page.

**Comment by gwendupre** [comment]
Thanks
