### ISSUE TITLE
Delete a comment with a status doesn't bring back the previous status on a history page of a shot [CUBE]

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#229]
When a comment with status is deleted (for example shot 214), the deleted status is still displayed, instead of the previous one.
The actual status is WFA, but the last comment displayed is linked to a validated status.

On the shot pages, a script fills the status.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed! thanks
