### ISSUE TITLE
Error while deleting a shot [ENI]

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#230]
In the project **Animaux**, in the global shot page, an error message appears when I want to delete the shot **plan02cacamou**: An error occurred while deleting this shot. There are probably data linked to it. Are you sure this shot has no task linked to it?

But when I click on confirm, it works, the shot appears as strikethrough.

All the comments have been deleted. But deleting the tasks "Storyboard", "Layout" or "Animation" is impossible. The loading wheel on the action menu keeps running until I refresh the page, and the task is not deleted. The problem appears with the 3 tasks at the time and one by one.

![image](https://user-images.githubusercontent.com/42962633/56585706-a82a4b80-65de-11e9-8087-0fb397230079.png)

The other tasks of this shot were deleted without issue.

Now that the shot is strikethrough, the same error message is displayed, when I tried to delete it for good.

![image](https://user-images.githubusercontent.com/42962633/56585864-eaec2380-65de-11e9-8215-d41e4a9c0233.png)

The same situation appears as a CG Artist, and as a Studio Manager.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
