### ISSUE TITLE
Custom Task Names

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#233]
**Goal**

To enable an arbitrary amount of tasks with a specific task type.

**Motivation**

Currently you can only have task types where you also define the name of the task, but productions often require multiple tasks of the same task type.

For example rigging a character can be split into an animation rig and muscle simulation rig. Both tasks are under the Rigging task type umbrella, but they might be assigned to two different people.
In this example you would make a task called "animation" and "simulation" with the task type of "Rigging".

**Comment by tokejepsen** [comment]
Another example is to split the body and face into separate rigs. So you would end up with three tasks; "body", "face" and "main", where the "main" task combines the body and face rig.

**Comment by frankrousseau** [comment]
Thank you for the suggestion. It's a tough question because it implies a UX overhead which doesn't fit with the Kitsu philosophy (simplicity over exhaustivity). Nevertheless, we'll think about solving your use case.

**Comment by tokejepsen** [comment]
Thanks @frankrousseau.

Just some more use cases. Compositing can often get split into different tasks as well. For example a task for greenscreen keying and another for live action plate integration.

**Comment by cuckon** [comment]
+1, we need this feature as well. It's not unusual actually, like lod variants of modeling tasks, deferent phases of layout tasks.

**Comment by frankrousseau** [comment]
The thing is that it's more a problematic related to asset management. On the production point of view, it leads to a complexity that can create more trouble than solving problems. We still don't have figured out how to solve this easily.

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/task-tables/p/custom-task-names
