### ISSUE TITLE
Wrong url in reset password email.

### ISSUE THREAD

**Issue by g-LuL** [cgwire/kitsu#235]
When user forget his password, he can reset it. An email is sent with a link but this link has the wrong url.  
The url in the email points to http://localhost:8080 :(

**Comment by frankrousseau** [comment]
Hello @g-LuL, thank you for your report. Did you set the `DOMAIN_NAME` environment variable?

https://zou.cg-wire.com/configuration/#emails

**Comment by g-LuL** [comment]
We've add this DOMAIN_NAME var, and it worked.
Howerver, our domain is not under ssl/https so the link is still false. Is the https needed ?

**Comment by frankrousseau** [comment]
Yes it's very important for the security of your data and for your pictures. With http, it's easy to steal passwords. You can have free certificate via let's encrypt now.

**Comment by g-LuL** [comment]
Yes I understand, in our case, the kitsu instance is only in our local network for the moment.  
Anyway, we planned to switch it to https soon.  
Thanks for your answer :)

**Comment by frankrousseau** [comment]
I think you can contribute by proposing adding a environment variable for the protocol and change the email with that variable.
