### ISSUE TITLE
Tagging in comment fails when submitting comment without typing anything after tag

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#240]
### Issue

Whenever tagging someone with `@Username` and you click Enter to autocomplete it to the user and then you submit your comment then the tag would fail to get processed correctly, somehow the person's name is dropped and you only see the part of the name in the resulting comment that you typed prior to the enter of autocompleting.

Pressing `<Space>` or `.` or anything else after the tag makes it however succeed. It *also!* succeeds if you move the beginning of the line and type something else.

It seems that it requires just one extra "text changed" signal after the tag completion to correctly work with the comment. However, when I would type out the entire name correctly and then click to autocomplete then suddenly it works. It's as if the autocomplete result actually isn't applied to the resulting comment whatsoever until another thing is typed.

_Tested on Windows + Firefox, not sure if related_

**Comment by frankrousseau** [comment]
I was able to reproduce. Thx for reporting!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by BigRoy** [comment]
Seems fixed with this PR, but couldn't find the related code changes/commits that should fix something like this: https://github.com/cgwire/kitsu/pull/241

**Comment by frankrousseau** [comment]
The commit you were looking for is this one: https://github.com/cgwire/kitsu/pull/241/commits/edadbb049c3639fb3dfbbbd431636b9f257bbdc1
