### ISSUE TITLE
Quickly find Shots or Assets by last edited/commented

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#244]
### Issue

Artists in our studio have requested the ability to "sort by last comment/edit" in the Asset/Shots view. I've referred them to the News Feed to get details on the Latest Comments in the project, but they stated that it's quite a bit slower to read that page (because you need to read the full names, etc.) as opposed to the table view getting sorted.

As such, I wanted to open up this issue to discuss how things could be improved for an Artist to quickly find out the shots with the latest changes. To accompany this I did a quick "discussion" through the News Feed page on how it could be visually improved.

Here's a screenshot of the current state.

![newsfeed_current](https://user-images.githubusercontent.com/2439881/59495576-dc5c1300-8e8f-11e9-9488-c4896ae7380c.jpg)

And here are some of the notes we made to improve the UX - of course very subjective.

![newsfeed_notes](https://user-images.githubusercontent.com/2439881/59495595-e7af3e80-8e8f-11e9-9232-168642699606.jpg)

---

Whether the fix is to improve the News Feed or to allow Sorting by "Latest Comment/Edit" in the Asset/Shots view is up for discussion.

**Comment by frankrousseau** [comment]
Thank you for opening this discussion. You can already sort shots by last comment in the detailed task view.

Thank you for the UX suggestion. We will look forward to implement them.

**Comment by BigRoy** [comment]
> You can already sort shots by last comment in the detailed task view.

Ah, this has been insufficient for the Artists though. Since Producers/Directors don't necessarily see all shots in the Task view. And sometimes an Artist wants to see the latest comments on work done by other Artists - just to see what they are up to.

**Comment by frankrousseau** [comment]
> Ah, this has been insufficient for the Artists though. Since Producers/Directors don't necessarily see all shots in the Task view. And sometimes an Artist wants to see the latest comments on work done by other Artists - just to see what they are up to.

I think it can be done via the task lists (when clicking on a column name). Is it enough for you?

**Comment by BigRoy** [comment]
> I think it can be done via the task lists (when clicking on a column name). Is it enough for you?

No, because the Tasks page shows only those tasks that you are assigned to. In this case, "And sometimes an Artist wants to see the latest comments on work done by other Artists - just to see what they are up to." - as such it would have to be Project-wide.

**Comment by frankrousseau** [comment]
What I mean by the task list is the list you access by clicking on a task type name which leads to the details of the task (assignees, number of retakes, etc.). This list can be filtered by assignee.

**Comment by frankrousseau** [comment]
Most of the improvements asked there werer performed. Feel free to open a ticket on Canny if you think that things are still missing.
