### ISSUE TITLE
Importing .csv

### ISSUE THREAD

**Issue by FrancoisMaree** [cgwire/kitsu#252]
When trying to import a .csv file with data, some of the fields doesn't come through. To make sure I got the same fields that Kitsu use, I filled in a couple of shot details and exported a .csv file of that. 
It contains entries for:
- Project
- Episode
- Sequence
- Name
- Description
- Time Spent
- Nb Frames (This seems to be the amount of frames for the shot)
- Frame In
- Frame Out

To test this I kept the file the same, but adjusted the entries, keeping the commas etc. Upon importing the modified file, most of the data gets imported except for Frames and FPS.
I noticed that FPS doesn't get exported (or imported) via csv. It's not show-stopping but it would be nice for the odd occasion that a shot needs to be done at a different frame rate than the rest of the show.

**Comment by frankrousseau** [comment]
Thank you for reporting @FrancoisMaree ! We'll have a look at that. It doesn't look like a big bug.

**Comment by frankrousseau** [comment]
https://github.com/cgwire/zou/pull/166

**Comment by FrancoisMaree** [comment]
Awesome! Working like a charm. Thanks for the fast response time!
