### ISSUE TITLE
TV Show Shot Creation

### ISSUE THREAD

**Issue by FrancoisMaree** [cgwire/kitsu#253]
If you have a Production defined as a TV show, the shot creation popup closes once you fill in an episode name and click on add. This means you have to open the popup again to assign a sequence and shot to the episode (in those cases clicking on add doesn't close the popup).

![image](https://user-images.githubusercontent.com/38096286/61112344-e885c100-a48b-11e9-86f1-d3aba72f81aa.png)

I forgot to mention, if you are on the shot list page, clicking on the big "Add shots" button at the bottom, nothing happens.
![image](https://user-images.githubusercontent.com/38096286/61112624-8e393000-a48c-11e9-965b-bc1cb45b193e.png)

**Comment by frankrousseau** [comment]
Thank you for reporting. It should be fixed in next release.

**Comment by frankrousseau** [comment]
https://github.com/cgwire/zou/pull/166

**Comment by FrancoisMaree** [comment]
I can confirm that is is working now. Thanks!
