### ISSUE TITLE
Shortcut for going to different Task/Asset annoying on desktop

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#257]
### Issue

It seems there's a shortcut set for `Ctrl + arrow key` that moves the selected task to something else. However, I tend to edit whatever I type quite often and going to the beginning of a word with `Ctrl + left key`... however doing that currently loses any text I typed as it would change the currently active task.

As such, for me the shortcut is slightly annoying. I was wondering, would there be a more fitting shortcut that didn't influence how one is used to editing text?

I see how it's a hard decision, since most options are used:
``` 
- Left/Right: change character
- Ctrl + Left/Right: change character by word
- Shift + Left/Right: select character
- Shift+ Ctrl + Left/Right: select character by word
- Alt + Left/Right: go back in history or forward in browser history
- Ctrl + Page Up/Page Down: move through Browser tabs
- Home/End: Move to beginning/end of line.
- Ctrl + Home/End: Move to start/end of document
```

Could we find another logical shortcut combination?

**Comment by frankrousseau** [comment]
Thank you for reporting. We don't have any idea yet about how to change that. Let's keep the discussion open.

**Comment by frankrousseau** [comment]
We decided to use the alt-key instead of the ctrl-key. It blocks the navigation history of the browser via these shortcuts.
