### ISSUE TITLE
Comment with markdown `text` in dark theme turns out very bright.

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#259]
### Issue

When you include a word surrounded by ` then it turns it into a code line, which in the Dark Theme turns out very bright. See:

![dark_theme_code_line](https://user-images.githubusercontent.com/2439881/61792992-53d17a80-ae1e-11e9-8d1e-05d411943037.png)

_Note: A code block seems more readable without the red text, but could also use some improvement_

### Reproduce

To reproduce, use dark theme and make comment:
```
This looks fine. This `part here is very bright!`
```

This is [_Markdown Formatting_](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

### Solution

It will likely work better with a darker background and lighter font color. So, light font on darker background for dark theme.

A bit messy, but here's a quick mockup:

![dark_theme_code_line_mockup](https://user-images.githubusercontent.com/2439881/61793353-3e108500-ae1f-11e9-8b50-2debe58bd7b1.jpg)

_This isn't intended as a perfect design, but just shows how it could be easier to the eye. I'd recommend **not** copying this one-to-one._

**Comment by frankrousseau** [comment]
Thank you for the suggestion! We'll see what we can do for this.

**Comment by BigRoy** [comment]
Similar issue with Bold text `**bold**` in dark theme. It turns out very dark making it hard to see, quite the opposite of what you'd want from something that's meant to be **bold**. :)

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by BigRoy** [comment]
![lovelycolors](https://user-images.githubusercontent.com/2439881/62470131-06e49100-b79a-11e9-91ac-b331a42060a5.png)

Looking better! 🥇
