### ISSUE TITLE
Columns/header position

### ISSUE THREAD

**Issue by g-LuL** [cgwire/kitsu#261]
When I switch from one project to another, if they don't have the same number of tasks, columns are not aligned to header anymore.  
The asset page has this issue almost at each switch, the shot page seems to have the issue too...

Tested on kitsu 0.10.13 (current docker image)

![Peek 2019-07-31 13-30](https://user-images.githubusercontent.com/6122546/62208810-2b0a3180-b398-11e9-9b3f-e4b63d2df4c2.gif)

**Comment by frankrousseau** [comment]
Thank you for reporting, we'll see if we can reproduce it.

**Comment by BigRoy** [comment]
@g-LuL I've tried to reproduce this but myself was unable to do so. However, could this maybe only happen when switching between projects that have "Episodes" and those that don't?

If you can reproduce it otherwise too. Could you share what OS + browser you are using?

**Comment by g-LuL** [comment]
Hey @BigRoy, i'm on linux kubuntu and firefox. It is important that projects don't have the same number of tasks/columns (custom properties may be responsible too)
I'll try to find exact tests to reproduce this tomorrow.

**Comment by frankrousseau** [comment]
@g-LuL, if you update your version. It should be fixed. Thank you again for reporting.
