### ISSUE TITLE
Timesheets display July 32

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#262]
On the /timesheets page, with default settings (monthly view, nothing else set), we can see a july 32 displayed :)
Might be only on july 31 ? We'll check tomorrow again

![july32](https://user-images.githubusercontent.com/870195/62223610-8b5b9c00-b3b5-11e9-9fca-176203a764b4.png)

**Comment by frankrousseau** [comment]
Ok, thank you for reporting!

**Comment by frankrousseau** [comment]
I can't reproduce this is issue...

**Comment by flablog** [comment]
It's happenning again, today on the 31 of August :)

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/870195/64061950-4360ac80-cbe1-11e9-88e9-e97259c35521.png">

**Comment by frankrousseau** [comment]
It should be fixed can you try again?
