### ISSUE TITLE
User can not connect to kitsu with Microsoft edge

### ISSUE THREAD

**Issue by anthonydns** [cgwire/kitsu#267]
On windows 10 Ms edge browser  is installed by default and by default Ms outlook open link (reset password link) on Microsoft Edge

It is possible to configure this on company computers but not on personal computers...

To inform the user to use another browser I add the following code to nginx config file `/etc/nginx/sites-enabled/zou`.

```
if ($http_user_agent ~* ".Edge.") {
  return 403 "Browser not supported. Please use Google Chrome.";
}
```

Restart nginx for apply.

This catch Edge browser and return 403 (is possible to add Internet explorer).

**Comment by frankrousseau** [comment]
Thank you for reporting and for the snippet! We'll think about a solution for this (maybe that adding your Nginx snippet to the doc is enough).

**Comment by frankrousseau** [comment]
Kitsu now stop working if the user is not using Chrome or Firefox. Is it enough for you?
Not sure when the bug occurs on Edge.
