### ISSUE TITLE
Mytask order by name is wrong

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#270]
In the MyTask page, ordering by name rather than priority orders the list by shot name when it should order it by sequence name and shot name.

So I've this kind of results : 

- S010 P001
- S002 P002
- S010 P003
- S001 P004

When I expect :

- S001 P004
- S002 P002
- S010 P001
- S010 P003

Cheers

**Comment by frankrousseau** [comment]
Thx for the report @flablog

**Comment by frankrousseau** [comment]
It should be fixed. Can you confirm?
