### ISSUE TITLE
Return to login page

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#273]
Very often we get "disconnected" from the page we are working on and get return to the` /login` page. But we are not disconnected. It was tricky to track this behaviour, but this is what I get.

Apparently in some cases when a comment is posted by someone, and someone's else Kitsu tries an update (within same project, and all levels of roles), there is an access error to the newly created comment, which leads to go back to` /login`

Still the comment is readable later of course...

In this screenshot I've pointed out the moment it happens on a simple GET request on a comment, which returns an Unauthorized 401
The request is on a simple 
`GET /api/data/comments/d944ed5a-1ad2-4104-8a3c-ce10da352499 HTTP/1.1`

```
HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.14.0 (Ubuntu)
Date: Wed, 21 Aug 2019 16:47:48 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 236
Connection: keep-alive
Vary: Cookie
```

`{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}`

![error_to_login](https://user-images.githubusercontent.com/870195/63455360-edf00700-c44c-11e9-9930-70a5e227fba9.jpg)

That issue happens to us dozens of times per day and per person... Because we generate a lot of comments (some are automatic from scripts -rendering for example-).

**Comment by flablog** [comment]
I didn't mention it, but it happens on many pages, without even being doing something at that time. It's purely on a background/live update

**Comment by frankrousseau** [comment]
Hello,

Thank you for the precise report.
I can't understand why you receive a 401 error. It should be a 403. Can you verify your Redis installation?

**Comment by flablog** [comment]
Ok, I'll have a look and let you know

**Comment by flablog** [comment]
So far, so good
no error in the redis-server log ( ` /var/log/redis/redis-server.log`)which looks like this
```
4691:M 22 Aug 2019 08:40:50.083 * 10 changes in 300 seconds. Saving...
4691:M 22 Aug 2019 08:40:50.084 * Background saving started by pid 28271
28271:C 22 Aug 2019 08:40:50.105 * DB saved on disk
28271:C 22 Aug 2019 08:40:50.106 * RDB: 0 MB of memory used by copy-on-write
4691:M 22 Aug 2019 08:40:50.185 * Background saving terminated with success
4691:M 22 Aug 2019 08:45:51.003 * 10 changes in 300 seconds. Saving...
4691:M 22 Aug 2019 08:45:51.005 * Background saving started by pid 28340
28340:C 22 Aug 2019 08:45:51.040 * DB saved on disk
```
while at least a user got a window back to /login
Should I look somewhere else ? 

On the gunicorn_error.log I have messages (but not sure they are related to the /login issue) and a lot of : 
```
[2019-08-22 08:47:51,990] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 102, in wrapper
    verify_jwt_in_request()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 34, in verify_jwt_in_request
    _load_user(jwt_data[config.identity_claim_key])
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 161, in _load_user
    user = user_loader(identity)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 189, in user_loader
    return jwt_manager._user_loader_callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/__init__.py", line 109, in add_permissions
    identity=Identity(user["id"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by frankrousseau** [comment]
I made a dirty fix. But it should work. Can you confirm?

**Comment by flablog** [comment]
Yes the hacks works ! Thankkks it's helpful already
