### ISSUE TITLE
Playlists : all pending is not adding last version

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#274]
In the playlist page, tu button "all pending" is adding all the WFA shots. But the versions automatically selected is the older/first one, and not the last one (which is more probably the one we are going to screen). So we have to go through every shot and select the last version.

Which leads to another issue : if there is many shots, we have to use the horizontal scroll to go to the end of the list. But changing a version here reset/reloads the page and the scrolls goes back to the beginning. So when dealing with a long list of shots to update to last version, it's pretty anoying behaviour.

**Comment by frankrousseau** [comment]
Ok, thank you for reporting.

**Comment by flablog** [comment]
Last update is avoiding the scroll reset. Thanks :)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
