### ISSUE TITLE
Slack Integration ping user on enable/disable

### ISSUE THREAD

**Issue by BigRoy** [cgwire/kitsu#283]
**Problem**

As an artist it's hard to figure out whether the connection with Slack worked out correctly, e.g. whether they typed there username the right way.

Now the only way to test whether it works is to wait for a new notification to come in.

**Solution**

How about sending a notification whenever the _Slack username_ or _Slack notification enabled_ state changes in the User's CG-Wire settings. 

That way, whenever the artist enables it they are supposed to directly see a notification, e.g. "You have succesfully connected your CG-Wire account with Slack".

**Comment by BigRoy** [comment]
This is also helpful for debugging, as currently we have someone with special characters in their *Display Name* on Slack, specifically the `ö` who seems to be unable to get any notifications and it's hard to identify where the problem originates from.

**Comment by frankrousseau** [comment]
That's right. Thank you for the suggestion.

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/casting/p/slack-integration-ping-user-on-enabledisable
