### ISSUE TITLE
CSV Import issue on Breakdown page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#284]
On gwen.cg-wire, for the "Caminandes" short production, in the breakdown page, the .csv file import does not work. There is an error message.

When exporting the .csv of the breakdown, it is not possible to upload it afterward, the error message is identical.

**Comment by frankrousseau** [comment]
It should be fixed. Can you confirm?

**Comment by gwendupre** [comment]
It's working now, thanks
