### ISSUE TITLE
Playlist select the oldest version of the shot even if there is a newer version [LeeFilm]

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#287]
When I create a playlist and add a whole sequence, fx sc0220. It automatically selects the oldest version of the shot, fx v1, even if there is a newer version v2 or v3. 
Now I have to go through each shot and check if there is a newer version.

**Comment by flablog** [comment]
Related to https://github.com/cgwire/kitsu/issues/274

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
