### ISSUE TITLE
Task deadlines

### ISSUE THREAD

**Issue by OxB03** [cgwire/kitsu#292]
Hi all.

So I have only recently really started digging into the code a bit, and was wondering:

We would like to be able to assign a due date / deadline on tasks. I can see these fields
in the database already, but don't really see it being used ? (Tasks.due_date)

I was thinking of maybe just adding a calendar picker on the top bar when you assign the task, and alternatively / also in the asset edit view

Is there any plans for due date, or is this being used by SG or similar ? 

thanks,

**Comment by frankrousseau** [comment]
Hello @OxB03,

Initially this field was used to import data from SG, but soon we will work on "Task Type schedule", where you will be able to set due dates to each task for the current task type and current production.

**Comment by OxB03** [comment]
That's great @frankrousseau 

We are in the process of trying to put together a pipeline using Kitsu, and that would be key.

Any rough idea on a time frame ?

**Comment by frankrousseau** [comment]
It will be shipped for mid-october if we don't face particular issues.

**Comment by frankrousseau** [comment]
(That's great news for your pipeline!)

**Comment by OxB03** [comment]
That is really great thanks @frankrousseau
