### ISSUE TITLE
Breakdown: 

### ISSUE THREAD

**Issue by OxB03** [cgwire/kitsu#294]
I see there has been a lot of changes on this recently :-)

Would sequences ever be available for assignment here ? 

We have script to assets, so we know which assets belong in what sequence, but we won't know the actual shot until later in the pipe.

What would be very useful is to already allocate assets to a sequence, and manage tasks from there, until after layout and cameras.

**Comment by frankrousseau** [comment]
Hello @OxB03,  

We don't develop specific features for free. If you want to order additional features, please contact our Sales team (sales@cg-wire.com).

What you can do alternatively is to create one shot by sequence and set the casting into it.

**Comment by OxB03** [comment]
I'm pretty sure we will be contacting sales in future, but probably for other stuff 

At the moment I am just trying to understand the Kitsu / Gitsu roadmap and where to focus our development

Thanks @frankrousseau, appreciate all the feedback / comments
