### ISSUE TITLE
Support for Chromium-based browsers

### ISSUE THREAD

**Issue by Arubinu** [cgwire/kitsu#297]
Hello,

I have a problem since adding the functionality showing if the browser is compatible or not with Kitsu.

In fact my browser is compatible, since it is based on Chromium, but is not Chrome itself.
So, would it be possible to add these to the list of browsers supported, not to have this message?

```
Your browser is not supported by Kitsu
Kitsu can only be used with Firefox and Chrome browsers.
```

Personally I use Vivaldi Browser, and here is his user agent:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36 Vivaldi/2.8.1664.43
```

It would be convenient to add a bypass, allowing the use of Kitsu, while being informed that it is potentially incompatible!

**Comment by frankrousseau** [comment]
Ok, thx @Arubinu for reporting!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
