### ISSUE TITLE
Breakdown not saving

### ISSUE THREAD

**Issue by OxB03** [cgwire/kitsu#299]
Hi all

My Breakdown view seems to lose all settings as soon as the shot or asset changes

- I choose a shot
- Link an asset
- Go to another shot
- Go back, first link is lost

In my log files I can see this:
`[2019-10-01 13:28:50,905] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/werkzeug/routing.py", line 1798, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2019-10-01 13:28:51,989] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/werkzeug/routing.py", line 1798, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
`
Any ideas ? Thanks :-)

**Comment by OxB03** [comment]
---
Access log if that helps ? 
---
`127.0.0.1 - - [01/Oct/2019:13:28:31 +0200] "GET //data/assets/b095bb26-35aa-451a-99af-4355b7f10fdc/cast-in HTTP/1.0" 200 3 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/assets/b095bb26-35aa-451a-99af-4355b7f10fdc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:28:43 +0200] "GET //data/episodes/d85ac78b-bb58-4081-a328-383f3798461a/sequences HTTP/1.0" 200 1075 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:28:43 +0200] "GET //data/shots/with-tasks?project_id=0d574898-e31e-4a26-af10-fabc3359246f&episode_id=d85ac78b-bb58-4081-a328-383f3798461a HTTP/1.0" 200 6817 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:28:43 +0200] "GET //data/projects/0d574898-e31e-4a26-af10-fabc3359246f/sequences/e8fd0758-9e30-481a-bbab-bd98a56c4f3f/casting HTTP/1.0" 404 163 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:28:43 +0200] "GET //data/assets/with-tasks?project_id=0d574898-e31e-4a26-af10-fabc3359246f&episode_id=d85ac78b-bb58-4081-a328-383f3798461a HTTP/1.0" 200 4479 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:28:50 +0200] "PUT //data/projects/0d574898-e31e-4a26-af10-fabc3359246f/entities/b5b39947-53a5-4c97-9b99-c2855340134f/casting HTTP/1.0" 500 1002 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown/sequences/e8fd0758-9e30-481a-bbab-bd98a56c4f3f" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:28:51 +0200] "PUT //data/projects/0d574898-e31e-4a26-af10-fabc3359246f/entities/b5b39947-53a5-4c97-9b99-c2855340134f/casting HTTP/1.0" 500 1002 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown/sequences/e8fd0758-9e30-481a-bbab-bd98a56c4f3f" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:29:03 +0200] "GET //data/projects/0d574898-e31e-4a26-af10-fabc3359246f/asset-types/e93b127e-a41f-4424-a780-86ced774240d/casting HTTP/1.0" 404 163 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown/sequences/e8fd0758-9e30-481a-bbab-bd98a56c4f3f" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:29:09 +0200] "GET //data/projects/0d574898-e31e-4a26-af10-fabc3359246f/sequences/662d1103-4daf-45bf-b97f-8e801d607e10/casting HTTP/1.0" 404 163 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown/asset-types/e93b127e-a41f-4424-a780-86ced774240d" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
127.0.0.1 - - [01/Oct/2019:13:29:10 +0200] "GET //data/projects/0d574898-e31e-4a26-af10-fabc3359246f/sequences/e8fd0758-9e30-481a-bbab-bd98a56c4f3f/casting HTTP/1.0" 404 163 "http://falling.duckdns.org/productions/0d574898-e31e-4a26-af10-fabc3359246f/episodes/d85ac78b-bb58-4081-a328-383f3798461a/breakdown/sequences/662d1103-4daf-45bf-b97f-8e801d607e10" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
`

**Comment by frankrousseau** [comment]
Hello, 

Are you sure that you use the latest versions ? Now all shots from a sequence are listed on the same page.

**Comment by OxB03** [comment]
Yes, I pulled last night

It's whenever you navigate away, it doesn't persist

Yes, all shots per sequence listed, but if I switch sequences and go back, the data is lost

**Comment by frankrousseau** [comment]
Did you update the Zou API too?

**Comment by OxB03** [comment]
I did not ...

I only updated the database and synced Kitsu

Thanks, let me have a look ...
