### ISSUE TITLE
Error on the count of asset when deleting them

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#302]
In the general asset page, when you delete an asset, the total at the bottom of the page drops by 2 (instead of 1).

When the total reaches 0, while there are still assets, in reality, the page displays that there are no assets to create and suggests to create one.

A refresh corrects this problem, but it is necessary to refresh each time an asset is deleted.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
perfect, it works! thanks
