### ISSUE TITLE
Task Schedule issue with "5 days estimation" & "1 day task" 

### ISSUE THREAD

**Issue by quentinricci** [cgwire/kitsu#307]
Hello, about the task schedule, 
When the estimation is put on "5 days", it's not possible to move or to adjust the schedule of your task only the first time. If you change to an other estimation, and you change it back after that, it will work.
Also, I could not find the way to set a 1 day task in the schedule, minimum of 2 days is required ?
Thanks!

**Comment by frankrousseau** [comment]
Hello @quentinricci,

We just published a fix for the task bar that you cannot move. About the 1 day task in the schedule, it's not something possible. We have to find a solution for this problem.

**Comment by frankrousseau** [comment]
Hello @quentinricci,

It should be fixed. Can you try again?
