### ISSUE TITLE
Production schedule issue with man-days

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#308]
On the planning page of a short film.
If you enter man-days for each type of task but then want to remove them to return to 0, everything is fine. 
But if we change pages (for example, go back to the asset page) and return to the planning page, the previously deleted man-days are displayed, and we have to remove them again.

The total man-days on top of the screen stay at 0.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks
