### ISSUE TITLE
Can not send email

### ISSUE THREAD

**Issue by xtvjxk123456** [cgwire/kitsu#311]
sorry for my bad english.
The problem:
1,already installed zou and kitsu
2, config email environment done. use online smtp server(smtp.163.com)
3, when send invitation got error:
`[2019-11-08 16:58:17,362] ERROR in __init__: Traceback (most recent call last): File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request() File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper resp = resource(*args, **kwargs) File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/views.py", line 89, in view return self.dispatch_request(*args, **kwargs) File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request resp = meth(*args, **kwargs) File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper return fn(*args, **kwargs) File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/blueprints/persons/resources.py", line 209, in get persons_service.invite_person(person_id) File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/services/persons_service.py", line 297, in invite_person emails.send_email(subject, body, person.email) File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/utils/emails.py", line 11, in send_email mail.send(message) File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_mail.py", line 491, in send with self.connect() as connection: File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_mail.py", line 144, in __enter__ self.host = self.configure_host() File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_mail.py", line 156, in configure_host host = smtplib.SMTP_SSL(self.mail.server, self.mail.port) File "/usr/lib/python3.6/smtplib.py", line 1031, in __init__ source_address) File "/usr/lib/python3.6/smtplib.py", line 251, in __init__ (code, msg) = self.connect(host, port) File "/usr/lib/python3.6/smtplib.py", line 336, in connect self.sock = self._get_socket(host, port, self.timeout) File "/usr/lib/python3.6/smtplib.py", line 1037, in _get_socket self.source_address) File "/opt/zou/zouenv/lib/python3.6/site-packages/gevent/socket.py", line 83, in create_connection addrs = list(getaddrinfo(host, port, 0, SOCK_STREAM)) File "/opt/zou/zouenv/lib/python3.6/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags) File "/opt/zou/zouenv/lib/python3.6/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo return self.pool.apply(_socket.getaddrinfo, args, kwargs) File "/opt/zou/zouenv/lib/python3.6/site-packages/gevent/pool.py", line 159, in apply return self.spawn(func, *args, **kwds).get() File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception File "/opt/zou/zouenv/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise raise value.with_traceback(tb) File "/opt/zou/zouenv/lib/python3.6/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) socket.gaierror: [Errno -2] Name or service not known
`
need for help for that.
thanks .

**Comment by xtvjxk123456** [comment]
nginx  setting:

`server {
    listen 80;
    server_name 192.168.10.21;

    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://localhost:5000/;
    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://localhost:5001;
    }

    location / {
        autoindex on;
        root  /opt/kitsu/dist;
        try_files $uri $uri/ /index.html;

    }
}`

**Comment by xtvjxk123456** [comment]
![image](https://user-images.githubusercontent.com/8720281/68471241-bed18080-0258-11ea-9835-9bf1e1aa0164.png)

environment.

**Comment by frankrousseau** [comment]
Do you know which technology use smtp.163.com ?

All new users can connect by using `default` as password. Kitsu will ask them to change their password on first connection.

**Comment by xtvjxk123456** [comment]
my bad,my system can not access internet when error accurred

**Comment by frankrousseau** [comment]
Ok great, enjoy using Kitsu!
