### ISSUE TITLE
Export CSV of shots does not include sequence name

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#313]
From the shot page, with or without filtered results, the downloaded csv does not include the sequence name, but just the shot name*. That makes the csv useless.

*At least on a "feature film" project.
Version of zou/kitsu updated last friday.

**Comment by frankrousseau** [comment]
Hello @flablog,

Thank you for reporting. Can you update your app again? We fixed that problem yesterday.

**Comment by flablog** [comment]
Oh sorry, I haven't seen the usual pull requests and didn't realize there was an update.
I will do as soon as I can stop for a few minutes the service !

**Comment by flablog** [comment]
Everything is good after update.
Sorry for not checking better before !

Cheers

**Comment by frankrousseau** [comment]
It's because we push hotfixes directly to go faster. Sorry for that.
