### ISSUE TITLE
Error with CSV import file, frame in and frame out column

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#318]
With A tv show production, when I try to create my episode, sequences, and shots with the frame in and frame out with a .csv file, I have an error due to the Frame In and Frame out column.

If I empty these two columns, I can import the file, but if Frame In and Frame Out are filled, there is an error message.

**Comment by frankrousseau** [comment]
Does the bug is still occuring?

**Comment by gwendupre** [comment]
I don't have an error anymore, but the frames in and frames out and the total frames don't appear.

**Comment by gwendupre** [comment]
It's fixed now, thanks
