### ISSUE TITLE
Episode deletion fails (Ui & API)

### ISSUE THREAD

**Issue by MrFrangipane** [cgwire/kitsu#327]
Hi,

Trying to delete an episode fails from the stats page (pressing the button does nothing)

![image](https://user-images.githubusercontent.com/5055938/69875437-6b81a980-12bd-11ea-873e-dad3c99dde67.png)

On the API side, it raises a `gazu.exception.MethodNotAllowedException: data/episodes/XXXXXXXXXX?force=true`

Thank you for your support !

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll fix that for the next release.

**Comment by MrFrangipane** [comment]
Thank you !
