### ISSUE TITLE
SHOT: frame_in / 'in' field with 0 doesn't display anything

### ISSUE THREAD

**Issue by Tilix4** [cgwire/kitsu#349]
On a shot, if you fill the frame_in / 'in' field with a 0, it doesn't display it. It behaves like nothing is filled.
The expected behavior is:
- If nothing is filled (frame_in is None) nothing is displayed.
- If 0 is filled, 0 should be dislayed.

**Comment by frankrousseau** [comment]
Thank you @Tilix4 for reporting

**Comment by gwendupre** [comment]
@Tilix4 It should be fixed now, can you confirm?

**Comment by Tilix4** [comment]
Hi @gwendupre, I've just updated Kitsu and it doesn't seem fixed.

**Comment by gwendupre** [comment]
Hi! What is your version of Kitsu?

**Comment by Tilix4** [comment]
How could I check that?

**Comment by gwendupre** [comment]
Click on your name/profile, at the bottom of the menu you will see the Kitsu's version.

![image](https://user-images.githubusercontent.com/42962633/74739824-effb1d00-5259-11ea-9851-c634abae4acf.png)

**Comment by Tilix4** [comment]
It's exactly the same as yours: 0.11.17

**Comment by gwendupre** [comment]
Weird!

In a shot if you enter 0 as a frame IN it doesn't appear on Kitsu?

![image](https://user-images.githubusercontent.com/42962633/74739949-351f4f00-525a-11ea-9aa7-86fb76c5105f.png)

**Comment by Tilix4** [comment]
Okay, it works setting to 0 again, when it have been already set, it's not displayed.
