### ISSUE TITLE
Edit a task type.

### ISSUE THREAD

**Issue by g-LuL** [cgwire/kitsu#36]
Hi,
When I try to edit a task type, the opened popup is for the production edition.

**Comment by frankrousseau** [comment]
Hello @g-LuL,  

Thank you for reporting, it will be fixed in next release.

**Comment by frankrousseau** [comment]
It's now fixed. Could you confirm @g-LuL?

**Comment by g-LuL** [comment]
I confirm it's fixed. Thanks @frankrousseau !

**Comment by frankrousseau** [comment]
Great! Thx
