### ISSUE TITLE
Playlist : annotation position is not linked to the video but depending on viewport size

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#364]
When the viewer size changes because of opening the comments or because of a viewport resize the annotations drawn on it move and scale with it.

![Playlists - Kitsu_1](https://user-images.githubusercontent.com/57003626/73939199-3ad77500-48e9-11ea-8c2b-d7d776a4ee1b.png)
![Playlists - Kitsu_2](https://user-images.githubusercontent.com/57003626/73939201-3b700b80-48e9-11ea-9a74-ef3de28268e3.png)
![Playlists - Kitsu_3](https://user-images.githubusercontent.com/57003626/73939202-3c08a200-48e9-11ea-9834-bbe11f448fa9.png)

**Comment by frankrousseau** [comment]
Thx for reporting. We'll fix that soon.

**Comment by frankrousseau** [comment]
Can you tell us where is located your instance? We made a new version that fixes this. But we don't how to deploy it for you.

**Comment by bartdriedee** [comment]
I'm still assessing Kistu to see if it will be a good fit for our pipeline. As such I'm on a trial account.
Our testing account is on https://wenneker.cg-wire.com

**Comment by frankrousseau** [comment]
Ok, we updated your instance. Can you try again?

**Comment by bartdriedee** [comment]
The placement issue seems resolved. But I do notice it now disappears when the  comments-panel is opened or closed. Don't think this happened in the previous version but I'm not sure.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by bartdriedee** [comment]
All is good!
