### ISSUE TITLE
scheduling: weeks go from tuesday till saturday

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#365]
Weeks start on T and end on S, which I asume are Tuesday and Saturday. We're used to a monday to friday workweek. Is this a design choice or a mistake? 
A 7 day week would also be nice as it adds the possibility to plan weekend but that should probably be a separate request.

**Comment by frankrousseau** [comment]
Hello @bartdriedee,
Did you set your timezone properly in your profile?

**Comment by bartdriedee** [comment]
Hi @frankrousseau , I'm in Amsterdam so the Paris timezone should be fine. But I've just changed it to Amsterdam and that doesn't seem to change anything.

**Comment by frankrousseau** [comment]
We cannot reproduce this bug. So, it will require time to be fixed.

**Comment by bartdriedee** [comment]
I haven't checked but I would expect the "main schedule" (side menu) to use largely the same code as the "schedule" (top menu)
Both the dates (mon-fri weeks) and the [dragging behaviour ](https://github.com/cgwire/kitsu/issues/363) work as to be expected on the "main schedule"
Hope this is of any help.

**Comment by bartdriedee** [comment]
I'm not sure if you changed something but I am also no longer able to reproduce this. Dragging is a bit sluggish but works as to be expected.
As far as I'm concerned you can close this issue.

**Comment by frankrousseau** [comment]
If you don't mind, I will reopen it. There is a glitch somewhere. It's hard to identify when it's occured. But you are the seconde person to mention this behaviour.

**Comment by bartdriedee** [comment]
No problem. Both my laptop and workstation were having the issue till just before noon last friday. I was under the assumption you made a change as it stopped occurring on both around the same time.
