### ISSUE TITLE
Shots : Frames aren't calculated from start - end

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#366]
I'm not sure if I understand this correctly but I would expect that if I fill the start and end frame Kitsu subtracts these and the frames attribute would list the length of the shot. This is not working but maybe it's a design choice and frames has a different meaning than length of the shot?

**Comment by frankrousseau** [comment]
Frames has the meaning you mention. We decided to not add computation to let users set this data freely. We can rethink this decision.

**Comment by bartdriedee** [comment]
If it's by design you can leave it as is. I can easily add the formula to the spreadsheet or other means I use to add shots.
