### ISSUE TITLE
Duplicate episode/sequence/shot

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#37]
You seem to be able to add duplicate episodes/sequences/shots, though its seems to sort itself out when you refresh the page:

![14e9a90f63bbf574c126c9f3d577eeeae3f3c202](https://user-images.githubusercontent.com/1860085/32908719-b1efe09c-cb04-11e7-94ec-e17ef4af4be5.PNG)

**Comment by frankrousseau** [comment]
Thank you for reporting. This widget requires many improvements. I expect to work on it in the upcoming weeks.

**Comment by flablog** [comment]
Actually, don't know if it is another issue. But you can create duplicate assets with the same name via the API. Should asset names of a type, shots of a sequence, sequences of an episodes, and episodes be unique names ?

**Comment by frankrousseau** [comment]
I fixed the issue mentionned. Can you confirm @tokejepsen?

**Comment by tokejepsen** [comment]
Sorry for the very late reply, but yes I can confirm 😄

**Comment by frankrousseau** [comment]
Good :), Thank you!
