### ISSUE TITLE
Post one after the other the same status won't display it on the newsfeed page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#378]
On the newsfeed page, comment only, the status won't display, if the same status is used two times or more on top of each other.

![image](https://user-images.githubusercontent.com/42962633/74543770-44468a00-4f46-11ea-93bb-f8bfd92e4f53.png)

**Comment by frankrousseau** [comment]
Yes this is the expected behaviour. If the status isn't changed, the comment shows no status.

**Comment by GoOz** [comment]
There's something to do here to make it more clear to the user but as it is non-blocking I changed the label from bug to enhancement and will take care of it later.

**Comment by frankrousseau** [comment]
Still don't see any way to improve it. Feel free to open an issue on Canny.
