### ISSUE TITLE
Same named task type for asset and shot.

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#380]
**Issue**

You cant create the same named task type for asset and shot.

**Reproducible**

- Create task type `Animation` for shots.
- Create task type `Animation` for assets.

This results in only a task type of `Animation` for shots. When confirming the task type creation for assets, nothing happens.

**Comment by tokejepsen** [comment]
Is this by design?

We often test animation or other task types on assets before putting them into shots.

**Comment by frankrousseau** [comment]
Yes it's by design. It's there to avoid confusion among peers of the production

**Comment by tokejepsen** [comment]
Is that design cemented or open for revision?

**Comment by frankrousseau** [comment]
It's design cemented.
