### ISSUE TITLE
Task type column misaligned if IN/OUT are 5 or more digits

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#381]
In the global shot page, if the number of frames of the IN and/or OUT column is more than five digits, the task type columns will be misaligned.

![image](https://user-images.githubusercontent.com/42962633/74733365-76a8fd80-524c-11ea-9fa7-e39061fb1d8a.png)

**Comment by frankrousseau** [comment]
In what kind of production does it occur?

**Comment by gwendupre** [comment]
Short, TV show, Feature film

**Comment by gwendupre** [comment]
It's fixed now
