### ISSUE TITLE
Playlist: Comment indicatorbar disappears on resize

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#385]
No biggy but thought you might want to know.
If the browser window is resized to a smaller size, the bar with the red dots showing where annotations were made on the video, disappears behind the bottom bar with the buttons.

**Comment by frankrousseau** [comment]
Thx for the report @bartdriedee. We cannot reproduce. Can you send a screenshot?

**Comment by bartdriedee** [comment]
![Playlist_Smaller](https://user-images.githubusercontent.com/57003626/74831788-3746e380-5316-11ea-9e63-b124d0812965.jpg)
![Playlist_Normal](https://user-images.githubusercontent.com/57003626/74831790-37df7a00-5316-11ea-9dc3-5fa3f0a33a0c.jpg)

Sure. No problem.
It only happens with the comment panel open. Otherwise it will work as expected.

**Comment by frankrousseau** [comment]
I was able to reproduce it in Firefox. Thank you for reporting.
