### ISSUE TITLE
my productions: Trying to create a new production as supervisor fails

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#392]
![2020-02-21 15_09_26-Window](https://user-images.githubusercontent.com/57003626/75041282-8fb7e580-54bc-11ea-9af2-7f0a4c1cb200.png)

When I try to add a new production on the my productions page while logged in as supervisor I get this error. When logged in as studio manager it does work.
I'm using firefox on windows.

**Comment by frankrousseau** [comment]
Yes, only studio managers can create a production. The bug is that a supervisor is able to access to the create production modal.

**Comment by frankrousseau** [comment]
The bug is fixed.
