### ISSUE TITLE
Sorting/Filtering Options in shot list (Alphabetical - date added - etc .. )

### ISSUE THREAD

**Issue by clarkjohn2989** [cgwire/kitsu#399]
Hi there

I believe adding a feature of sorting in your kitsu web UI will be great

another issue there is list of shots are not sorted using new versions of chrome/firefox

**Comment by bartdriedee** [comment]
We like to give all shots a number when creation of the film is started. In practice shots are added or the order is changed during the process so the numbers are no longer the shot order but just identifiers. We don't like to change these during production as this creates lots of confusion. 
It would be nice to be able to have them on a custom order. Dragging them to the correct order might be a bit complicated but sorting on a custom variable would be really nice.

**Comment by frankrousseau** [comment]
It's an interesting idea. Can you propose it on our roadmap tool? https://cgwire.canny.io/

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/asset-and-shot-tables/p/sortingfiltering-options-in-shot-list
