### ISSUE TITLE
Super slow click action on a task when lots of assets or shots

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#40]
When having hundreds of assets (in my case 400+) and going to the asset list page (or same for shot), and clicking on any task to go and see/add comments, the page can take up to 15 seconds to go to that page.

If I copy the target task url or if I middle click on the task status, the page opens in a new tab instantly.
So what takes a lot of time is whithin the asset/shot list page.
Maybe some javascript iterating over the whole task list ?

**Comment by frankrousseau** [comment]
Thanks for reporting. I will look for some improvements but I think it mainly means that server side filtering is needed :)

**Comment by flablog** [comment]
Umm,
when running a performance log on firefox, it looks pretty obvious it's a javascript thing going on, in Vue.js
I've a production js, so I can't really debut it more thant saying what is happening here :)

![image](https://user-images.githubusercontent.com/870195/33892789-02298f40-df5a-11e7-9017-e573de921daf.png)

**Comment by frankrousseau** [comment]
Sorry for my previous comment. I will see if i do something wrong or if it's related to Vue js

**Comment by flablog** [comment]
Last update (with pull request #52 ) is no longer affected by this bug and it's working well ! Thanks !
