### ISSUE TITLE
Update Kitsu Shots Data from CSV is broken

### ISSUE THREAD

**Issue by clarkjohn2989** [cgwire/kitsu#409]
a new issue appeard while trying to update shots data through csv

when i choose csv to upload the preview data not appear correctly and when i force kitsu to upload csv it creates shots again which makes duplicated shots even if i clicked the update button in csv preview window

**Comment by frankrousseau** [comment]
Hello,
We are not able to reproduce. Can you send us the problematic CSV file?

**Comment by clarkjohn2989** [comment]
Hi,
Here is the original csv i used to create shots on kitsu with name Main_CSV
another file is attached that i want to use to update the shots data that already created with name Update_CSV
[CSVs.zip](https://github.com/cgwire/kitsu/files/4313537/CSVs.zip)

Thanks in advance

**Comment by gwendupre** [comment]
With the new csv import system, it should be fixed, can you retry?
