### ISSUE TITLE
Slow filtering on huge asset list

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#41]
A huge asset/shot list (400+) make the filtering in pages very slow.

**Comment by frankrousseau** [comment]
Thanks for reporting. I will look for some improvements but I think it mainly means that pagination is needed :)

**Comment by flablog** [comment]
Filter reacts way better with last update. I think we can close this one too for now

**Comment by frankrousseau** [comment]
Yep. Long TV shows will probably require improvements (server side pagination). I have one last thing to try on the client side before implementing server side pagination. We'll see that later.
