### ISSUE TITLE
Impossible to change password

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#43]
Currently, via Kitsu, going to the profile, we can not change the default password.

We just have the following error displayed : "An error occured while changing password. Please verify your current password."

**Comment by frankrousseau** [comment]
Thanks for reporting. It will be fixed in next release.

**Comment by frankrousseau** [comment]
Thanks for reporting. It will be fixed in next release.

**Comment by flablog** [comment]
Working with last version !
Sorry for my too early issues, working with a test server not up to date
