### ISSUE TITLE
Long asset names hard to read on breakdown view

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#44]
When having long name assets, it's very hard to read on the breakdown view as the text overlaps the neighbors.

![image](https://user-images.githubusercontent.com/870195/33898480-dcf0b5a0-df68-11e7-88b0-5dc35a5ae725.png)

Rollingover the text does not changes anything (could be a solution)

**Comment by frankrousseau** [comment]
Ok thanks for reporting!

**Comment by flablog** [comment]
Sorry, this message was made on a previous version. Last version don't have this issue ! Now the text is readable but goes above the image under. For example the 2 in the middle first row

![image](https://user-images.githubusercontent.com/870195/33947490-c69c6e90-e024-11e7-8dd7-ca8895d784bc.png)

**Comment by BigRoy** [comment]
Just wanted to state that this last issue is still the case, long asset names overflow in the picture underneath.

It's not a big issue for me though.

**Comment by frankrousseau** [comment]
We changed the layout of the breakdown page. It's now fixed.
