### ISSUE TITLE
adding previews often fail

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#446]
![2020-04-21 12_21_02-My tasks - Kitsu – Mozilla Firefox](https://user-images.githubusercontent.com/57003626/79856794-20cc0f80-83cd-11ea-9ef4-9447f6f3afe1.png)

When I try to add a clip to a task, to show my progress on a shot, it often fails and gives me an error. The comment is added but the attached image or video is dropped, showing a black screen. 

![2020-04-21 12_33_28-Window](https://user-images.githubusercontent.com/57003626/79856803-23c70000-83cd-11ea-94b7-87b0e2bd1107.png)

 Afterwards it keeps showing this error message on all comments even before any input is entered. 
Is there a log or something where I can maybe find what might be causing this?

**Comment by frankrousseau** [comment]
Hello, can you tell us if you are using one of our instance or yours?

If you host Kitsu by yourself can you check the max upload size limit of your Nginx configuration?
You can find logs in `/opt/zou/logs`.

**Comment by bartdriedee** [comment]
I must have missed changing the default size to something bigger. Was it added to the guide recently?
Anyway.. it works now. Thanks Frank!

**Comment by frankrousseau** [comment]
I think we added the parameter a long time ago. Whatever it's great that it's working!
