### ISSUE TITLE
Global shots page doesn't load on episodes when switching from production

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#460]
In a TV show production.
On the global shot page of an episode, when you switch to another TV show production, the shots on the first episode of this other production won't load. The global shot page indicates there is no shot on this episode or load indefinitely.

Refreshing the page fixes the issue

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's working, thanks
