### ISSUE TITLE
Personal information in docs

### ISSUE THREAD

**Issue by ricekab** [cgwire/kitsu#464]
While testing out Zou/Kitsu I noticed there's a phone number in the documentation: https://kitsu.cg-wire.com/getting-started-artist/#first-connection . 

I couldn't find that number on the cg-wire website so I'm assuming it's not intentional. If it is, this issue can be ignored.

**Comment by frankrousseau** [comment]
I think it's a fake number, randomly generated. It's ok but thank you for mentioning  it!

**Comment by ricekab** [comment]
Alright, I'll close the issue then 👍
