### ISSUE TITLE
Version 11.50

### ISSUE THREAD

**Issue by samyghafili** [cgwire/kitsu#466]
Bonjour, 

La nouvelle version mise à jour du code 11.50, comporte des bugs au niveau des playlists (impossible de créer une playlist), du feed des commentaires qui garde aucun historique des statuts des tâches.. Ce qui rend le Kitsu inutilisable pour une production. 

Avez-vous déjà eu un retour similaire ? OU peut-être que le soucis viens de chez nous.. 

Bonne Journée. 

Samy

**Comment by frankrousseau** [comment]
Bonjour @samyghafili,

Nous ne rencontrons aucun soucis de notre côté. Est-ce que vous êtes hébergé chez nous ?

**Comment by samyghafili** [comment]
Bonjour, 

Merci pour votre réponse, 
Nous hébergeons Kitsu sur notre propre serveur. 
Nous étions sur la version 0.11.22, et rencontrions quelques bugs qui semblaient avoir été réglé avec la version 0.11.50. 
Nous avons tenté une mise à jour qui a fait apparaître ces nouveaux problèmes.

**Comment by frankrousseau** [comment]
C'est probablement la mise à jour de la base de données qui a échoué. Avez vous exécutez:

```
DB_PASSWORD=yourdbpassword zou upgrade_db
```

**Comment by samyghafili** [comment]
Merci pour cette réponse, le soucis est réglé

**Comment by frankrousseau** [comment]
Bonne nouvelle !
