### ISSUE TITLE
Wrong landing going to shots or breakdown

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#47]
If I open a new tab and go to my kitsu service I land in /todos ("My Tasks")
If I now go to the left menu and click on Assets, Shots or Breakdow, I'm asked to choose the production.
But in the case of landing in that choice page by clicking Shots or Breakdown, the next page after choosing the production will always be Assets (and not Shots or Breakdown).

**Comment by frankrousseau** [comment]
It should be fixed. Is it good for you?

(I'm still thinking about how to add both ilnks to open production page)
