### ISSUE TITLE
Add support for scrubbing / seeking preview videos

### ISSUE THREAD

**Issue by ricekab** [cgwire/kitsu#472]
Right now there is no way to quickly scrub through footage other than download the files and using other tools. It would be nice to be able to scrub footage straight from the preview.

I've implemented some basic seeking behaviour on this commit: https://github.com/ricekab/kitsu/commit/21541e2e87f07a2a9b850b8eb5b0ef18071dd624 in a forked repo. Whilst it does allow seeking via click-and-drag it does not update the video in a timely manner except for the first few frames (at least with my test clip).

EDIT: In case it's important. Tests are done with Firefox 77.x and Chrome 83.x

**Comment by frankrousseau** [comment]
Thank you. We'll have a look at this. The big issue is that the video are quite heavy for a browser

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/casting/p/projectepisodesequence-tasks

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/review/p/add-support-for-scrubbing-seeking-preview-videos
