### ISSUE TITLE
Delay at project creation

### ISSUE THREAD

**Issue by mathbou** [cgwire/kitsu#474]
**Issue:**

When creating a new project from Kitsu and reloading the page, the project disappear from the view. It takes ~2min to get it back in the UI. There is no traceback of any kind.
It happens both on my docker stack (K-0.11.53/Z-0.11.54) and on the cgwire one (K-0.11.47/Z-0.11.49).
Creating a project with Gazu seems to not produce the delay issue.

**Comment by frankrousseau** [comment]
Thank you, it looks like a caching issue. We'll investigate it.

**Comment by mathbou** [comment]
cgwire/zou#264
