### ISSUE TITLE
Vertical scroll bar disapeared in tasktype page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#475]
In a TV Show, Feature films, short Films.

When there are more than 100 assets/shots, and you go to a task type page, the vertical scroll bar disappeared and don't allow you to navigate.

It also happens when the browser window is not fullscreen.

**Comment by frankrousseau** [comment]
I cannot reproduce this one. Can you give more information?

**Comment by frankrousseau** [comment]
Thanks @gwendupre (video sent via email)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again @gwendupre ?
