### ISSUE TITLE
Cannot add some extensions as preview although it's written in documentation

### ISSUE THREAD

**Issue by Tilix4** [cgwire/kitsu#478]
As mentionned here: https://kitsu.cg-wire.com/getting-started-production/#add-preview
I try to use the `attach preview` to upload a .zip but I cannot upload anything else than an image, a movie or an obj.

OSX, Kitsu latest version.

**Comment by frankrousseau** [comment]
I cannot reproduce this issue. Can you tell me more about this?

**Comment by Tilix4** [comment]
Sorry, my report is not explicit.

I can do it using "Attach preview" but I cannot using "Add attachment".

**Comment by Tilix4** [comment]
Moved to correct issue: https://github.com/cgwire/kitsu/issues/479

**Comment by frankrousseau** [comment]
Ok got it!
