### ISSUE TITLE
Shots/Sequences disappear when converting production from Short to TvShow

### ISSUE THREAD

**Issue by mathbou** [cgwire/kitsu#482]
**Issue:**

Shots and sequences of a 'short' production get lost when changing the type of the project to TvShow. 
However they still exist in the db and still accessible with the API, but the 'parent_id' key is empty.

![bug_kitsu](https://user-images.githubusercontent.com/13415583/86261457-ddf19980-bbbe-11ea-8a66-56403e32a9f0.gif)

**Comment by frankrousseau** [comment]
Ok. Thank you Mathieu for reporting.

**Comment by frankrousseau** [comment]
After a second thought. I think that it would be better to block the capability to switch from one type to another. Getting or losing episodes may be confusing and it looks better to just start a production from scratch. What is your point of view?

**Comment by mathbou** [comment]
In our case, we use Episodes for multiples ads from the same client, but we don't always know if there will be more than one from the start. So due to the current behavior, we create all projects with the TvShow type.
