### ISSUE TITLE
Breakdown csv export contains all the episodes

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#487]
In a TV show, when you export a specific episode breakdown as a .csv, all the episodes of the tv show are also exported on the .csv, not only the selected episode.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed now but could be great to have the episode number into the shots CSV (the assets CSV has the episode column)

**Comment by frankrousseau** [comment]
Sorry but I don't understand well. Where is the issue in the breakdown export or in the shots export?

**Comment by gwendupre** [comment]
My bad, I meant the export of the shots, I'll close this issue and create a new one
