### ISSUE TITLE
lost password, reset link does not work

### ISSUE THREAD

**Issue by JessySuh** [cgwire/kitsu#489]
Hello, 

I forgot my Kitsu password and tried to reset it with the link automatically send to my e-mail for setting up a new password. Unfortunatly it doesn't work. What can I do?

**Comment by frankrousseau** [comment]
Hello @JessySuh,

Is your Kitsu hosted on our servers? If yes, it may be related to our email provider. Please send us your email so we can check what is going wrong.
If not you must check your SMTP server and your SMTP configuration in Kitsu.

**Comment by JessySuh** [comment]
Hello Frank,

thank you for your quick response,
a producer at the company I work for remembered my password so I am now
logged in and no longer in need of help.

have a lovely evening.

kind regards,

Jessy



Op do 16 jul. 2020 om 17:34 schreef Frank Rousseau <notifications@github.com

**Comment by frankrousseau** [comment]
Good news! 
Frank
