### ISSUE TITLE
frames column on shots page is always there. Even when empty.

### ISSUE THREAD

**Issue by bartdriedee** [cgwire/kitsu#491]
As screen space is precious and I do not need this info I hoped it would go away again if they were all empty like the other columns do but this is not the case nor is it removable like the custom columns.
![2020-07-17 12_17_06-test - H9505 _ Shots - Kitsu](https://user-images.githubusercontent.com/57003626/87776349-ec2eef00-c827-11ea-8d73-3ee1f7f8f51e.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you confirm?

**Comment by bartdriedee** [comment]
Yes, confirmed.
