### ISSUE TITLE
One project breakdown 

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#495]
I upload the video and the gunicorn wrog log as a attach,please help me to solve  this as  soon ,Very Thanks.
Luckly,there is no data yet
[42F85CCF-6A92-4DDF-B4A1-C7C3D76E17E0_167juUcxzb.zip](https://github.com/cgwire/kitsu/files/4965377/42F85CCF-6A92-4DDF-B4A1-C7C3D76E17E0_167juUcxzb.zip)
![image](https://user-images.githubusercontent.com/48669854/88280493-7d1a3480-cd18-11ea-9fd1-b9d2474daf30.png)
![image](https://user-images.githubusercontent.com/48669854/88280561-9f13b700-cd18-11ea-82fb-72802219fdeb.png)

**Comment by frankrousseau** [comment]
Sorry, but I don't understand your problem. Try to refresh the page (ctrl+F5).

**Comment by DuanXu-anim** [comment]
you can unzip the zip,I recoverd issue in a video,thank you.

**Comment by DuanXu-anim** [comment]
we have one of productions crashded，but other production are normal

**Comment by frankrousseau** [comment]
There is no error message. It's hard to figure out what is going wrong. Are you sure that your database is properly configured? 
Can you try to create a new project?

**Comment by DuanXu-anim** [comment]
yeah,i can create new project, and others project are going well. And now there is no issues,thanks

**Comment by DuanXu-anim** [comment]
yeah,i can create new project, and others project are going well. And now there is no issues,thanks
