### ISSUE TITLE
Super Admin password incorrect

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu#496]
Hi,

I have just installed Zou and Kitsu, and while trying to login on Localhost, with the email address used to create Super Admin, it tells me to verify my credentials.

What should be the correct default password for Super Admin ?

Thanks,
Lukas

**Comment by lukas-remis** [comment]
Solved by deleting the "person" table content and creating the Super Admin again.

**Comment by frankrousseau** [comment]
Ok great
