### ISSUE TITLE
Suggestion: Hardware Encoding on Raspberry Pi

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu#497]
Hi,

I'm testing Raspberry Pi as a server for Kitsu - so far everything works well. 

As RPi has hardware encoding for h264, I wanted to suggest and ask if it's possible to turn it on for uploaded previews. By default ffmpeg is not using it - you have to add "-codec:v h264_omx" to the command. 

Hardware encoding works only up to HD resolution - still I think it would be very usefull, as it greatly reduces encoding time.

Cheers,
Lukas

**Comment by frankrousseau** [comment]
Hello, this place is now dedicated to bugs. Can you add this feature request to our Canny? cgwire.canny.io/

Best

**Comment by lukas-remis** [comment]
Of course, sorry for that.
