### ISSUE TITLE
Problem with asset creation

### ISSUE THREAD

**Issue by g-LuL** [cgwire/kitsu#5]
When trying to create an asset on the assets page, this error comes out :
> Creation or edition failed, an error occured. 

The logs of Firefox :
> "(psycopg2.IntegrityError) null value in column \"project_id\" violates not-null constraint\nDETAIL:  Failing row contains (2017-07-27 05:11:11.944184, 2017-07-27 05:11:11.944193, 2cbff8c8-8472-4b9b-9bfa-29d4c8228f64, test, null, null, null, null, null, null).\n [SQL: 'INSERT INTO entity (created_at, updated_at, id, name, description, shotgun_id, project_id, entity_type_id, parent_id) VALUES (%(created_at)s, %(updated_at)s, %(id)s, %(name)s, %(description)s, %(shotgun_id)s, %(project_id)s, %(entity_type_id)s, %(parent_id)s)'] [parameters: {'project_id': None, 'name': 'test', 'id': UUID('2cbff8c8-8472-4b9b-9bfa-29d4c8228f64'), 'created_at': datetime.datetime(2017, 7, 27, 5, 11, 11, 944184), 'description': None, 'parent_id': None, 'updated_at': datetime.datetime(2017, 7, 27, 5, 11, 11, 944193), 'entity_type_id': None, 'shotgun_id': None}]"

The JSON data looks like this :
> {"name":"test"}

Maybe some data is missing in the dictionary...

**Comment by mottosso** [comment]
This happens to me as well, Chrome on Windows.

**Comment by frankrousseau** [comment]
Thank you @g-LuL for reporting and @mottosso for confirming.

**Comment by frankrousseau** [comment]
I just published a fix. Could you test if it solved the problem. If you need a new build, tell me.

**Comment by g-LuL** [comment]
It's working again !
Thanks @frankrousseau !
