### ISSUE TITLE
Wrong user name displayed if field First Name or Last name not filled

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#50]
If we don't fill the first name and last name, there is no preview icon for the user. Maybe at least one should be not optional ?
![image](https://user-images.githubusercontent.com/870195/34002000-c70cbb8c-e0f1-11e7-9a8d-f45993f2a599.png)

If only first name is filled, the initials are.. wrong
![image](https://user-images.githubusercontent.com/870195/34002035-df4508a8-e0f1-11e7-89ea-ada87cab7e8d.png)
![image](https://user-images.githubusercontent.com/870195/34002043-e63a3304-e0f1-11e7-928d-23e740d79b0d.png)
It says JUNDEFINED where I expect just "J"

Same for defining only last name without a first name 
![image](https://user-images.githubusercontent.com/870195/34002105-0a06e7e6-e0f2-11e7-9b2b-9a6c2029a12e.png)
UNDEFINEDD instead of "D"

not urgent

**Comment by frankrousseau** [comment]
@flablog It should be fixed. Can you try again?

**Comment by flablog** [comment]
Fixed :)
