### ISSUE TITLE
Adding new task doesn't resize the modal dialog

### ISSUE THREAD

**Issue by tobkum** [cgwire/kitsu#503]
When I add a new task for a shot or an asset, as soon as I expand the dropdown, it gets cut off and I have to move down via the cursor keys on the keyboard to see the bottom entries.

![image](https://user-images.githubusercontent.com/16955378/89906652-f0aeb380-dbeb-11ea-868b-a2476eecfb3b.png)

**Comment by frankrousseau** [comment]
Thank you @tobkum for reporting this issue.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by tobkum** [comment]
Works, thanks!
