### ISSUE TITLE
Artist authority BUG

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#506]
The same one artist can use pen to modeify a shot but can't use pen in the same shot in playlist , There is no pen button .And I try the supervisor or studio manager chould use pen. So there is a conflict authority of artist? I attached the issue screenshot  

![image](https://user-images.githubusercontent.com/48669854/90736913-8a6b1480-e300-11ea-9461-c8b57aa78e2d.png)
![image](https://user-images.githubusercontent.com/48669854/90738258-e9308e00-e300-11ea-92ee-9f7805f4e365.png)
![image](https://user-images.githubusercontent.com/48669854/90738748-0c5b3d80-e301-11ea-9b74-c4fb70ccc2da.png)

**Comment by frankrousseau** [comment]
Thank you for reporting this bug. We'll fix that.
