### ISSUE TITLE
The changes on the start date/end date of the global schedule is not saved

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#509]
For short / TV Show / Feature film

As a Studio Manager, if I change the start date and/or End date of the global schedule, the new date is not saved if I reload the page or go to another one.

![image](https://user-images.githubusercontent.com/42962633/91312747-da405480-e7b4-11ea-8d15-5b0142a520df.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
