### ISSUE TITLE
Display the Start date and End date on task tab of the supervisor page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#510]
In short/tv show/ feature film production.

In the supervisor page, it could be helpful to view the start date and end date of the task type in the task tab (as displayed in the schedule tab). It will help to define the start date with the calendar, and we will be sure to be in the right timeframe and don't have to do back and forth with the schedule tab.

**Comment by frankrousseau** [comment]
Can you move this issue to Canny? We keep only bug reports there.

**Comment by gwendupre** [comment]
My bad, I move it Canny and close this issue

https://cgwire.canny.io/asset-and-shot-tables/p/allow-to-display-the-start-date-and-end-date-on-task-tab-of-the-supervisor-page
