### ISSUE TITLE
On the global schedule the total of MD is not the same of the displayed MD per Task Type

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#511]
In a short/tv show/feature film
The total number of Man Day automatically calculated is not the sum of each MD per task type

![image](https://user-images.githubusercontent.com/42962633/91313069-3e631880-e7b5-11ea-8f87-e66639a24297.png)

**Comment by frankrousseau** [comment]
It's probably due to the fact that you have old data that are not compatible with the recent revamp of estimations.

**Comment by frankrousseau** [comment]
Can you try again?
