### ISSUE TITLE
Attaching multiple (mixed) preview types to a Task only displays one

### ISSUE THREAD

**Issue by fsiddi** [cgwire/kitsu#512]
On v0.11.81, when attaching (as preview) a video and multiple pictures to a task, only the video is displayed as a preview, while the pictures are not visible anymore.

**Comment by frankrousseau** [comment]
Hello @fsiddi,

In Kitsu, you can't mix different file formats in a single preview. You have to publish either a video, a set of pictures, a 3D model or a "neutral" file like an archive.

**Comment by fsiddi** [comment]
Thanks for the clarification! Do you have any suggestion for how to allow a review of a "version" that should feature both a video and some images? I would like an artist to post a turnaround video and some stills in the same version, so that the version can be added to a playlist and reviewed.

**Comment by frankrousseau** [comment]
There is no way to do that in the current version. You can post two revisions as a workaround but that won't be excatly what you are looking for.

**Comment by fsiddi** [comment]
I did some exploration into how preview_files are handled by Zou and Kitsu. It looks like the the "issue" is only on the Kitsu side, right? Would you accept turning `PictureViewer.vue` into a more generic viewer that can handle mixed media?

Side note: currently it's possible to "break" the viewer by adding a video and and image as previews. The viewer will try to treat the video path as an image.

**Comment by frankrousseau** [comment]
You're right, the issue is only on the Kitsu side. But, the picture viewer is designed only for pictures. Annotations and comparisons are very different when dealing with pictures or movies. The other complexity comes from the playlist which requires duplicated development (though there is probably a better way to design them both.

**Comment by frankrousseau** [comment]
Hello Francesco,

It's now implemented thanks to your sponsoring. Let us know if it matches your expectations!

**Comment by fsiddi** [comment]
Thank you Frank! The current implementation is a great start and fully answers my initial request. I'm going ahead and closing the issue since the feature is now merged in master.
