### ISSUE TITLE
Task type page issue

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#513]
In the task type page we found nothing,it should include task information in the bussiness version.So is it a bug or something else?
I attched the screenshot.

<img width="215" alt="微信截图_20200828174942" src="https://user-images.githubusercontent.com/48669854/91548495-06480b00-e958-11ea-9ae3-efc1086227e2.png">
<img width="947" alt="微信截图_20200828175036" src="https://user-images.githubusercontent.com/48669854/91548498-0811ce80-e958-11ea-9b7b-23bf36e9cf8e.png">

**Comment by DuanXu-anim** [comment]
<img width="215" alt="微信截图_20200828174942" src="https://user-images.githubusercontent.com/48669854/91548638-3f807b00-e958-11ea-890a-85875a46ab17.png">
![Uploading 微信截图_20200828175036.png…]()

**Comment by DuanXu-anim** [comment]
<img width="215" alt="微信截图_20200828174942" src="https://user-images.githubusercontent.com/48669854/91548638-3f807b00-e958-11ea-890a-85875a46ab17.png">
<img width="947" alt="微信截图_20200828175036" src="https://user-images.githubusercontent.com/48669854/91548645-41e2d500-e958-11ea-8aa1-300141483780.png">

**Comment by DuanXu-anim** [comment]
<img width="947" alt="微信截图_20200828175036" src="https://user-images.githubusercontent.com/48669854/91548829-96865000-e958-11ea-996d-3b4f375d3174.png">

**Comment by DuanXu-anim** [comment]
and we have assign this shots to the artists
<img width="433" alt="微信截图_20200828181026" src="https://user-images.githubusercontent.com/48669854/91549692-e4e81e80-e959-11ea-80db-d8f4eb4ab672.png">

**Comment by frankrousseau** [comment]
Can you update your installation? We faced this issue last week. Then we published a release wih a fix.

**Comment by DuanXu-anim** [comment]
Solved the issue after the update.Thanks!!!

**Comment by DuanXu-anim** [comment]
When we update the new version .We found the role "artist" couldn't edit the shot with pen ,Only artist'pen is disappeared.
![image](https://user-images.githubusercontent.com/48669854/91791365-8a92da80-ec45-11ea-9873-143cd600f430.png)
![image](https://user-images.githubusercontent.com/48669854/91791441-bb730f80-ec45-11ea-97d4-96fac00bea70.png)

**Comment by frankrousseau** [comment]
Yes it's by design. Artists cannot create annotations.

**Comment by frankrousseau** [comment]
Thank you for reporting.

**Comment by DuanXu-anim** [comment]
But before we update the version 0.11.82 , artist could  create annotations.So It's the new version and new change?

**Comment by frankrousseau** [comment]
Sorry for that. It was probably a bug. Because it has always been like that. Why do you want to allow artists to draw annotations? We can't see a use case for this.
