### ISSUE TITLE
Shot csv export are shifted of one column

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#514]
For a tv shot, short, feature film
On global page of the shots, if the information of "NB frame" is not filled, when we export the csv of this page, the task columns information is shifted on the left, meaning the NB frame column is filled with the first task type information.

![91313387-9bf76500-e7b5-11ea-8f3e-b2d8e7f2f245](https://user-images.githubusercontent.com/42962633/91698841-a5951a00-eb73-11ea-9a39-37f3611f2c36.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks
