### ISSUE TITLE
When creating a new production, the setting of the task type display all the task types

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#515]
on a short, tv show and feature film.

When a new production is created, and empty of shots or assets. If we go to the setting page of the production and pick one task type from to list to add it to the newly created production, all the task types are displayed as added.
But if the page is refreshed, only the selected task type is displayed.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks
