### ISSUE TITLE
Suggestion-shot compare 

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#518]
We found we could compare the same shot between different task type.And we also need compare the different version in the same task type of one shot .
![image](https://user-images.githubusercontent.com/48669854/91792210-98e1f600-ec47-11ea-9c0c-861cdf8e424c.png)

**Comment by frankrousseau** [comment]
We don't take enhancement suggestion anymore on Github. Can you open a ticket on our Canny page? 
https://cgwire.canny.io/

**Comment by DuanXu-anim** [comment]
OK

**Comment by frankrousseau** [comment]
Thanks!
