### ISSUE TITLE
Nothing happens when we try to edit or delete a Shot task types

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#520]
In the Task Types page, under the Admin section.
Nothing happens when we click on the "edit" or "delete" button on the shot task types.

The asset task types are working.

**Comment by DuanXu-anim** [comment]
May I ask when this issue can be solved

**Comment by frankrousseau** [comment]
It's fixed. I will probably publish a new version today or on wednesday.

**Comment by DuanXu-anim** [comment]
Got it, thanks!

**Comment by frankrousseau** [comment]
I published a new version. Can you update your Kitsu and try?

**Comment by frankrousseau** [comment]
It should be fixed. @gwendupre Can you confirm?
