### ISSUE TITLE
can't edit task type-shot  

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#525]
I can't access the edit interface of shot .But the asset is normal .What's the problem ? 

![1](https://user-images.githubusercontent.com/48669854/92895744-5c37ab00-f44e-11ea-9ba9-a43ca66ad736.png)
![2](https://user-images.githubusercontent.com/48669854/92895759-5e9a0500-f44e-11ea-8d8a-0ce3217ad8a6.png)

**Comment by frankrousseau** [comment]
Thank you for your bug report.

It's a bug already reported there : https://github.com/cgwire/kitsu/issues/520. We'll fix it next week.

**Comment by frankrousseau** [comment]
I close it. Please follow the original issue for resolution.
