### ISSUE TITLE
It's not possible to batch comment tasks without changing the status

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#528]
on a tv show/short/feature film

If we want to have a brief for the first comment on all the selected tasks, the batch comment didn't work if we keep the same status as it's already been.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by frankrousseau** [comment]
Sorry but to me, it's not a bug but a feature request.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try?

**Comment by gwendupre** [comment]
It's fixed thanks!
