### ISSUE TITLE
When I create shots for my episode in Kitsu they also automatically appear under other episode shots list until we refresh the page

### ISSUE THREAD

**Issue by sayanel** [cgwire/kitsu#529]
When we create (using gazu or even directly using kitsu) new shots for an episode they appear correctly on our page but they also appear on other people session even if they are watching another episode. It disapears after a refresh or a change of episode.
I suppose there is something wrong in the event/automatic refresh system.

![image](https://user-images.githubusercontent.com/7714353/93609067-ae874780-f9cb-11ea-975d-026a8a74cf6b.png)

On this image you can see some shots that should not be there, they were created in another episode (before the 001).
You can easily reproduce the bug if you open two kitsu on two different episodes and you add some shots on one of them.

**Comment by frankrousseau** [comment]
Sorry for that and thank you for reporting.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by sayanel** [comment]
All good ! Thanks a lot :)
