### ISSUE TITLE
When creating an asset task type the 'For' field is not used

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#53]
When using kitsu to create a task type, the field 'For' is not considered. So if we set it to asset the task type created is assigned to shots

**Comment by frankrousseau** [comment]
Thx for reporting. I will fix that soon!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by flablog** [comment]
Indeed, it's fixed. Thanks
