### ISSUE TITLE
Improve confirm message when deleting all tasks of a given type.

### ISSUE THREAD

**Issue by aboellinger** [cgwire/kitsu#533]
Deletion of all tasks of a given type on the project happens on [the shots page](https://github.com/cgwire/kitsu/blob/39afa08d85d7a4999a3a3352c2909c0723a0d785/src/components/pages/Shots.vue#L592).

The issue is that the shot page has an episodic scope, but this action has an effect on the whole episode.
If the user assumes that his actions only affect the current scope, he can end up deleting data for other episodes (we have seen it happen).

The easiest fix would be to improve the message `tasks.delete_all_text`, so that it clearly states that tasks will be deleted for the whole project.

**Comment by frankrousseau** [comment]
The text is explicit but it seems that people don't read it. We are going to redesign a little bit this part.

**Comment by aboellinger** [comment]
It is explicit about the fact that *things get deleted*, but not about the scope (deleting *all tasks on **episode*** vs *all tasks on **whole project***)

Our user was not very risk-averse so he assumed it was on the ***episode*** (precisely what he wanted to do).
And if putting myself in his shoes I could'nt really blame him, I really felt there was room for interpretation.

I think expliciting in the message that the impact will be on the ***project*** level will already be a quick-win.

**Comment by frankrousseau** [comment]
A sorry, I thought that *project* was explicitly written. I added an option to select the scope. It will be fixed in the next version.

**Comment by frankrousseau** [comment]
We changed the way things work. Can you update your instance and try again?
