### ISSUE TITLE
Renaming shot from within shot task page doesn't work

### ISSUE THREAD

**Issue by LarsCawley** [cgwire/kitsu#534]
OS Ubuntu 20.04
Zou 0.12.5
Kitsu 0.12.2
Using the edit button beside the shot hierarchy/path in the shot's task page, then editing the shot name causes the 'confirm' button to spin endlessly.
Using the edit button beside the shot in the shot list page, the editing the shot name works fine.

**Comment by frankrousseau** [comment]
It's a random bug that we don't know yet how to fix. Until we find a solution, using an admin user should allow you to rename the shot.

**Comment by frankrousseau** [comment]
Ok we understood the problem. It will be fixed in next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by LarsCawley** [comment]
Yes, that's fixed it.  Very good!
