### ISSUE TITLE
Can't open an asset from the shot detail page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#535]
On a tv show.
On the detail page of a shot, if we want to see the assets of this shot, and want to open the detail of the asset (directly or on a new tab).
If we click on the asset (or right-click "open in a new tab"), the page (or the new tab) opened but keeps loading.

The issue happens with chrome and firefox.
But not in a short film.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed thanks!
