### ISSUE TITLE
Can't edit an asset from the asset detailed page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#536]
on a tvshow, short, feature film

From the detailed page on an asset, if we want to edit the asset, the confirm button changes to loading and spin forever.

![image](https://user-images.githubusercontent.com/42962633/94668489-655ebe00-0310-11eb-9877-ec317b0938da.png)

**Comment by frankrousseau** [comment]
Similar to https://github.com/cgwire/kitsu/issues/534

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
