### ISSUE TITLE
When importing a new asset episode, the preview displayed the element as already existing

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#539]
On a TV show, From the global asset page, or any other episode asset page.
With the import (csv file and paste data), the asset new episode is displayed as already existing on the preview page.

![image](https://user-images.githubusercontent.com/42962633/94677497-487cb780-031d-11eb-8acb-dcafeeab3e88.png)

If we choose to "update" then the episode, and the assets will be created.

If the episode is already created in the shot section: If we go to the episode asset page, then the preview displays the assets as new.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks
