### ISSUE TITLE
Data is overwrite deleting keys and values when editing infos through kitsu

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#54]
If I use `data` in a shot for example, to store keys and values through Gazu, for example doing : 

```
s = gazu.shot.get_shot(sid)
data = s['data']
print(data)
> {u'frame_in': 10, u'frame_out': 75}`
data['foo'] = 'bar'
gazu.client.put("data/entities/%s" % sid, data={'data':data})
```

next time I query that shot, my data looks like : 
`u'data': {u'foor': u'bar', u'frame_in': 10, u'frame_out': 75}`
perfect

But if I use the edit button on Kitsu, to change the frame_in for example, only frame_in and frame_out are saved, everything else is overwrited, so deleted.
My key 'foo' doesn't exists anymore.

**Comment by frankrousseau** [comment]
Thanks for the report. I will unclude it in the next release. It should not be hard ti fix.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
