### ISSUE TITLE
When exporting a CSV file of a shot episode, the episode column is missing

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#543]
In a TV show.
When we export a shot episode CSV File, the Episode column is missing. 

For the asset, the episode column on the CSV File is there.

**Comment by frankrousseau** [comment]
It's more a design question than a bug. The episode name is already in the title. With assets you can have every assets in the same export.

**Comment by gwendupre** [comment]
it could be an issue if you want to export your short episode data to update them, and then re-import. the same CSV file updated. The episode will be missing, and the import fails.

**Comment by frankrousseau** [comment]
Yes you're right.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks
