### ISSUE TITLE
An artist / Vendor can't compare side by side previews

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#546]
On a tvshow, short, feature film.

The artists/vendors don't have access anymore to the side by side comparison of the preview when they go fullscreen from the comment section or from the detail version page.

They have access to the comparison from the "on the fly" playlist.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed thanks
