### ISSUE TITLE
On the quotas page, the previous months are limited to the current day

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#548]
In a short, tv-show, feature film.

at the day's level, if for example, we are on the 12th of October, and if I want to check the quotas of the past month, all the other month will stop on the 12th, they won't display the other days.

![image](https://user-images.githubusercontent.com/42962633/95748349-2595c000-0c9a-11eb-8fda-1c61b7d86035.png)

**Comment by frankrousseau** [comment]
Sorry I don't understand this one. Can you make it more explicit?

**Comment by gwendupre** [comment]
I don't have the issue anymore, thanks

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
