### ISSUE TITLE
When an artist updates his timesheet, the duration on his todo list doesn't update

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#549]
As an artist/vendor.
When an artist update his timesheet, the duration on his todo list doesn't update

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's not updating on the todo list

**Comment by frankrousseau** [comment]
Are you sure you tried with the latest version?

**Comment by gwendupre** [comment]
I try with chrome and firefox (both up to date), and my Kitsu instance is 0.12.19

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
