### ISSUE TITLE
The videos don't appear anymore on the newsfeed page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#552]
In a tv show, short, feature film.

On the newsfeed page the video don't appear anymore on the 0.12.7 version of Kitsu

![image](https://user-images.githubusercontent.com/42962633/95849769-27ba5600-0d50-11eb-9a14-48d3519052e2.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks
