### ISSUE TITLE
We can't loop in a specific shot on a playlist

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#553]
On a tv show, short, feature film.
On the playlist module or playlist on the fly, the "loop" icon has disappeared.

But it's still here on the fullscreen mode of a single shot task

![image](https://user-images.githubusercontent.com/42962633/95850150-af07c980-0d50-11eb-8dec-ee9c077d18c0.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks
