### ISSUE TITLE
When adding new shots by hand into a existing sequence, double shots are created without tasks

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#554]
in a tv show, short, feature film

When we add more shots to an existing sequence; some shots are created in double, and they don't have tasks attach to them.

![image](https://user-images.githubusercontent.com/42962633/95850757-99df6a80-0d51-11eb-9423-27d6f72a97d0.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks
