### ISSUE TITLE
As a client I can't delete my own comment

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#555]
On a TV Show, short, Feature film.

As a client, if I post a comment, and can't delete it, an error message appears.

![image](https://user-images.githubusercontent.com/42962633/95963870-804d2a00-0e08-11eb-9e0d-4e70b31248c8.png)

**Comment by frankrousseau** [comment]
Sorry, but I can't reproduce this one. Do you have more infomation?

**Comment by frankrousseau** [comment]
Can you try again? The last release may have fix that.

**Comment by gwendupre** [comment]
it's fixed, thanks!
