### ISSUE TITLE
no option to close project

### ISSUE THREAD

**Issue by Aderemi-Adesada** [cgwire/kitsu#556]
kitsu doesn't provide an option to close project
![Screenshot (19)](https://user-images.githubusercontent.com/61081333/96353405-a9e5aa00-10c3-11eb-906e-7372d6ca17e1.png)

**Comment by frankrousseau** [comment]
Are you sure that you have properly initialized your database data?

**Comment by Aderemi-Adesada** [comment]
I fixed it thanks. I found out that initializing DB data sometimes doesn't initialize well.
