### ISSUE TITLE
Long shotlist not populating the list on tall screens

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#557]
I have a shotlist of ~500 shots but when I enter the shots tab I only see the first 30 shots (3 sequences, 10 shots each).
Under the shots there is just empty space and I can't scroll or anything.
If I make the window smaller so the scroll-bar shows up, then I can scroll down to the bottom and the list will get populated.

If you don't have a tall screen you can simply make the webpage smaller using ctrl + scrolling and then enter the shots tab.

![firefox_1603202799](https://user-images.githubusercontent.com/49758407/96597534-4095af00-12ee-11eb-8ab0-fb6054ef03e4.jpg)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Works fine now!
