### ISSUE TITLE
Can't add task

### ISSUE THREAD

**Issue by mamorix** [cgwire/kitsu#558]
I have some assets and I wanna add task to it but it didn't work. When I click on Confirm button ,it just close the box without do any action. 

![Capture](https://user-images.githubusercontent.com/19630406/97101674-8d91d080-16b4-11eb-8850-4e38c58f8cdf.PNG)

**Comment by frankrousseau** [comment]
Are you sure that both Kitsu and Zou are up to date?
Can you copy/paste the server error log?

**Comment by mamorix** [comment]
Oh sorry, I didn't update Zou.
Thank you.
