### ISSUE TITLE
Assignment/Additional Data buttons in Shots view are not clear (especially in Dark Mode)

### ISSUE THREAD

**Issue by LarsCawley** [cgwire/kitsu#560]
The buttons for hiding assignations and additional information are very subtle, especially in Dark Theme.  It might be good to have them highlighted more to reduce confusion.  Perhaps a colour tint to the whole button?

**Comment by frankrousseau** [comment]
I'm not sure there is something to do. On one hand, you are right, it could be more visible. But, on the other hand, it is not interesting to highlight this button. I'm not sure we should do something on this.

**Comment by LarsCawley** [comment]
Sure.  I understand.  I think it is fine once people are familiar with the UI.  I raised this when I had a supervisor adding artists to shots in a new episode (with the filter on) so it looked like they were not added.  Maybe it would be good if adding artists caused the filter to be turned off, but perhaps you have enough work to do?

**Comment by frankrousseau** [comment]
I added a warning on the topbar to warn people when the assignation display is not present.
