### ISSUE TITLE
An error occured while creating new team member

### ISSUE THREAD

**Issue by aditiapratama** [cgwire/kitsu#561]
I've got the following error when adding new team member
```
An error occured while creating this person. Please contact our support team for more information.
```

Lately I found out that adding member without filling `last name` will raise this error, but this not happening on previous version. So, for now workaround to solve this is by fill the last name as well.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by aditiapratama** [comment]
Hi Franck, thank you I'll update by this week.
