### ISSUE TITLE
Can't download a pdf or any kind of file in the preview

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#568]
on a tvshow, feature film, and short. As studio manager, supervisor or artist

When we upload a file that is not a preview, the "download" button in the version preview is not working on the reduced view.
If we enlarge the view or go fullscreen, we can then download it.

**Comment by frankrousseau** [comment]
I can't reproduce it. Are you sure about that one?

**Comment by gwendupre** [comment]
It's working now, thanks
