### ISSUE TITLE
Wrong icon display when window is not large enough

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#57]
The edit/delete icon on shots and asset pages is not displayed well if the window is not large enough to display all columns. And one might click delete instead of edit

![image](https://user-images.githubusercontent.com/870195/34724549-7a23df0a-f54e-11e7-998d-5259fb17210c.png)

Tested on firefox/chrome (mac)

**Comment by frankrousseau** [comment]
It should be fixed. Can you confirm?
