### ISSUE TITLE
On the comment section, supervisor can delete any preview with the trash button

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#570]
In tv shows, short and feature films.

As a supervisor or studio manager, the trash icon appears even if there is only one preview in the comment section.
Anyone (as supervisor or manager) can delete the preview of someone else.

Maybe the trash icon could be placed somewhere else; it's easy to misclick on it, as it's between the open and fullscreen button.

**Comment by frankrousseau** [comment]
There is already a confirmation window. Not sure that's an issue if someone misclick on it.

**Comment by frankrousseau** [comment]
I changed the icon positiion. Is it fine now?

**Comment by gwendupre** [comment]
It's working, but if you switch to another task to change the thumbnail, you need to refresh the page to have the thumbnail updated
