### ISSUE TITLE
Synchro "temps réels" v.12.18

### ISSUE THREAD

**Issue by samyghafili** [cgwire/kitsu#572]
Bonjour, 
J'espère que vous allez bien, 

Nous avons un petit soucis concernant la mise à jour des données en temps réels entre les utilisateurs. 
Sur la version précédente, nous pouvions voir en quasi-instantanée les différents changements de statuts, assignations ect... sur la version 12.18 nous devons refresh la page, une ou plusieurs fois pour voir certains changements effectués 

Je vous laisse une capture d'écran de l'IT qui travaille avec nous, qui semble identifier le problème, 

![erreur a transmettre a cgwire](https://user-images.githubusercontent.com/66003665/98930180-923fec80-24dc-11eb-88c1-9855e58af1dc.png)

Bien à vous, 
Samy GHAFILI
Les Astronautes.

**Comment by frankrousseau** [comment]
Bonjour,

Merci pour le rapport de bug. On ne constate pas le problème sur nos installations. Est-ce que vous pouvez nous décrire de manière plus précise le scénario qui aboutit à ça ?

**Comment by samyghafili** [comment]
Bonjour, 
Merci pour votre réponse, lorsque l'on change le statut d'une tâche, la modification apparait chez les autres utilisateurs en différé, après plusieurs refresh de la page.

**Comment by frankrousseau** [comment]
Est-ce que vous pouvez vérifier que le service `zou-events` est bien lancé ?

**Comment by frankrousseau** [comment]
Pas de nouvelles, je ferme le ticket.
