### ISSUE TITLE
When several pictures are upload as a version, it's not the first picture that is used as the entity thumbnail

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#575]
On a TVshow, Feature Film, and Short.

When we upload several pictures as a preview, then we enlarge the comment section and click on the version number to see all the pictures uploaded.
We may change the preview order to have the more explicit one at first for the thumbnail. 
Once we have set the first picture and click on the thumbnail button, it's a random picture that is chosen.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's working, but if you switch to another task to change the thumbnail, you need to refresh the page to have the thumbnail updated

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks
