### ISSUE TITLE
The 2 first frames of a preview is fixed during the play

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#576]
On a tv show, short and feature film.
When you have the numbers of frames burned into the video preview, you realize that during the play, the first 2 frames into Kitsu are stuck on the first frame of the preview (the number of frames burns on the video doesn't change), then at the third frame, the preview is played normally.

It's more obvious when you read the preview frame per frame (with the keyboard shortcut).
If you do a lot of back and forth on the video frame per frame, only the first frame is now fixed, meaning the preview starts at the second frame and not the third as the beginning.

**Comment by frankrousseau** [comment]
I think it occurs only with 24 FPS.

**Comment by gwendupre** [comment]
i had the issue on a 25fps production

**Comment by frankrousseau** [comment]
I still don't get why it behaves like that. I give the right information to the video player but it stills show the first frame. I'm still investigating that one.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
