### ISSUE TITLE
we can't delete start and due date on the tasktype page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#580]
On a tv show, short, feature film.

It can happen that the select more task than what we should and apply to the extra task a start and due date. 
When we realize the mistake we want to delete it, but it seems impossible.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed thanks, but now if we select several tasks to add the same start date, the date doesn't apply to all the selected tasks.

**Comment by frankrousseau** [comment]
I can't reproduce this issue. Can you give me steps to reproduce it?

**Comment by gwendupre** [comment]
my bad, the start date apply to all the selection, once the selection is removed. So it's fixed, thanks!
