### ISSUE TITLE
Newsfeed days are not divided/displayed properly

### ISSUE THREAD

**Issue by LarsCawley** [cgwire/kitsu#582]
Kitsu 0.12.26
Zou 0.12.23
Server date/time seems to be correct
Region is NZDT
The beginning and end of days is not correct in the newsfeed.  At the moment there is the same day twice.
![Kitsu_Newsfeed](https://user-images.githubusercontent.com/21695124/100448334-fbe40b80-3116-11eb-87a4-af489d6f1122.jpg)

**Comment by frankrousseau** [comment]
Thank you @LarsCawley for reporting.

**Comment by LarsCawley** [comment]
When I change my timezone to Europe/London, the divisions remain in the same place and the times are changed.  It seems the divisions are being calculated using UTC, rather than local time.  This might be the same thing that is causing [the timesheet issues](https://github.com/cgwire/kitsu/issues/602)?

**Comment by frankrousseau** [comment]
It is probably related yes.

**Comment by frankrousseau** [comment]
Sorry for the delay it will be fixed in next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by LarsCawley** [comment]
It is fixed.  Thank you Frank.
