### ISSUE TITLE
Timesheet calendar locking for artists could be more flexible for different needs

### ISSUE THREAD

**Issue by LarsCawley** [cgwire/kitsu#585]
An idea for something more flexible: 

- a Boolean setting for locking
- an integer for the day of the week when the locking occurs
- an integer for how many days  in the past the locking occurs from

Previous behaviour: False, 0, 0 [ no locking ]
New behaviour: True, 1, 1 [ lock on Monday for Sunday and earlier ]
Our studios preferred behaviour: True, 4, 4 [ lock on Thursday for Sunday and earlier ]

**Comment by ddesmond** [comment]
upvote for customization.

**Comment by LarsCawley** [comment]
Hi Frank, the weekly hours locking went away but it seems to have come back recently?

**Comment by frankrousseau** [comment]
If it went away, it was a bug. We have to keep this feature for our customers.

**Comment by frankrousseau** [comment]
I added an option to remove this locking in the settings page. Does it work for you?

**Comment by frankrousseau** [comment]
I close this due to inactivity.
