### ISSUE TITLE
The total number of hours on the timesheet page does not calculate correctly the sum

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#586]
On the todo page as all permission.

When we enter a number of hours per task, the total number of hours on top of the screen is wrong

![image](https://user-images.githubusercontent.com/42962633/100729380-fe6d8c00-33c8-11eb-9915-20557e9c05dc.png)

**Comment by frankrousseau** [comment]
Can you give the steps to reproduce it?

**Comment by gwendupre** [comment]
I connect to the timesheet, and add hours, even for the first it was wrong, nothing special

**Comment by frankrousseau** [comment]
It doesn't happen all the time. I can't fix the problem without more information.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
