### ISSUE TITLE
When you delete a playlist, you are send to the open-production page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#587]
As a Studio Manager, 

When you delete a playlist (studio or client), you are automatically moved to the "open production" page.

As a supervisor, you stay on the playlist page.

**Comment by frankrousseau** [comment]
I can't reproduce this one. Do you have steps to reproduce it?

**Comment by gwendupre** [comment]
I can't reproduce it either with the 0.12.27, it's fixed, thanks
