### ISSUE TITLE
On the newsfeed page, if we are in "preview only" the calendar is displayed behind a picture

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#590]
On a short film, tv show, feature film

When we go to the newsfeed page and on *add more filter* decide to display preview only. 

If the first preview is a picture, and we want to enter a timeframe, the calendar is displayed behind the picture.

![image](https://user-images.githubusercontent.com/42962633/101059909-168f0800-358f-11eb-8ddc-57ae2b12c98c.png)

If the preview is a video, the calendar is displayed normally on top of the preview.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
