### ISSUE TITLE
possible memory leak when drawing on firefox

### ISSUE THREAD

**Issue by MrFrangipane** [cgwire/kitsu#595]
Hi,

It seems there is a memory leak on firefox when using the drawing module.
Our directors see their RAM fill up rapidly until there is no memory left.

![fuite-memoire-dessin-kistu](https://user-images.githubusercontent.com/5055938/102368285-f9106400-3fba-11eb-963c-fca36d462f74.png)

The memory footprint stops growing when exiting the module, but the memory is not freed.

Thank you very much

**Comment by frankrousseau** [comment]
Sorry for that. We'll investigate this problem. Thank you for reporting.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
