### ISSUE TITLE
Can't go in fullscreen if chrome is not at 100%

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#596]
On a tv show, short, feature film.

On the global page, with the comment panel. When we try to view a preview in fullscreen and if the browser is zoomed (110%, for example), the bottom of the video is missing, and the navigation tools at the bottom of the screen too.

It's working if we are on a playlist on the fly or from the playlist module.

**Comment by frankrousseau** [comment]
Sorry but we won't support zoomed mode. It's too heavy to handle this.
