### ISSUE TITLE
Aspect ratio issues in task detail media display

### ISSUE THREAD

**Issue by fsiddi** [cgwire/kitsu#597]
When displaying a video as part of a task, the thumbnail does not respect the source aspect ratio.

Thumbnail display | After pressing "play"
------------ | -------------
![Screen Shot 2020-12-17 at 15 45 19](https://user-images.githubusercontent.com/451841/102502570-11e24d80-407f-11eb-91f5-7f3cdbd3d8a9.png) | ![Screen Shot 2020-12-17 at 15 45 24](https://user-images.githubusercontent.com/451841/102502577-14dd3e00-407f-11eb-87d3-d86a6e4cb84e.png)

This is the source file used: [sprite_fright_character_ellie_modeling_v12.mp4.zip](https://github.com/cgwire/kitsu/files/5710144/sprite_fright_character_ellie_modeling_v12.mp4.zip)

Let me know if you need any further info.

**Comment by frankrousseau** [comment]
Thank you for the reporting. We are aware of that bug. It's not easy to fix. But we'll have a second look.

**Comment by frankrousseau** [comment]
It comes from ffmpeg when it extracts the first frame. I think there is nothing we can do about it.

**Comment by frankrousseau** [comment]
My bad I may have find the right parameter.

**Comment by frankrousseau** [comment]
Oups no sorry, it doesn't work either...

**Comment by frankrousseau** [comment]
Following a community suggestion, I was able to fix it. Can you try again?
