### ISSUE TITLE
filtre devrait lancer la requette apres 'enter' 

### ISSUE THREAD

**Issue by col-one** [cgwire/kitsu#60]
Le comportement actuel est de lancer la requette de filtre a chaque caractère entre. Ce qui est très long lorsque l'on a plusieurs centaine d'asset. La validation de la recherche ressouderai ce problème.

**Comment by flablog** [comment]
As tu la derniere version ?
c'etait tres tres lent pour moi avant noel, 
mais là, avec 500 assets, ca va tres bien
et j'aime bien le comportement actuel perso (et les graphistes aussi)

**Comment by col-one** [comment]
Hello, 
effectivement j'ai pas teste avec la derniere version, j'ai etait trop presse =] franck m'a prevenu. 
cimer !
