### ISSUE TITLE
On a playlist, the drawings disappeared when the shot is changed

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#601]
On a tv show, short, feature film.

On a playlist, we draw on a specific frame and then change the shot; if we want to go back to the previous shot, all the red dots (and drawings) have disappeared. We need to refresh the page to have them visible again.

**Comment by frankrousseau** [comment]
I cannot reproduce this problem.

**Comment by frankrousseau** [comment]
Do you have an explicit manner to reproduce it?

**Comment by gwendupre** [comment]
I don't have the issue anymore, and I didn't receive any feedback about it again, thanks

**Comment by gwendupre** [comment]
I don't have the issue anymore, and I didn't receive any feedback about it again, thanks
