### ISSUE TITLE
Kitsu timesheet day/week calculations don't match at year end

### ISSUE THREAD

**Issue by LarsCawley** [cgwire/kitsu#602]
I am trying to trouble shoot some incorrect timesheet calculations, where the final week (that starts in 2020 and ends in 2021) for example an artists hours for 2020's week 52 is recorded as 21 hours worked at the 'week' level, but at the 'day' level there is 21 hours logged up until Dec 30th, then 8 hours on Dec 31st as well as the 4 hours from the Jan 2nd seem to be missing from the week calc.

![day_week_calc](https://user-images.githubusercontent.com/21695124/103596162-24ef8b80-4f62-11eb-9802-1406b1c80334.png)

I'm not sure if it is related but, but I include it here because @frankrousseau couldn't replicate our issue. Kitsu/Zou seems to be dividing days by Greenwich Mean Time.  As an example my days logs start at 1pm the previous day, because I am in NZDT.  The host system reports the date correctly.
```
date
Tue 05 Jan 2021 13:18:44 NZDT
```

![image](https://user-images.githubusercontent.com/21695124/103594446-97aa3800-4f5d-11eb-8569-d3f42d95364b.png)

**Comment by frankrousseau** [comment]
Ok @LarsCawley, thank you for the reporting.

**Comment by frankrousseau** [comment]
I close this due to inactivity.
