### ISSUE TITLE
Try to login but get 405

### ISSUE THREAD

**Issue by caksa87** [cgwire/kitsu#604]
I try to login, front-end from this repo, and back-end using docker. But I get response 405 Not Allowed
![image](https://user-images.githubusercontent.com/48079713/103724372-c03a3c80-5006-11eb-971f-6efcf42b47e5.png)
![image](https://user-images.githubusercontent.com/48079713/103724421-d647fd00-5006-11eb-9595-e47cab606731.png)

What I have to do? I try to modify ```vue.config.js``` file in proxy setting, but nothing happens

**Comment by frankrousseau** [comment]
How does your `vue.config` look?

**Comment by caksa87** [comment]
Well, I have modify it
![image](https://user-images.githubusercontent.com/48079713/103765425-bf79c880-504f-11eb-9f22-23668c14c31c.png)

**Comment by caksa87** [comment]
This is the error from console when I redirected to login page
![image](https://user-images.githubusercontent.com/48079713/103767761-c99dc600-5053-11eb-8982-5b6691fe7661.png)


And this is after I click login button
![image](https://user-images.githubusercontent.com/48079713/103768094-6e200800-5054-11eb-809f-ccb746a14272.png)

Because I use the backend from docker, I use the credentials for the Docker image: admin@example.com / mysecretpassword

**Comment by caksa87** [comment]
Lol, just need to follow this https://kitsu.cg-wire.com/development-environment/#prerequisite
Thanks

**Comment by frankrousseau** [comment]
Ok, great!
