### ISSUE TITLE
We're sorry but Kitsu doesn't work properly without JavaScript enabled. Please enable it to continue.

### ISSUE THREAD

**Issue by fananimi** [cgwire/kitsu#607]
I'm trying to set up the local development environment by running the frontend and backend. I already successfully run flask web server, event server, and frontend server.

After that, I tried to log in with credentials through login page. After submitting valid credentials, I found an error says 

*We're sorry but Kitsu doesn't work properly without JavaScript enabled. Please enable it to continue.*

after redirecting to http://localhost:8080/api/auth/authenticated
and  http://localhost:8080/api/data/organisations.

Here my screenshot

![Selection_001](https://user-images.githubusercontent.com/497424/103973047-1642e780-51a1-11eb-9297-f658db952c84.png)

Thanks!

**Comment by frankrousseau** [comment]
Can you show your vue config file again? It seems that authenticated returns the frontend code instead of the backend result.

**Comment by fananimi** [comment]
@frankrousseau , I do not change the default vue config. 

This it's issue is unique, only occurs in my environment. Right now solved by changing chrome on incognito mode.

Thanks!
