### ISSUE TITLE
As a Supervisor my modification on the production schedule is not saved

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#611]
On a TV show, short, feature film.

As a Supervisor, I can modify the production schedule, but my changes are not saved if I change the page.
The start and due date of the task type are not saved either on the Task Type page.

**Comment by frankrousseau** [comment]
I'm not sure that's a good thing. If anyone can create a column, it could become messy.

**Comment by frankrousseau** [comment]
My bad, I answered to the wrong issue. It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
