### ISSUE TITLE
Encrypted password shown on comment api response

### ISSUE THREAD

**Issue by fananimi** [cgwire/kitsu#614]
I found a security issue. After submitting a comment and get back the response from the backend, a `password` returned on response.

![Selection_002](https://user-images.githubusercontent.com/497424/104281385-01878c00-54e0-11eb-943f-9b63f5f150ce.png)

Thanks!

**Comment by frankrousseau** [comment]
It's encrypted but it's still a problem. Thank you for reporting.

**Comment by fananimi** [comment]
Hi @frankrousseau  can I working on it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frankrousseau** [comment]
Yes. These two functions should use the `serialize_safe` method:

https://github.com/cgwire/zou/blob/master/zou/app/services/persons_service.py#L81
https://github.com/cgwire/zou/blob/master/zou/app/services/persons_service.py#L118

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by frankrousseau** [comment]
I close this due to inactivity.
