### ISSUE TITLE
On a playlist, if there are multiple pictures on several version, only the pictures from the latest version are displayed

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#615]
On a short, TV Show, Feature film.

On a task, we upload several pictures for each version (for example 4 pictures for the V1, and 5 pictures for the V2).

We create a playlist, the V2 is selected (as expected), we can navigate through all the pictures, everything is displayed as expected.
But, when we switch to the V1, the first picture is displayed correctly, but if we want to navigate through all the pictures of the V1, we realize that, except for the first picture, all the others are from the V2.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
