### ISSUE TITLE
The tasks are not displayed in the pipeline order on the detail page of an asset or a shot.

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#618]
On a TV show, Short, Feature film.

When we go to the detail page of an asset or a shot, we realize the task list is not displayed in the correct order as defined on the task type page.

![detailsasset_task](https://user-images.githubusercontent.com/42962633/104466415-81335a80-55b5-11eb-81e8-1172414c316a.PNG)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks!
