### ISSUE TITLE
When editing an asset, the type displayed is wrong

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#62]
On a list of assets, if I click the edit button, the type displayed is not correct : 

![image](https://user-images.githubusercontent.com/870195/35093701-6d7e7084-fc43-11e7-90a9-cde2362fc403.png)
As you can see, the type is "Props"
But in the edit popup, it's "Chars"
![image](https://user-images.githubusercontent.com/870195/35093752-924a0f5e-fc43-11e7-9d1c-21dfccc5dc3f.png)

**Comment by frankrousseau** [comment]
Thank you for reporting. I think it's easy to fix. I will probably solve this for the next release.

**Comment by frankrousseau** [comment]
It should be fixed can you confirm?
