### ISSUE TITLE
When we enter a start and a due date on the task type page and leave the selection, the start date appears as empty.

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#620]
On a TV show, Short, Feature film.

On the task page, when we enter a start and a due date on the task tab, only the due date remains. The start date appears as empty.
To make the start day stay, we have to enter an estimation, then a start date. The start day disappears again, but the estimation and the due date remains.
If we add one more time the start date, it will stay, and the due date will be calculated with the estimation and the start date.

If we enter first the estimation, then start date, due date, and press escape, all the data is displayed. 

If we use the Gantt diagram on the schedule tab, we don't have the issue.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
