### ISSUE TITLE
On the task type page, selecting too many elements freeze Kitsu

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#624]
On a TV show, short, feature films.

On the task type page of the shots or assets. If you select several elements to batch edit the start date/due date or estimation, kitsu will freeze

When we select the first element, we have to wait for the video or picture to load and then select another element. It will work.

But if we want to select several elements simultaneously, Kitsu freeze and the browser displays an error message saying it takes too much time to answer.

Refreshing the page doesn't solve the issue.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
I still have the issue, and I only selected 8 tasks

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
