### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#63]
Is it possible to add a favicon to kitsu ? Like the fox logo ? So it's easier to spot kitsu tabs ?  :)

**Comment by frankrousseau** [comment]
Ok. It's definitely missing. I will add it to the next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you confirm?

**Comment by flablog** [comment]
![image](https://user-images.githubusercontent.com/870195/36094239-b6e6d5fa-0fed-11e8-892c-0429d4ee18a6.png)
