### ISSUE TITLE
Can't read any preview

### ISSUE THREAD

**Issue by aMondelin** [cgwire/kitsu#630]
Hello,

We can't read any preview uploaded today on Kitsu. Previews are uploaded manually or with `gazu.task.add_preview()`

We have a loading screen on preview, but we can't read them

Thanks

**Comment by aMondelin** [comment]
I closed because previews finally appeared after a long time. Upload seems to be lagguy today

**Comment by frankrousseau** [comment]
I think it's more related to the fact that normalization is queued. The upload goes faster but the processing on the server is handled separately. So videos at the end of the queue seems to be very long to process.

**Comment by aMondelin** [comment]
Thank you for your answer and details
