### ISSUE TITLE
Can't delete custom status

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#631]
On TV-Show, Short, Feature Film

I have created a status, but I'm not using it anymore. I have checked in the newsfeed if the status is not appearing.
But when I want to delete it, I don't have any error message, but the status is still here.

![image](https://user-images.githubusercontent.com/42962633/106464711-4e380480-6499-11eb-85a9-06721a1213c2.png)

**Comment by frankrousseau** [comment]
They can now be archived.
