### ISSUE TITLE
Help With Zou Email Failure?

### ISSUE THREAD

**Issue by petertimberlake** [cgwire/kitsu#634]
Hi!

We've successfully set up Kitsu / Zou on our Ubuntu server. Everything seems to be working well except for email. When I attempt to email other users to invite them to my organization, I receive this error in the kitsu web UI:

An error occured while sending the invitation
(occurred is spelled wrong in the error :) )

here is my /etc/systemd/system/zou.service file with usernames, passwords, and keys omitted - We've modified this file restarted the zou / zou-events / nginx services many times without success 

```
[Unit]
Description=Gunicorn instance to serve the Zou API
After=network.target

[Service]
User=zou
Group=www-data
WorkingDirectory=/opt/zou
# Append DB_USERNAME=username DB_HOST=server when default values aren't used
# ffmpeg must be in PATH
Environment="DB_PASSWORD=xxxxxxxxx"
Environment="SECRET_KEY=xxxxxxxxxx"
Environment="PATH=/opt/zou/zouenv/bin:/usr/bin"
Environment="PREVIEW_FOLDER=/opt/zou/previews"
Environment="MAIL_SERVER=smtp.gmail.com"
Environment="MAIL_PORT=465"
Environment="MAIL_USERNAME=xxxxx@gmail.com"
Environment="MAIL_PASSWORD=xxxxxxxxx"
Environment="MAIL_USE_SSL=True"
ExecStart=/opt/zou/zouenv/bin/gunicorn  -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app

[Install]
WantedBy=multi-user.target
```

I don't think the problem is actually with this file, but I can't figure out where else to look. Thank you in advance.

**Comment by ddesmond** [comment]
checked other issues ?
https://github.com/cgwire/kitsu/issues?q=is%3Aissue+is%3Aclosed+email
maybe there is a hint what is "wrong"...

**Comment by petertimberlake** [comment]
Yes I've read through everything here...I think the problem has to do with my installation, not my zou.service file, but I welcome any help on diagnosing.

**Comment by frankrousseau** [comment]
Are you sure that you have an up and running email server using SSL to communicate with?

**Comment by petertimberlake** [comment]
We solved this issue - this is probably a fairly juvenile mistake but so many of us are artists 1st and sysadmins 2nd (or 3rd) - the solution was to add this line to our zou.service file.

`Environment="DOMAIN_NAME=YOURDOMAIN.com"`

 If I'm not mistaken, I think you only need to do this if you've set up your kitsu under a public domain, like kitsu.vfxstudio.com ?

we also set up an additional app within gmail so that we don't need to use our email login password in the service file. Here's that article:
https://support.google.com/accounts/answer/185833

**Comment by frankrousseau** [comment]
A yes I forgot that one. Thank you for your feedback.

**Comment by bleedblue28** [comment]
Hi, I'm getting the same error described in this post. Did you ever find a resolution to this problem?
