### ISSUE TITLE
The timesheet page of the artist is empty or lacking some information

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#643]
As an artist, when I check the timesheet page with the global menu, the time spent is not displaying properly.
For some people, to timesheet page is empty; for others, days filled are missing.

![image](https://user-images.githubusercontent.com/42962633/109314008-1aa68b00-7849-11eb-821c-efbc8adb5135.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
