### ISSUE TITLE
Date ranges broken in project settings

### ISSUE THREAD

**Issue by tobkum** [cgwire/kitsu#647]
When trying to set start/end dates for a project, I get this:

![image](https://user-images.githubusercontent.com/16955378/109958368-70b27d00-7ce6-11eb-8842-09ae91c97c05.png)

**Comment by frankrousseau** [comment]
Thank you for reporting. The problem will be fixed in next release.

**Comment by tobkum** [comment]
I don't see an update?
![image](https://user-images.githubusercontent.com/16955378/110456631-16d8fb00-80ca-11eb-8c51-b367364e9da3.png)

**Comment by frankrousseau** [comment]
Sorry it was not released. You can update it and try again.

**Comment by tobkum** [comment]
Sorry for the delay - works fine now, thanks!
