### ISSUE TITLE
There is an error when preview the image  in the 12.53 new version

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#648]
![image](https://user-images.githubusercontent.com/48669854/110090185-f52dfa00-7dd1-11eb-8140-42dbaaecd84d.png)
I can't open the image in the comment area,when i click on the image icon. It jump to another webpage and display:
**{"error":true,"message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}**

**Comment by frankrousseau** [comment]
The problem seems related to your installation. Are you sure that you didn't change the access rights of the temp folder?

**Comment by DuanXu-anim** [comment]
yeah，I didn't change any rights,and the issue happened when I updated the new version



发自我的iPhone


------------------ Original ------------------

**Comment by frankrousseau** [comment]
Does it happen with every picture?

**Comment by DuanXu-anim** [comment]
yes,every picture ,and I found these picture were uploaded in server successfully .it should be a bug

**Comment by DuanXu-anim** [comment]
no ,just pictures

**Comment by frankrousseau** [comment]
I think you should check the rights of the `/opt/zou` folder and its subdirectories.
