### ISSUE TITLE
Newsfeed interface data disappeared

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#649]
Afer i updated the 12.53 version ,I found the Newsfeed data is disappeared ,there is no feeds show up
![image](https://user-images.githubusercontent.com/48669854/110284927-75946b00-801d-11eb-960f-40bd5e310078.png)

**Comment by frankrousseau** [comment]
I looks like the url is broken. Can you go back to project list, then refresh the page and navigation to the newsfeed again?

**Comment by DuanXu-anim** [comment]
yeah , i go back to the project list and try it many times,and i still can't access the newsfeed. what do i do the next step

**Comment by DuanXu-anim** [comment]
can  I go back version 12.45,because i found the problem happened when I updated the latest version

**Comment by frankrousseau** [comment]
Did you ran the database update?

**Comment by DuanXu-anim** [comment]
Not yet,should I need to do?

**Comment by frankrousseau** [comment]
Yes, of course after every update, the upgrade command must be run.

**Comment by DuanXu-anim** [comment]
The issue is fixed, thanks
