### ISSUE TITLE
Able to access restricted pages via URL

### ISSUE THREAD

**Issue by caksa87** [cgwire/kitsu#651]
I login as `Artist` but still able access pages that I shouldn't have access to. For example `/people` that should be accessible by `Admin`
![image](https://user-images.githubusercontent.com/48079713/110421066-4b9b8100-80cf-11eb-8b7f-5c9f70c6091a.png)

**Comment by frankrousseau** [comment]
It's true but as you can notice you don't see sensitive information. Artists need the user list to display comments and assignations properly.

**Comment by frankrousseau** [comment]
I let the issue open, because a friendly message would be better than a half empty screen.

**Comment by frankrousseau** [comment]
The related pages return a 404 error now.
