### ISSUE TITLE
Empty Shots list after 'Back' button is being clicked in Shots detailed view

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#653]
I stuck with a strange behavior of Kitsu in Shots section: it shows empty Shots list if I use Back button from detailed Shot's view. 
I updated to latest build (Kitsu 0.12.57) but it didn't help (and I have enabled Jobs queue if that is important).

Test scenario:
1. Visit Shots list and Click any Shot to enter Detailed view.
![image](https://user-images.githubusercontent.com/13551109/111121853-3cf51400-857e-11eb-993c-77fe78b6d251.png)

2.  Click Back button to get back to Shot list again
![image](https://user-images.githubusercontent.com/13551109/111121054-3b771c00-857d-11eb-8b00-fb620a9bcfc0.png)

3. Getting to Shots list with no Shots displayed with spinner loading:
![image](https://user-images.githubusercontent.com/13551109/111121398-a4f72a80-857d-11eb-88c2-75acd0554c00.png)

It is also worth noting that on Step 1 the URL contains trailing `?search=` e.g. `https://<domain>/productions/e70e98da-ac0d-47c9-a19a-d7d7cc2c16f3/shots?search=` but on step 3 it's just `https://<domain>/productions/e70e98da-ac0d-47c9-a19a-d7d7cc2c16f3/shots`

**Comment by frankrousseau** [comment]
Ok thank you, we will have a look at this bug.

**Comment by keshon** [comment]
I did extra tests about this issue and noticed that the only way this bug **is not** happening when:
- Production is for `TV Show`
- Sequence and Shot are created under default Episode `E01` 

So under these conditions it is possible to see shots and sequences list after clicking Back button from any shot but even then there are few things:
- Episode dropdown menu disappears
- Dev Console is full of errors.

**Comment by frankrousseau** [comment]
Ok thank you. It will help to fix this issue.

**Comment by keshon** [comment]
I don't observe the issue anymore on Kitsu 0.12.58 so I'm closing it. Browser clearing cache is necessary.
