### ISSUE TITLE
Enabling Job Queue somehow breaks S3 integration for mp4 files preview upload

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#654]
I did setup Jobs Queue according to official [documentation ](https://zou.cg-wire.com/jobs/):
- create zou-jobs.service for systemd
- add Env variable "ENABLE_JOB_QUEUE" with value True to (main) zou.service

The issue is that this actions breaks S3 integration for uploading mp4 files as a preview inside tasks. If I try to upload mp4 file Kitsu stores it in local `preview` folder while having settings for S3 storage - this leads to a black screen in Player after uploading and reconverting video file.

The gunicorn log says the following:
```
[2021-03-16 09:37:22,010] ERROR in resources: Picture file was not found for: 27cc6477-462c-41d5-ae5c-93cf55d025b6
[2021-03-16 09:37:22,047] ERROR in resources: Movie file was not found for: 27cc6477-462c-41d5-ae5c-93cf55d025b6
[2021-03-16 09:37:22,094] ERROR in resources: Picture file was not found for: 27cc6477-462c-41d5-ae5c-93cf55d025b6
```

**Comment by frankrousseau** [comment]
Ok thank you. S3 integration is not our priority, but we will have a look at this bug.

**Comment by keshon** [comment]
I tested it on recent versions of Kitsu. The bug still persists

**Comment by frankrousseau** [comment]
Did you set up the environment variable properly in the `zou-rq` service?

**Comment by keshon** [comment]
I feel myself stupid as I didn't realize that S3 Storage settings should be in zou-rq and not in zou if I want to use Job Queue.
In my defense I say documentation should explicitly cover this step as I would never guess that.

**Comment by frankrousseau** [comment]
Both services need this configuration. Can you update the documentation to mention this? You're right it's definitely missing.
