### ISSUE TITLE
Latest upload movie can't display

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/kitsu#655]
![image](https://user-images.githubusercontent.com/48669854/111408997-13b8bd00-8711-11eb-8ed4-6130ba5c7f07.png)

**Comment by DuanXu-anim** [comment]
I can find the movie of zou,it can display normally when I download from zou

**Comment by DuanXu-anim** [comment]
the version of kitsu and zou are both 0.12.53

**Comment by DuanXu-anim** [comment]
How could I roll back previous version?

**Comment by frankrousseau** [comment]
It looks like it's broken. Can you delete it and reupload it (you should update Kitsu too).

Kitsu is not designed to rollback versions. We always move forward.
