### ISSUE TITLE
When deleting an"empty" shot, the shot is deleted but it should only be crossed

### ISSUE THREAD

**Issue by NeirdaP** [cgwire/kitsu#656]
When I delete a shot, the documentation says it doesn't really delete it but that the "shot appears as crossed and can be restored".

Actually, when a shot has no task in it, the shot is really deleted. 

I don't know if this is a bug or a feature and I wonder if that should appear in the documentation. :)

![kitsu_no_restore](https://user-images.githubusercontent.com/20859383/111474390-52a83c00-872c-11eb-93a9-992e3212ddea.gif)

**Comment by frankrousseau** [comment]
The idea is that you don't have data to lose when the shot is empty. So, it is faster to delete it fully. But you're right the message and the documentation are not clear about this behaviour.

**Comment by frankrousseau** [comment]
I prefer to close this one. If you want to change this please submit a feature request on https://cgwire.canny.io/ .
