### ISSUE TITLE
You can't delete a start date / due date on a task type page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#657]
On a TV-show, short and feature film. As a Studio Manager and Supervisor.

Once an estimation, start date, or due date is set, you can't delete them.
If you click on the cross on top of the case, it won't empty it. You can modify the date or estimation, but you can't empty it.

**Comment by keshon** [comment]
It's also not possible to change Estimate field back to 0 again if it was (accidently) set on.

**Comment by frankrousseau** [comment]
it should be fixed. Can you try again?

@keshon can you open a different issue for the problem you mentioned?

**Comment by keshon** [comment]
> it should be fixed. Can you try again?
> 
> @keshon can you open a different issue for the problem you mentioned?

I think it is the same issue. @gwendupre mentioned that it is not possible to delete Estimation field. Setting this field to 0 is essentially same thing as "delete" procedure. @frankrousseau  I still can open a separate issue if you say so.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!

**Comment by keshon** [comment]
I also confirm (sorry for late reply)
