### ISSUE TITLE
Change status action not working on the shots page going back to it with an active filter

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#66]
When you set a filter on the shot page
Go to any other page (assets for example)
And go back to the shot page, where the filter is still active (which is good)
if you select tasks and try to batch change the status with the action in the menu bar, it deselect the tasks and nothing happends 

This doesn't look to be an issue on the asset page (I was not able to reproduce the bug)

**Comment by frankrousseau** [comment]
Ok thanks, I will try to reproduce it then fix next week.

**Comment by frankrousseau** [comment]
Can you still reproduce this bug?
