### ISSUE TITLE
When downloading pictures from a playlist with the download.zip, they are compressed compared to the original file

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#661]
On a Tv Show, Short and Feature film.

When we download the assets preview pictures from a playlist, we realize the pictures are compressed.

When we download the preview file directly from the comment section, it seems like the original file.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
