### ISSUE TITLE
When uploading pictures as an attachment into a comment, they are displayed in random order

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#662]
On a Tv show, short, feature film.

When we want to upload several pictures as attachments to a comment, they seem to be displayed in random order. If, for example, my picture is named 01, 02, 03, they will be displayed, 01, 03, 02. 
I have selected in batch or one by one to respect the order on the picker window, but it doesn't change the display order on the comment pannel.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
