### ISSUE TITLE
0.12.57 build - Task Thread & Playlist playback of clips broken.

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#669]
Updated Kitsu to the latest build (0.12.57) , playback of clips previously submitted to Kitsu (and working), play button in the Task status thread no longer plays the clip. - only first frame is displayed.

To play the clip, you have to enter full-screen mode. Again, play button doesn't work, but hitting Space bar plays the clip. Exiting full screen results in any graphics used in the thread panel being blacked out. Need to refresh the page.

Playlists, however are also totally broken - can't view movie clips (just black frame), only images. Pressing Space has no effect.

**Comment by PeteDraper** [comment]
note: this issue is also present in new clips uploaded, not just legacy clips. Tested on windows and osx chrome to check if it was a platform issue - same issues persist..

**Comment by frankrousseau** [comment]
It seems related to recent changes. But there is no reason to have this behavior. Can you check the permission rights of your preview and temp folders?

**Comment by PeteDraper** [comment]
Permissions should be ok - it was working perfectly fine before updating to the latest build. The only thing I did was to run the “update kitsu” section that’s instructed in the installation instructions which I’ve done a few times before. Haven’t updated in about 3 weeks so it’s possibly the latest one or something in between which has caused this.

**Comment by frankrousseau** [comment]
Can you show us your error logs?

**Comment by PeteDraper** [comment]
I’ll check in the morning.
