### ISSUE TITLE
When editing a Task Status, the Is Reviewable is not set well the first time

### ISSUE THREAD

**Issue by flablog** [cgwire/kitsu#67]
If you go to that page to set a task reviewable parameter
if you set it to "yes" and save, the value is set to False.
Then you can edit it again and set it to True

This is also true when creating a new status, without changing the Is Reviewable (to No, or to no and then to yes) it's set to False, even if "Yes" was displayed.

**Comment by frankrousseau** [comment]
Thank you for reporting, it probably doesn't deal well with null values.
