### ISSUE TITLE
Tasks duplicated in schedule after upgrading into a new version 

### ISSUE THREAD

**Issue by Chantology** [cgwire/kitsu#672]
We updated to Kitsu V0.12.57 and since this release the tasks in the schedule are doubled or tripled. 

We are not sure if this is connected to the new feature to add beginning and end date in the settings. It was turned on at some point but I deleted those in order to try to get rid of the additional tasks in the schedule but it didn't make a difference.

![Screenshot 2021-03-26 184705](https://user-images.githubusercontent.com/50327807/112672358-aec53b80-8e63-11eb-9a99-41a1116cb04f.png)

**Comment by frankrousseau** [comment]
We fixed the problem to avoid that it happens again. Unfortunately, you have to clean the database yourself with Gazu. Do you need any help with this?

**Comment by Chantology** [comment]
Hi Frank, thanks a lot for the update! We will try to clean the database and if any problems occur I can also post a message in the forum.

**Comment by frankrousseau** [comment]
Great! thank you! I close the issue. Feel free to open it if it happens again.

The objects you must clean are schedule-items. The duplicated ones have an empty value for `object_id` which means they are dedicated to the project.

You can find the items there: `http://kitsu.url/api/data/schedule-items`.

**Comment by keshon** [comment]
> The duplicated ones have an empty value for `object_id` which means they are dedicated to the project.

This this mean that any record in `http://kitsu.url/api/data/schedule-items` having empty `object_id` considered as obsolete and can be safely removed?

**Comment by frankrousseau** [comment]
No no, they are useful. But they were the only ones to be duplicated.
