### ISSUE TITLE
If you change the version of the main preview, it will restart the compared video's timecode.

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#674]
On a tv show, feature film, short.

On the playlist module, with the side-by-side activated.
If you change the version of the main preview, it will restart the compared video's timecode.

So when you go back to the playing, the videos are not synched anymore.

**Comment by frankrousseau** [comment]
I did some tests again. And it seems that it doesn't restart anything anymore. So do you think it's working now?

**Comment by gwendupre** [comment]
it's fixed, thanks!
