### ISSUE TITLE
Old comments loose timestamps and get dates

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#675]
Current UX decision hides timestamps for old comments (that are more than 1 day old). Why can't we see timestamp and datetime at the same time? Sometimes it's necessary to know exactly what date time was used for a particular task comment.
There is a lot of space for that simple feature as task bar can be extended:

![image](https://user-images.githubusercontent.com/13551109/113552749-431b6500-95ff-11eb-98b8-37b656d84f8d.png)

**Comment by frankrousseau** [comment]
Helo @keshon, thank you for your question.
You can just put your mouse over the date and see the full date as a tooltip.

**Comment by keshon** [comment]
Hi @frankrousseau, thank you for explanation! I didn't notice there is a tooltip (it has a delay - easy to miss).
I close the question but honestly Kitsu would benefit of using a popovers with no time delays (VueJS has some like https://www.npmjs.com/package/vue-js-popover).
Thanks again!
