### ISSUE TITLE
We can't change the length of a task type bar on the schedule if it's a one-day duration

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#676]
On a tv show, short feature film.

On the production schedule page. If the length of a task type is only 1 day, we can't grab a side of the bar to extend his duration.
The grab only makes you move around in the schedule.

To go around the issue, we can unfold the task type and change the duration of the asset type/sequence to force the global bar's length.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks
