### ISSUE TITLE
New assets/shots don't display on the task-type page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#680]
On a tv-show, short, feature film.

On a production with assets, shots, and task type.
If you create the assets/shots and go to a task-type page, everything is well displayed.

But if you create later assets/shots and go back to a task type page, the newly created element don't display on the task type page.
You have to refresh the task-type page to display the new element.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
I'm sorry, but the newly created element doesn't appear in the task type page without a refresh.

**Comment by frankrousseau** [comment]
Are you sure? Can you try again?

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?
