### ISSUE TITLE
The sequence page is stuck on the green loading animation.

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#681]
On a tv-show, short, feature film.

From any page, if you go to the "sequence stats" page, the green loading animation is here.
Even if you refresh the page (F5 or Ctrl F5), nothing happens; the green loading animation is still here.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
