### ISSUE TITLE
When we want to add more sequences/shots to a production, the list is empty

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#682]
on a short production

On a production with already sequences and shots.
If we want to add more sequences/shots, and we click on the "+ create shots" button, the list of the already created sequences and shots appears has empty. 

After a refresh, if we click again on the "+ create shots", the sequences and shots are displayed, but it's an old name for the displayed sequence. It's not the actual name of the sequence.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
