### ISSUE TITLE
Cancel button not working on modal window when deleting a production

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#684]
I noticed that it's not possible to click Cancel button modal window when deleting a production.
![image](https://user-images.githubusercontent.com/13551109/114364137-c4d03d00-9b81-11eb-91d9-e58de08a209f.png)

**Comment by frankrousseau** [comment]
Hello @keshon, you have to type the name of the production first in the text box. It's to ensure that you know what you are doing.

**Comment by keshon** [comment]
I 

> Hello @keshon, you have to type the name of the production first in the text box. It's to ensure that you know what you are doing.

I agree that this rule is mandatory for Confirmation. But Cancel action should be accessible any time without any restrictions as it does not change anything but close modal window

**Comment by keshon** [comment]
I have a feeling that Cancel button is broken because even if I fill the production name Cancel button still ignores my clicking on it

**Comment by frankrousseau** [comment]
A sorry, I misread. I thought you were talking about the confirm button.
