### ISSUE TITLE
The modal dialog of cancellation says 'remove'

### ISSUE THREAD

**Issue by mathbou** [cgwire/kitsu#685]
When canceling a shot or an asset, the message in the dialog implies that the entity will be erased. 

![image](https://user-images.githubusercontent.com/13415583/114433221-dd604780-9bc1-11eb-81b2-21add52ddfe1.png)

**Comment by frankrousseau** [comment]
Thank you for reporting, it will be fixed in the next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
