### ISSUE TITLE
Kitsu Player counter does not respect mixed content

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#687]
If I try to upload to preview mixed content like video and images the player counter does not show total number of elements properly. 
For example if I upload 1 video file and 4 images at the same time the counter in Kitsu Player will show "1" for video omitting  total number of elements (but "2/5" for second image, "3/5" and so on - which is correct behavior).
Here is a gif demonstrating the issue
![issue](https://user-images.githubusercontent.com/13551109/115526722-01461c00-a299-11eb-8e3b-122d5b3b0308.gif)

**Comment by frankrousseau** [comment]
Thank you for reporting. But it's a tough question. Because videos don't offer the same space as pictures.

**Comment by keshon** [comment]
if screen space is an issue then it is necessary to hide some action elements under dropdown menu or make a global toggle switch (or even rethink player UI in general). 

Because such scenarios can greatly affect user experience in a bad way. The simplest way for now is just forbid Kitsu upload mixed content at the same time (it's better to split content than 'loose' it)

**Comment by frankrousseau** [comment]
You don't lose anything, it's just that you have less information when you show a video. We do not want to remove access to mix content upload. There is nothing harmful here. We can improve it but there is no big issue with it.

**Comment by keshon** [comment]
The issue (as I see it) is that if I upload mixed content for an assignee - he might not be aware of that and don't notice that images followed by the video in my example. We had this real life scenario in our studio. Anyway I just made a report :) Thanks @frankrousseau for your patience!

**Comment by frankrousseau** [comment]
If there is only one video, there is no counter displayed. So, the artist can guess that he has several content to see.

**Comment by frankrousseau** [comment]
I prefer to close this issue. Please open a feature request on Canny if you want to change this.

**Comment by keshon** [comment]
Yeah I agree with that. Thank you !
