### ISSUE TITLE
Broken filtering with recent update

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#691]
After recent update (to Kitsu 0.12.66) filtering by status stopped working
![broken_filtering](https://user-images.githubusercontent.com/13551109/116207536-a99c2a80-a748-11eb-9c07-4ac60ba51145.gif)

**Comment by frankrousseau** [comment]
Yes, this version is very unstable. Please, wait for the next one.

**Comment by keshon** [comment]
the issue is closed (but I found a new one.. wait for it).
