### ISSUE TITLE
Broken selection array for Custom actions

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#692]
It looks like Kitsu has UI bug that prevents proper update of selection array that is being send by Custom Action.

![selection_not_updating](https://user-images.githubusercontent.com/13551109/116256718-1d0b5f80-a77c-11eb-95f2-aeaec7d60834.gif)
If I switch between two different tasks back and forth - the `selection` array that sends to Custom Action does not update according to my current selection. The Custom Action will send the selection of the very first selected task right after you load the webpage.

The only way to update data for `selection` array is to intentionally deselect one task and select another which is a bit annoying and breaks any use for custom action integrations (Telegram bot in our case).

**Comment by frankrousseau** [comment]
Sorry, but I can't reproduce this one.

**Comment by keshon** [comment]
Just in case I made a better representation of the problem. 
Could you confirm that on your side every next task you select sends corresponding selection to Custom Action and you don't have to deselect and reselect the task?
![Animation](https://user-images.githubusercontent.com/13551109/117330532-75d6a880-ae9e-11eb-99ed-c1f1d2704a0d.gif)

**Comment by frankrousseau** [comment]
Does it happen only with custom actions or with everything (status change, assignation)?

**Comment by keshon** [comment]
It only affects Custom actions. Status change and assignations work buttery smooth.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by keshon** [comment]
I cannot test it anymore but will close the issue. Thanks!
