### ISSUE TITLE
Empty timesheets for Artist

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#694]
I noticed there is an empty tab for Artists where I should check workhours spent for particular tasks.
![Screenshot 2021-04-30 165022](https://user-images.githubusercontent.com/13551109/116704521-2b53b880-a9d4-11eb-9096-ab09b4301bb2.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by keshon** [comment]
It is fixed indeed, thanks @frankrousseau !
