### ISSUE TITLE
The Delete Tasks function on multiple tasks only deletes the first selected task for Shots

### ISSUE THREAD

**Issue by angel-k** [cgwire/kitsu#702]
On Kitsu 0.12.72, when I select multiple tasks in the Shots page and run the Delete Tasks function, only the first one is deleted and the function runs endlessly.
No problem for the assets though.
On my browser console, I get an error:
"Uncaught TypeError: i.remove is not a function" in shots.js

**Comment by frankrousseau** [comment]
Hi @angel-k, thank you for the reporting. We think that it will be fixed in the next release.

**Comment by frankrousseau** [comment]
@angel-k It should be fixed. Can you try again?

**Comment by angel-k** [comment]
I confirm that the problem no longer appears on Kitsu 0.12.78! Thank you @frankrousseau !
