### ISSUE TITLE
Assets Sort by resets after asset edition

### ISSUE THREAD

**Issue by angel-k** [cgwire/kitsu#703]
On Kitsu 0.12.72, the assets "Sort by" (with the metadata) resets after any asset modification whereas the sorting is supposed to be still active ("Sort by xxx" text in the top left corner is still present with the cross to remove it)
This problem does not happen for shots

**Comment by frankrousseau** [comment]
Thank you for reporting @angel-k, it will be fixed in next release.

**Comment by angel-k** [comment]
I confirm that the problem no longer appears on Kitsu 0.12.78! Thank you @frankrousseau !
