### ISSUE TITLE
Unable to switch language to Chinese

### ISSUE THREAD

**Issue by fyplclfkr** [cgwire/kitsu#706]
When I set the language to Chinese, English is still displayed
Then I opened the browser console and found that there were no Chinese files in locales
![unknown](https://user-images.githubusercontent.com/74193811/119641565-64a10c00-be4c-11eb-80b6-fb178b32fd2b.png)

**Comment by frankrousseau** [comment]
Hello @fyplclfkr,  thank you for reporting this bug. It should be fixed now. Can you confirm?

**Comment by fyplclfkr** [comment]
> Hello @fyplclfkr, thank you for reporting this bug. It should be fixed now. Can you confirm?

Yes, it can display Chinese correctly now. Thank you very much

**Comment by frankrousseau** [comment]
Great! Thank you
