### ISSUE TITLE
Can't assign tasks on 'Surface Pro laptops'

### ISSUE THREAD

**Issue by erikvanschaaik** [cgwire/kitsu#711]
It is impossible to assign a task. The artists-dropdown list does not work. 

See the dropdown-malfunction in this clip:
https://vimeo.com/560357658/87a870d4d3

This problem occurs on a Windows Surface Pro laptop (with tablet-mode off). I got the same issue on two different **Surface pro** laptops. **Mac** works fine, **iPad** works also fine. 

Fresh installs of the newest Chrome and Firefox don't fix the problem. 

Typing a name in the box, then pressing 'down arrow key' to select a person, then pressing 'enter' also doesn't work. When I try that, the dropdown disappears for good (until I refresh the browser).

The source code of my browser indicates that there are some problems with the vue-websocket. 

Thanks, kind regards.
Erik

**Comment by frankrousseau** [comment]
Ok thank you for reporting!

**Comment by erikvanschaaik** [comment]
Update on the drop-down-list-problem with Surface Pro:
Everything works just fine when using **pen** or **touch**. However, it will not work with the **trackpad**. 
So it is not really a problem anymore.
