### ISSUE TITLE
Fullscreen doesn't show loop button it not first extended

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#713]
Hi! If I full-screen from a small preview window the loop-button isn't there but if I first expand the preview and then full-screen it the loop button is there.
See attached images for better understanding :)
![1](https://user-images.githubusercontent.com/49758407/121338564-e9485b80-c91d-11eb-877b-b920e62a2f4f.jpg)
![2](https://user-images.githubusercontent.com/49758407/121338569-ea798880-c91d-11eb-8c53-55b832811c1b.jpg)
![3](https://user-images.githubusercontent.com/49758407/121338571-eb121f00-c91d-11eb-9a30-3376580f295c.jpg)
![4](https://user-images.githubusercontent.com/49758407/121338573-eb121f00-c91d-11eb-80aa-3f44cecf6d38.jpg)

**Comment by frankrousseau** [comment]
Thank you for the report!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
