### ISSUE TITLE
Task Selection not change in run custom action

### ISSUE THREAD

**Issue by dinhthang1987** [cgwire/kitsu#716]
When select task for run custom action --> and continue select another task --> task old select first sill keep value 
![image](https://user-images.githubusercontent.com/44437492/121859538-01efb180-cd22-11eb-9707-f144816daf2c.png)

**Comment by frankrousseau** [comment]
We made a fix recently related to custom actions. Dose your bug still occurs?

**Comment by dinhthang1987** [comment]
yes, bug still occours

**Comment by dinhthang1987** [comment]
problem coming from when select 1 task

**Comment by dinhthang1987** [comment]
I had checked problem on code --> problem from variable this.selectedTaskIds
![image](https://user-images.githubusercontent.com/44437492/123028060-03e3ff80-d409-11eb-86c0-14bc2c160e80.png)
And I try change to --> Problem is resolved
![image](https://user-images.githubusercontent.com/44437492/123028216-43125080-d409-11eb-84a1-4a1fae667993.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by dinhthang1987** [comment]
Yes it fixed after update new version. Thanks you so much

**Comment by frankrousseau** [comment]
It seems there is still a bug with deselection. I will publish a new version soon.
