### ISSUE TITLE
Switch from node-sass to sass

### ISSUE THREAD

**Issue by fsiddi** [cgwire/kitsu#719]
Due to the [deprecation of the node-sass package](https://github.com/nodejs/node-gyp/issues/2384) in favor of [Dart Sass](https://sass-lang.com/dart-sass), it's currently not possible to build Kitsu with a recent version of Node. 

I tried updating `package.json` to use Dart Sass (simply `sass`), but could not do it. I suspect other packages still depend on node-sass and should be updated first. I'm available to spend some time on this, but since it's not a fun task I'd like to have approval before continuing.

**Comment by frankrousseau** [comment]
Hello @fsiddi,
We can fix it but if you want to help you're welcome! Can you tell which version of Node.js doesn't work with the current Kitsu build?

**Comment by frankrousseau** [comment]
I finally fixed this. It seems that there are still issues with the webpack version. But the `sass` thing should be ok.

**Comment by frankrousseau** [comment]
NB: Our goal is to migrate to Vue3 and Vite at some point (still complex because of our dependencies). Vite doesn't rely on Babel, so it should make things cleaner.

**Comment by fsiddi** [comment]
Apologies for not following up on this. Thank you for addressing the issue! 
I am still unable to build Kitsu, but it's due to another error, so I'll report it in a separate task.
