### ISSUE TITLE
Unable to Upload Videos

### ISSUE THREAD

**Issue by awils27** [cgwire/kitsu#723]
We have been using Kitsu and Zou without problem on google cloud from the past 2 months or so but as of today we cannot upload videos. We simply get, "The Preview is Broken." in the video window. Existing videos work just fine. The problem isn't limited to a single codec or file extension as it does it for mp4 mov h.264 and prores. Images still work just fine. It's deployed using google cloud on debain.

The error log shows this repeated a lot but it doesn't match the timestamp of any attempted video uploads:

```
[2021-07-26 10:25:57,357] ERROR in resources: Picture file was not found for: 4a63a271-2a27-4ca1-8fec-322ea001d664
[2021-07-26 10:25:57,366] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/pr$
[2021-07-26 10:25:57,366] ERROR in resources: Picture file was not found for: 4a63a271-2a27-4ca1-8fec-322ea001d664
[2021-07-26 10:25:57,378] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/movies/lowd$
[2021-07-26 10:25:57,378] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/movies/prev$
```

There is also several errors with file paths in the documentation both on the data migration page and the troubleshooting page, not sure if that should be a separate issue or belongs somewhere else.

**Comment by cuibonobo** [comment]
Has the configuration for your Google Cloud instance changed at all? It seems like your ffmpeg is damaged or running out of resources while making previews. Try uploading a video that's only a few seconds long. If the preview works then your ffmpeg may be running out of memory for your regular uploads.

**Comment by awils27** [comment]
I'm not sure, it's possible, although googles monitor doesn't show a spike in RAM, I might manually up to to something like 16gb and try.

**Comment by awils27** [comment]
The instance was changed to 2gb of ram after google had recommended it because of under utilization of RAM. Interesting at 2gb Google only showed ram reaching 55% although this could be an issue with google monitoring service.

Is there a list somewhere of recommended hardware for running Kitsu/Zou?

**Comment by frankrousseau** [comment]
There is no recommended hardware because it depends on your situation and needs. Every video processing requires strong hardware, especially when building playlists. So if you upload many videos, like hundreds a day,  it's better to have a good gpu and a lot of RAM. The webserver and the database can live with less.
However, if you are a team > 10 people, the best solution is to hire us to provide you with Kitsu.
