### ISSUE TITLE
Fixed / Animate labels do not work when asset is used in anothers asset breakdown

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#729]
Area: 
Breakdown

Issue:
Fixed / Animated labels only work in 'Shots' page but not on 'Assets' page.

How to reproduce:
- Add an asset ( custom asset type ) to an asset breakdown on the breakdown page.
- ( optional ) Click the +1 or +10 buttons on the asset to add multiples
- Click the label to set it to fixed. 
- Dialogbox opens, set to fixed. Choose 'fixed'
- Confirm
- BUG: Label on the asset doesn't change
- Try reloading the page ( this fixes the issue when it gets stuck on the shot breakdown )
- Label stays on 'animate'

If not reproduceable ad optional step.

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll fix that bug soon.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
