### ISSUE TITLE
Empty CSV assets breakdown

### ISSUE THREAD

**Issue by manuelrais** [cgwire/kitsu#732]
I'm trying to export a csv file containing asset breakdown data.  
![image](https://user-images.githubusercontent.com/6122546/129722309-2d33b174-5f7e-4ce6-9777-564543a50d5b.png)
When **there are some shots in project/episode**, assets breakdown download is **correct**. csv is populated.
When **there are no shots project/episode**, assets breakdown download results to an **empty csv**.  
Kitsu : 0.13.1 & 0.13.3
Zou : 0.13.2 & 0.13.4

**Comment by frankrousseau** [comment]
Thank you for the bug report. We'll have a look at this this week.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
