### ISSUE TITLE
Can't delete annotations

### ISSUE THREAD

**Issue by Taroslord** [cgwire/kitsu#743]
Image annotations can't be deleted.
I've added a text and a drawn annotation, but they can't be deleted anymore.
In some images it works in others not. Unfortunately it's not reproducable.

Any solution for this?

**Comment by frankrousseau** [comment]
Hello @Taroslord,

It's because we changed the way annotations are saved. I think it happens only on your old annotations. It should not happen on new previews.

**Comment by Taroslord** [comment]
Thank you for the fast answer. This happend with new annotations we made.
Does it help to make an update? Which version do you suggest to use to be sure all work fine?

**Comment by frankrousseau** [comment]
It's better to use the latest version. Update your installation every week.
