### ISSUE TITLE
On the asset playlist module, if a version has several elements; the drawing comment will apply to all the elements

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#755]
When you create an asset playlist (playlist on the fly or from the playlist module).

If you draw comments on a version that has several elements, the drawing will be displayed on all the elements.

![image](https://user-images.githubusercontent.com/42962633/134149107-ac582759-a927-4a49-adb1-080c9ca4fe53.png)

![image](https://user-images.githubusercontent.com/42962633/134149166-8f1cc0d4-34f6-493c-b61a-18c4914df05c.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
