### ISSUE TITLE
Not update list when changing task type filter in playlist

### ISSUE THREAD

**Issue by dinhthang1987** [cgwire/kitsu#758]
![image](https://user-images.githubusercontent.com/44437492/134471700-c9b183c2-a713-42ce-90db-3cf1dd167dae.png)

**Enviroment :** 
zou api : 0.13.6
kitsu : 0.13.12

**Comment by frankrousseau** [comment]
Thank you @dinhthang1987 for reporting.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by dinhthang1987** [comment]
Yes, thanks you so much. This problem resoved
