### ISSUE TITLE
Assets breakdown : label from csv import

### ISSUE THREAD

**Issue by manuelrais** [cgwire/kitsu#761]
Label column is not changed in kitsu breakdown when importing a csv in asset breakdown.
Label attribute stay empty regardless its value in csv file.  
It works in shot breakdown however.
Kitsu : 0.13.12
Zou : 0.13.9

**Comment by manuelrais** [comment]
It seems that adding an asset into the breakdown works, but updating label is not working if the asset is already casted.

**Comment by frankrousseau** [comment]
Ok, thank you @manuelrais for the report.
