### ISSUE TITLE
When a file is selected for being used as a preview it is downloaded

### ISSUE THREAD

**Issue by frankrousseau** [cgwire/kitsu#763]
it's an issue reported from the Discord:

"Not sure if it's a bug or an intended feature but on latest version of Kitsu I noticed a strange behaviour when attaching files. When I select file via "Browse" - the file content immediately prints in the same modal."

![image](https://user-images.githubusercontent.com/1336623/134927289-9f27e8f1-be92-4fd4-a27a-f0c9316a310f.png)

**Comment by keshon** [comment]
Add gif for better representation of the issue:
![d9720e49f0adf216](https://user-images.githubusercontent.com/13551109/134950815-02cf7043-8004-4a96-8ba0-2001652a16fc.gif)

**Comment by keshon** [comment]
[Stackoverflow how-to-check-file-mime-type-with-javascript-before-upload](https://stackoverflow.com/questions/18299806/how-to-check-file-mime-type-with-javascript-before-upload)
Just in case I googled this topic - there is an alternative way of detecting file types (check the ***Proper header-inspecting method*** section of the most voted answer) - might be a point of interest

**Comment by frankrousseau** [comment]
Sorry, but we can't reproduce that one.
