### ISSUE TITLE
Cannot upload videos

### ISSUE THREAD

**Issue by Animatect** [cgwire/kitsu#764]
Hi, I don't seem to be able to upload preview for videos, the pc should have more than enough resources to convert the files but I keep getting these errors on the gunicorn_error.log file:
[2021-09-29 15:42:49,573] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/thumbnails/229/13d/22913db4-5a89-419c-b708-ae505a234961'
[2021-09-29 15:42:49,573] ERROR in resources: Picture file was not found for: 22913db4-5a89-419c-b708-ae505a234961

they don't seem to be very descriptive regarding the uploading or ffmpg process, am I missing an error log where I could find more information?

Thank you!

**Comment by frankrousseau** [comment]
Hello @Animatect,

Can you check the troubleshooting section? https://zou.cg-wire.com/troubleshooting/

Best,

Frank

**Comment by Animatect** [comment]
Hey Frank, thanks so much for replying, this is the first thing I did, everything seems to be in order and the log logs this access to the file error but nothing much regarding why the file is not being created, I'm uploading the file from the local network and from localhost too just to make sure is not a problem with bandwidth but still nothing, any idea where I can start digging for answers?

Again thank you!

**Comment by frankrousseau** [comment]
Can you provide more information about the context:

* How did you install Kitsu? Did you set up the job queue or not?
* Which kind of files did you upload? Movies or pictures?

**Comment by Animatect** [comment]
Hey @frankrousseau thank you again for the follow up.
I installed Zou and Kitsu following the instructions from the documentation, I updated the installation to make sure it wasn't the problem, right now when I check the status I get:

version : "0.13.11"
database-up : true
key-value-store-up : true
event-stream-up : true
job-queue-up : true

So the Job Queue should be up and running.
I installed on an Ubuntu machine running a recent version of ubuntu. I'ts not the heaftiest of computers but it has a last gen Ryzen 5, 16GB of RAM, an Nvidia 1030 and a solid state drive.

I uploaded pictures fine, the problem comes when videos are involved, I've been testing with some open tests from blender foundation, mainly 5 secs mp4 videos, encoded with H264. 
I'm going to try updating everything on my system if it does not work, I'm going to try installing zou on a different bigger machine, maybe something with a 1060 or 1080 for video and at least 32 of Ram, althoug I feel this might be overkilled.

**Comment by frankrousseau** [comment]
Which version of Ubuntu do you use?

**Comment by Animatect** [comment]
21.04 I'm using pop-os distro

**Comment by Animatect** [comment]
Hi @frankrousseau, just to let you know that I made a clean install and everything seemed to be fine, probably the culprit was a mix of lack of permits and a bad Linux install, I got the same error on the clean install once but it sorted itself out.
Thank you so much for your support I had a couple of issues  but probably will ask about it on another topic, I'll close this one.
