### ISSUE TITLE
Default user/password error

### ISSUE THREAD

**Issue by javiertoledovis** [cgwire/kitsu#766]
Hi, I just installed Kitsu using docker in my synology nas. Everything looks fine but when I try to log in to the kitsu login page using the default user and password I get a `Log in failed, please verify your credentials` error message.

I tried setting the DB_USERNAME and DB_PASSWORD variables and also the default ones (admin@example.com | mysecretpassword) form the docker container info.

Any ideas on what can be causing this? 

Thank you in advance

**Comment by EvanBldy** [comment]
Hello @javiertoledovis,
I'm sorry but I just installed Kitsu using the dockerfile and there's no problem for me : everything was fine using admin@example.com/mysecretpassword.
So, I have no clue of what is not working for you. 
But you can try to reinstall the dockerfile (with no modification) from the beginning and put the logs here if it's not working again.

**Comment by javiertoledovis** [comment]
I kept adding folders to the /var/lib/postgresql and /opt/zou/previews mounts. I thought that was needed. I tried without that and everything worked just fine. 
Thanks for your time. I should've tried that before...

**Comment by EvanBldy** [comment]
If you run the docker with this command (to enable data persistence) : `docker run --init -ti --rm -p 80:80 --name cgwire -v zou-storage:/var/lib/postgresql -v zou-storage:/opt/zou/previews cgwire/cgwire`  there's no problem for me neither. 
No problem, I wish you a good try with Kitsu :)
