### ISSUE TITLE
Time out when creating tasks

### ISSUE THREAD

**Issue by g-LuL** [cgwire/kitsu#77]
When I try to create tasks for all assets/shots (more than 5000 in my production), a time out appears.
I'm using the docker container (build by myself, so I guess I have the last version of zou/kitsu).
Here's a screenshot :
![capture du 2018-02-27 13-30-11](https://user-images.githubusercontent.com/6122546/36728922-b801a704-1bc2-11e8-9fe7-f8e983c00765.png)

**Comment by frankrousseau** [comment]
Ok, thank you for reporting. Do you have server logs?

**Comment by g-LuL** [comment]
Here's gunicorn_error.log:
`[2018-02-27 16:29:29 +0000] [15] [CRITICAL] WORKER TIMEOUT (pid:8683)`
![image](https://user-images.githubusercontent.com/6122546/36741075-76dd6854-1be4-11e8-8470-db4a326229f2.png)

**Comment by gwendupre** [comment]
Hi g-Lul, do you still have this issue on your side?
