### ISSUE TITLE
When we add a new value to a custom column, it erases all the data

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#770]
On TV shows, feature films, short production.

We create a list of value custom columns and add data on the shot/asset page to it. Then if we realize we miss a value to the list and want to add it (with the edit option on the custom column), it will empty the data already filled on the asset/shot column.

**Comment by FionaProd** [comment]
Hi, is this bug under review? It's still causing issues as we need this function often.

**Comment by frankrousseau** [comment]
Sorry, it was reported in the community section. I didn't know that it was for you. We'll have a look next week. If you can give more precise information like examples, it would help to fix it.

**Comment by frankrousseau** [comment]
Hello @FionaProd, it will be fixed in the next release that will be published this week. Meanwhile, I have still good news. The data are cleared from the screen and not in the database. So you can already perform the changes (adding choices to a column) and run F5. The data should be there. I recommend to export the data first, in case of we are not talking about the same thing.

**Comment by FionaProd** [comment]
Hi Frank, thank you, I hope it fixes what I was reporting. In my previous issues, the page refresh didn't fix the issue (the example is the project Unicorn Wars, data column Studio - I added new possibilities for the drop down menu and it made all the info vanish. It had happened before for the column Technique). Now I export the data first, but as the OpenOffice software doesn't recognize the padding of the numbering by default, it makes for a couple of extra actions to fix everything back.

**Comment by frankrousseau** [comment]
Hello Fiona, the problem should be fixed on your installation. Can you hard refresh Kitsu (ctrl + f5) and try again?

**Comment by FionaProd** [comment]
Hi Frank, it seems fixed - when I add a choice in the list, the whole data disappears but if i refresh it comes back. Thanks!

**Comment by frankrousseau** [comment]
It should not make the data disappear. I will have a look at it again.
