### ISSUE TITLE
MacOS Unable to write @ symbol in comment field

### ISSUE THREAD

**Issue by elias-schwarze** [cgwire/kitsu#776]
On MacOS it is not possible to write the @ symbol in the comment field of an asset using the regular Mac keyboard shortcut (Alt+L). 
Copying and pasting the symbol into the comment does work and even brings up the @-suggestions dropdown menu, as expected.
Writing the symbol in other fields such as the search bar works. Only the comment field seems to be affected.

Tested on MacOS 
Big Sur 11.5.1
Catalina 10.14.6
Both Firefox & Chrome

Kitsu 0.13.18

**Comment by nledez** [comment]
Hi @elias-schwarze can you give us your keyboard input source?
In all mapping I found only "¬" with Alt+L.
![01-preference-home](https://user-images.githubusercontent.com/247138/164717057-4c49172e-cf48-49d8-b966-08baa70344d7.png)
![02-preference-input](https://user-images.githubusercontent.com/247138/164717074-63149d7f-025d-4e37-a28b-a01b143683e9.png)

**Comment by EvanBldy** [comment]
Hello @elias-schwarze 
This should be fixed with this PR https://github.com/cgwire/kitsu/pull/861, can you try it when it will be merged ? 
Thanks
