### ISSUE TITLE
Unable to switch through images by using keyboard

### ISSUE THREAD

**Issue by Taroslord** [cgwire/kitsu#781]
I've heard, it was possible to switch through review images by using the keyboard in earlier versions instead of the ui buttons.
I was never able to use the keyboard and miss this function a lot? Is this a bug?

![kitsu-keyboard-01](https://user-images.githubusercontent.com/55150926/140891530-066d02a4-f2a4-47d0-b3d2-9bd70c32ab52.jpg)

**Comment by frankrousseau** [comment]
Hello @Taroslord, did you try to use alt+j and alt+k?

**Comment by Taroslord** [comment]
> Hello @Taroslord, did you try to use alt+j and alt+k?

Thank you for the fast feedback. It works.
Why are you using this key combination? It's a bit unconventionally. I've tried intuitively the arrows keys, for example...

I haven't found a page in the Kistu manual, where all keys are listed. Is there one?

Thank you

**Comment by frankrousseau** [comment]
In the top right menu, you can display the shortcuts available. Arrows are used to navigate through frames in the video.

**Comment by Taroslord** [comment]
> In the top right menu, you can display the shortcuts available. Arrows are used to navigate through frames in the video.

Shame on me... Thank you.

Proposal: Change revision image navigation to this shortcut: ALT+[Arrow (Left/Right)]
This would be more intuitive, related to using arrow keys for navigating video images.
