### ISSUE TITLE
Unable to edit comments with a lot of inputs in a checklist

### ISSUE THREAD

**Issue by angel-k** [cgwire/kitsu#785]
Hello,
If I add a comment on Kitsu 0.13.28 with a lot of inputs in a checklist, when I want to edit them, they are shown below my screen as the checklist is too long to be displayed on screen.
A scroll bar should appear in that case.
Thanks

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by angel-k** [comment]
It's fixed on Kitsu 0.13.35.
Thanks !
