### ISSUE TITLE
People with the role "Client" can access the checkbox to delete shots

### ISSUE THREAD

**Issue by sayanel** [cgwire/kitsu#786]
This account has a "Client" role and can access the checkboxes on the left to delete shots. I did not try to click "Confirm" so even if the API will probably block the action they should not be able to see it.

![image](https://user-images.githubusercontent.com/7714353/143478926-6b81a512-2f32-46d6-b7a8-76432137a6ae.png)

Thanks!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by sayanel** [comment]
Yes it's fixed ! Thanks
