### ISSUE TITLE
Max number of users

### ISSUE THREAD

**Issue by wildchild-animation** [cgwire/kitsu#787]
Hi Kitsu

We are running a self hosted version of Kitsu, a few versions behind

Found a weird error today when adding a new user: 

> An error occurred while creating or update this user. You may have reach your user limit. Please contact our support team for more information.

Is there a limit on the number of users at all ? 

Thanks !

**Comment by wildchild-animation** [comment]
Nevermind: To answer my own question: 

Zou: 

USER_LIMIT = int(os.getenv("USER_LIMIT", "100"))

Thanks

**Comment by frankrousseau** [comment]
If you are running Kitsu for such a big studio, you should consider purchasing a license. It would be safe for your productions and would make our company more sustainable.
