### ISSUE TITLE
Stuck in Production Creation Menu Step 2

### ISSUE THREAD

**Issue by ServiceDog** [cgwire/kitsu#789]
System: Ubuntu 20.04.3 LTS

Steps:
1. Fresh Zou and Kitsu install following [the installation guide](https://zou.cg-wire.com/#deploying-kitsu).
2. Visit Kitsu via localhost, log in
3. "You don't have open productions. What about creating a new one?" -> Click "Create a new production"
4. Fill required fields in step 1 and step 2 "Set your production parameters"

Result:
Icon for step 2 turns green, but the next section "Select Asset Task Type" does not expand.

EDIT: Looks like they don't "expand", judging by [this screenshot](https://kitsu.cg-wire.com/assets/img/add_production_pipe.e18dd2f6.png) from Google Images there should be viewable fields already.
Image:
![stuck](https://user-images.githubusercontent.com/6334638/144531984-29559b96-b9d6-4bd3-8739-1ccccb566d98.png)

**Comment by ServiceDog** [comment]
I'm thinking the following steps aren't supposed to "expand" and should have viewable fields, as was the case with step 2's fields already being visible even when step 1 hadn't been completed.

**Comment by ServiceDog** [comment]
![Stuck2](https://user-images.githubusercontent.com/6334638/144533903-20ad2e6e-001e-4007-97c9-dc8104c0b3f7.png)

**Comment by frankrousseau** [comment]
Hello @ServiceDog, can you give us more information about the browser you use?

**Comment by ServiceDog** [comment]
Version 96.0.4664.45 (Official Build) (64-bit)

Followed the troubleshooting guide:
No errors from the logs

`localhost/api/status` returned:
```
{"name": "Zou", "version": "0.13.23", "database-up": true, "key-value-store-up": true, "event-stream-up": true, "job-queue-up": false}
```

Created the job queue service with following https://zou.cg-wire.com/jobs/, restarted all services. No change to bug.

**Comment by frankrousseau** [comment]
Can you open the javascript console panel and tell us if you see any error? (`ctrl` + `shift` + `j`)

**Comment by ServiceDog** [comment]
![image](https://user-images.githubusercontent.com/6334638/144968363-f51328ae-e37e-4ee7-a232-8a7af134c264.png)

**Comment by ServiceDog** [comment]
![image](https://user-images.githubusercontent.com/6334638/144968579-314a1816-4147-4597-ac49-b8ca9318f8f8.png)

**Comment by frankrousseau** [comment]
Mmm, I don't get what is wrong. Can you try with Firefox?

**Comment by ServiceDog** [comment]
Same with Firefox 94.0

**Comment by frankrousseau** [comment]
Can you try on another computer?

**Comment by jhoolmans** [comment]
I actually encountered the same, only to notice that there were no task types, task statuses etc populated by default. After creating those first, it continues properly.

But I would opt for letting the user know that this has to be done in the UI. 
Something like 'No task types were created. Click here to make some."

**Comment by ServiceDog** [comment]
> I actually encountered the same, only to notice that there were no task types, task statuses etc populated by default. After creating those first, it continues properly.
> 
> But I would opt for letting the user know that this has to be done in the UI. Something like 'No task types were created. Click here to make some."

This ended up being my issue. As someone newer to productions, some "suggested" task types and task statuses on those pages would be excellent as well

**Comment by jhoolmans** [comment]
Even though in the [documentation](https://zou.cg-wire.com/#deploying-kitsu) they state that some basic info is needed:

`DB_PASSWORD=yourdbpassword zou init-data`

I would still appreciate some UI feedback that in fact the data has not been initialized and point us to that part of the documentation.

**Comment by frankrousseau** [comment]
You're right but we have many other area to focus on for the moment. I prefer to close this issue. If people face the problem again. We'll see what we can do for it.
