### ISSUE TITLE
Issue with preview upload

### ISSUE THREAD

**Issue by fedmez** [cgwire/kitsu#791]
Hi there,

I am facing a problem with the preview upload on kitsu 0.13.26
I use chrome browser, Version 96.0.4664.45

I have tried to upload different files:
- .mov extension
- .mp4
The file I should upload does not contain any audio; but as the error came up, I thought it could have been a problem so I uploaded same file extensions but containing audio.

Three scenarios come up when a file is uploaded:
- the preview is shown corectly
- the preview is broken
- the preview remains in an upload status
These three situations occur randomly even when the very same file is uploaded. It is not matter of duration as the thing happens with both long and short files (4second long).

Does anyone have any clue on how to fix this?

I thank you in advance!

**Comment by frankrousseau** [comment]
Hello @fedmez,
Are you a customer of CGWire or do you run Kitsu by your own? If you are not using our services, it may be due to your infrastructure. Nevertheless, we would be glad to have the videos that fail to be uploaded.
