### ISSUE TITLE
"Clients" can no longer see the previews and write comments

### ISSUE THREAD

**Issue by sayanel** [cgwire/kitsu#793]
I know you said it was purposely removed but here at Cube Creative that's a feature that was really appreciated by our clients.
To be able to of course see the latest previews but as well be able to post and answer comments.

Maybe it would be worth it to create a "Watcher" role with the current attributions and give back to the "Client" the ability to interact with the shots ?

**Comment by frankrousseau** [comment]
Hello,

The client can comment the shots through the playlists. About the fact that he doesn't see the previews, we want to put it back. It should be there in the upcoming months.
