### ISSUE TITLE
Can't able to upload different files 

### ISSUE THREAD

**Issue by codersaran** [cgwire/kitsu#797]
Till before the last update i was able to upload all type of files like fbx, pdf etc through the comment section but now i was only able to upload jpg, png and mp4 files. I am running myself the kitsu in ubuntu 20.04

**Comment by frankrousseau** [comment]
Thank you @codersaran for the reporting. It will be fixed in the next release.

**Comment by codersaran** [comment]
Thank you  for the reply. Delightfully waiting for the next release :)

**Comment by frankrousseau** [comment]
We published the new release. Can you try again?

**Comment by codersaran** [comment]
Yes! now it's working perfectly :)
