### ISSUE TITLE
Asset Status (casting-ready) icon is show only on first row

### ISSUE THREAD

**Issue by Ramel** [cgwire/kitsu#803]
After installing a Kitsu self build with commit [c9ee61e](https://github.com/cgwire/kitsu/commit/c9ee61e5e33b6f92f7115633ec22d771e9f6ecbc)
![kitsu-asset-ready](https://user-images.githubusercontent.com/456421/151619611-1b1ab2e7-9123-4e2a-99f7-0bf220d8c693.png)

The following rows shows a "null" value for "cast-status" althought they have "Ready For" Assets.

Does not have tested with an official build. Should I ? Or I'm missing something?

**Comment by frankrousseau** [comment]
Hello @Ramel,

The new feature doesn't fix old data. To see something, you have to make a change in your casting. It's not optimal but we are a little bit overwhelmed by feature requests and lead prospective. So we had to take some shortcuts.

**Comment by Ramel** [comment]
Right, if I modify the "Breakdown/Casting" for SH02, the asset ready icons appears into "Shots" after reloading page.

Thanks.

**Comment by frankrousseau** [comment]
Great! Thank you for your understanding of the situation.
