### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by cliffnhansen42** [cgwire/kitsu#808]
Hello, I'm trying to figure out how to install Blender's Watchtower application on Windows, and it looks like I need Kitsu installed. I am not very experienced with anything that doesn't install from an MSI or EXE file, and so this has been a challenge. Plus, when I attempt to go to your website or anything connected to CGWire, I am told by Norton that your website has a virus, so I am unable to access your documentation to help me figure out how to install it. I imagine I am not alone in this problem, so if you could find out whatever's going on, I'm sure more people would be able to use your application! PS, I'm recording a video about the steps I took to install watchtower, so this would definitely help more people than just me if you can fix this!

Thanks for all you're doing for the 3d community, by the way, Kitsu looks amazing, and I really look forward to trying it out!

**Comment by frankrousseau** [comment]
Hello @cliffnhansen42, thank you for your message. We will contact the Norton team. We didn't know about this. We had similar issues with Avas and were able to fix that with them.
For Kitsu installation, I recommend you this documentation instead: zou.cg-wire.com/

**Comment by cliffnhansen42** [comment]
Thanks for checking it out. I'm still getting a warning from Norton about the link you sent. Hopefully Norton can fix this so those of us wanting to try Kitsu out can!

**Comment by frankrousseau** [comment]
I sent them a tweet. I hope they will change that soon. I'll keep you posted!

**Comment by cliffnhansen42** [comment]
That worked! Thank you. I feel safer using this now.
