### ISSUE TITLE
Tasks not showing in Task Type page

### ISSUE THREAD

**Issue by Shayen** [cgwire/kitsu#816]
Hi,

I want to change start date and end date for the task in asset, but those tasks is not showing in Task Type page.
It used to be show in a couple version before the latest one (current is 0.13.50)
![image](https://user-images.githubusercontent.com/27872000/156709838-7f2c72b8-318b-4123-a70a-a1759a269373.png)

I'm using Chrome, and there is no error in the dev console either.

Thanks

**Comment by Shayen** [comment]
For additional info,
I found that there have 2 ways to reach the Task type page
1. Clicking the Task Type name in the Column Header (Works)
2. Clicking the asset/shot name first, then click Task Type name in the asset/shot detail page (Not working)

Here the step I approach
![chrome_sAWL33JTS2](https://user-images.githubusercontent.com/27872000/156711653-97ccf424-9e42-407b-bea7-155bb0385bee.gif)


Thanks

**Comment by frankrousseau** [comment]
Thank you for the reporting. We will fix that in the upcoming weeks.

**Comment by Shayen** [comment]
Hi,
 
Sorry for the late reply.
I just check the feature and I want to confirm that the issue is resolved in version 0.13.58

Thank you very much
