### ISSUE TITLE
Status automations

### ISSUE THREAD

**Issue by Tilix4** [cgwire/kitsu#828]
# Main concept
As a production supervisor, I need to set automations when a status changes for an entity. For example, when the `Modeling` task status of an asset changes to `Done` I want the `Rigging` to automatically change to `WIP`.

# Proposal
It will work the same way as a Task Status: a studio list with a production assignation to enable.

- Add a `Status Automations` panel in the `Admin` section
  - Possibility to create an automation between two task type at status change, with two couples: `in_task_type/in_task_status -> out_task_type/out_task_status`.
  ![image](https://user-images.githubusercontent.com/22875539/159020015-9cbd2134-401c-4fd1-9f87-f5a67128bd33.png)
- Add a `Status Automations` panel in the `Production Settings` panel, which would work as the `Task Status` panel to enable automations for a production.

# UI
I'll need your contribution for:

- [ ] `Status Automations` icon
- [ ] The automation symbol

**Maybe the same could be used for both!**

Current UI:
![image](https://user-images.githubusercontent.com/22875539/159029124-9d302961-34d4-4f73-b4d8-0e27d76f2cd0.png)

# Implementation
## Parameters
- `in_task_type_id`
- `in_task_status_id`
- `out_task_type_id`
- `out_task_status_id`

*NB: `name` is dropped because I think it's be better to display the automation in the UI as a summary: `{in_task_type}.{in_task_status} => {out_task_type}.{out_task_status}`*

**Comment by frankrousseau** [comment]
It could be good to add a `ready_for` field to automate this field automatically too.

**Comment by Tilix4** [comment]
> It could be good to add a `ready_for` field to automate this field automatically too.

As you like, but I still don't get what `ready_for` brings to statuses. If `Modeling` is `Done`, it means it is ready for what follows...

**Comment by frankrousseau** [comment]
It is related to shot status. It allows to know when a shot layout/animation/compositing/... can be started.

**Comment by Tilix4** [comment]
> It is related to shot status. It allows to know when a shot layout/animation/compositing/... can be started.

I understand the need, but I still don't get why you needed to add this kind of field which creates confusion with Statuses IMO, but maybe this is not the current topic here.

**Comment by frankrousseau** [comment]
It's related to the topic because it's something that should be automatized. You can just add the field, I will take care of the rest later.

The need is to understand when you can start working on a shot at each stage of it. You can do a shot animation only when all the assets are ready. So you need to have this information at the asset level. You want to know if the asset is ready for animation or only for layout.

**Comment by Tilix4** [comment]
> It's related to the topic because it's something that should be automatized. You can just add the field, I will take care of the rest later.

You mean you want to code the automation for this field yourself but you expect me to at least add the `ready_for` field in the modal edition view?

> The need is to understand when you can start working on a shot at each stage of it. You can do a shot animation only when all the assets are ready. So you need to have this information at the asset level. You want to know if the asset is ready for animation or only for layout.

Yes but I already know it if my asset has Modeling `Done` and Rigging `WIP` that my asset is ready for layout but not for animation for example.

**Comment by frankrousseau** [comment]
> You mean you want to code the automation for this field yourself but you expect me to at least add the ready_for field in the modal edition view?

Yes

> Yes but I already know it if my asset has Modeling Done and Rigging WIP that my asset is ready for layout but not for animation for example.

You know it but Kitsu doesn't. Kitsu need it to show it in the *Shots* page. And you can have different rules depending on the studio or the production.

**Comment by frankrousseau** [comment]
Thank you for the contribution!
