### ISSUE TITLE
Clicking on @frame attribute in comment section make annotations not showing

### ISSUE THREAD

**Issue by nekopaldee** [cgwire/kitsu#831]
When I clicked on the @frame attribute posted in the comment section annotations in preview won't load, I found this happened in both playlist page and task page.
I'm using Kitsu v0.13.55 and Zou v0.13.42.

**Comment by frankrousseau** [comment]
Thank you for the bug report. We'll fix that soon.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by nekopaldee** [comment]
It is fixed now, Thanks!
