### ISSUE TITLE
Changing password failed. Please, restart the whole procedure again.

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [cgwire/kitsu#834]
I have tried to get zou/kitsu up and running from scratch three times now. 
I get as far as using `DBPASSWORD=myDbPassword zou create-admin myemail@my-company.com` which seems to work ok. Then I go to `192.168.x.x` where I log in with `myemail@my-company.com` and password `default`.
I'm then asked to change the password, which fails every time with 

```
Changing password failed. Please, restart the whole procedure again.
```

There are no error in gunicorn_error.log
<details><summary>gunicorn_error.log</summary>

```
[2022-03-23 11:54:49 +0100] [2987] [INFO] Starting gunicorn 20.0.4
[2022-03-23 11:54:49 +0100] [2987] [INFO] Listening at: http://127.0.0.1:5000 (2987)
[2022-03-23 11:54:49 +0100] [2987] [INFO] Using worker: gevent
[2022-03-23 11:54:49 +0100] [2997] [INFO] Booting worker with pid: 2997
[2022-03-23 11:54:49 +0100] [2998] [INFO] Booting worker with pid: 2998
[2022-03-23 11:54:49 +0100] [2999] [INFO] Booting worker with pid: 2999
```
</details>

I can see from the last few entries of gunicorn_access.log that the password reset it failing.

<details><summary>gunicorn_access.log</summary>

```
127.0.0.1 - - [23/Mar/2022:12:01:10 +0100] "POST //auth/login HTTP/1.0" 400 92 "http://192.168.15.205/login?redirect=%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
127.0.0.1 - - [23/Mar/2022:12:01:18 +0100] "PUT //auth/reset-password HTTP/1.0" 401 236 "http://192.168.15.205/reset-change-password/abb1c1d7-86cb-465e-b638-754f3e79e167" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844>127.0.0.1 - - [23/Mar/2022:12:01:38 +0100] "POST //auth/login HTTP/1.0" 400 92 "http://192.168.15.205/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
127.0.0.1 - - [23/Mar/2022:12:02:05 +0100] "PUT //auth/reset-password HTTP/1.0" 401 236 "http://192.168.15.205/reset-change-password/2f4f27bf-87e3-4a18-bd70-f835b2d5f84b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844>127.0.0.1 - - [23/Mar/2022:12:06:41 +0100] "PUT //auth/reset-password HTTP/1.0" 401 236 "http://192.168.15.205/reset-change-password/2f4f27bf-87e3-4a18-bd70-f835b2d5f84b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844>
```

</details>

Also, if I try to access the API at `192.168.x.x:api` I get 

```{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}```

**Comment by Anti-Distinctlyminty** [comment]
I successfully changed the password using Edge Version 99.0.1150.46 (Official build) (64-bit)

The failures were using Chrome Version 99.0.4844.74 (Official Build) (64-bit)

**Comment by frankrousseau** [comment]
Thank you for your bug report. It's probably related to the fact you had several installations. It created some mess with your cookies. I'm glad that you finally solved the problem!

**Comment by Anti-Distinctlyminty** [comment]
Hi @frankrousseau 
I would prefer to use Chrome and I only tried Edge as a test. Do you have any ideas on how to resolve the issue?
