### ISSUE TITLE
unable to post preview if project["fps"] is not set

### ISSUE THREAD

**Issue by mdk-man** [cgwire/kitsu#837]
We set a test project a while ago and didn't set the frame rate at that time. Today I just tried the new player and was unable to post a preview for this particular project :
```
File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/services/preview_files_service.py", line 48, in get_preview_file_fps
  fps = "%.2f" % float(project["fps"].replace(",", "."))
ValueError: could not convert string to float:
```

maybe cast project["fps"] to float it in a try/except ValueError (or check if it's an empty string). 
It's not an urgent patch : setting a framerate for the project solved the problem, but the error message is not explicit (HTTP 400 : Normalization Error)

**Comment by frankrousseau** [comment]
Thank you for reporting. At the project creation, via the UI, we force the FPS field. But It should definitely be handled if it's not set.

**Comment by frankrousseau** [comment]
Sorry for the long delay. It will be fixed in the next release.
