### ISSUE TITLE
When multiple artists are assigned to a task, can't unassign one, without removing all.

### ISSUE THREAD

**Issue by 77Dexter** [cgwire/kitsu#838]
In the case when a task is assigned to multiple artists, it would be great to have the option to unassign individuals from the task, rather than completely clear the assignment of all artists.

**Comment by frankrousseau** [comment]
Hello @77Dexter, you can unassign a single artist in the task type view (when you click on the name of a validation column).

**Comment by 77Dexter** [comment]
Hi Frank,

I couldn't comment on this in GitHub after it was closed by you, but this
really isn't immediately clear how to unassign one artist from a task
without removing all artists (and therefore removing hours logged against a
task.)

A little more info, or a screen grab would really help please.

thanks!
Carol Petrie ***@***.***)
