### ISSUE TITLE
Not show comment after update kitsu to version 0.13.55

### ISSUE THREAD

**Issue by dinhthang1987** [cgwire/kitsu#842]
Environment : 
Zou API : 0.13.43
Kitsu : 0.13.55

Pls help me, after update kitsu to version 0.13.55 not show some comment after push, but when return to review version 0.13.34 --> show normal

**Comment by frankrousseau** [comment]
Hello @dinhthang1987, can you show us the server error logs?

**Comment by dinhthang1987** [comment]
Ok this is problem on UI kitsu
![kitsu_comment_1](https://user-images.githubusercontent.com/44437492/163960924-648805e9-ddae-4589-ad17-5cac9a34672d.png)

**Comment by dinhthang1987** [comment]
This is run old version kitsu, comment show nomal
![kitsu_comment_2](https://user-images.githubusercontent.com/44437492/163961368-d21cd229-d5b4-4bb0-8a1a-f69bba76aa80.png)

**Comment by dinhthang1987** [comment]
I fixed this problem. because library node_module is old version for lib marked
