### ISSUE TITLE
after migrating the database via zou CI, users do not see their task lists in their accounts

### ISSUE THREAD

**Issue by Karbi81** [cgwire/kitsu#844]
after migrating the database via zou CLI, all data was migrated correctly but users do not see their task lists in their accounts. what could be the problem?
if I use raw mode then everything works correctly

name | "Zou"
version | "0.13.44"
database-up | true
key-value-store-up | true
event-stream-up | true
job-queue-up | false

**Comment by frankrousseau** [comment]
Sorry but we don't know what to tell you about this. Did you get any error message?
