### ISSUE TITLE
task panel size is reset to default size when I select a different cell

### ISSUE THREAD

**Issue by mdk-man** [cgwire/kitsu#848]
when I widen the task panel and then navigate through tasks using alt+arrow keys, the task panel is back to its smaller size. This was not the case in the version 0.13.43. Since I jumped from 0.13.43 to 0.13.55 I don't know precisely when this appeared..

**Comment by frankrousseau** [comment]
Thank you for the bug report. We'll fix that in the next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
