### ISSUE TITLE
Episode Stats show up for Short type instead of Sequence Stats

### ISSUE THREAD

**Issue by nekopaldee** [cgwire/kitsu#849]
![image](https://user-images.githubusercontent.com/26713157/163211896-185224cc-893c-49e5-9430-2451bd3d9f99.png)
I just noticed that Episode Stats show up for Short and Feature Film type instead of Sequence Stats, but this only affects existed production, I've tried to create a new one and this doesn't affect them.

Changing to TV Shows type will make both Sequence Stats and Episode Stats appear, but it makes shot list broken.
![image](https://user-images.githubusercontent.com/26713157/163215376-4db340a9-2d19-4002-ade7-2a2eb0b43983.png)

Kitsu 0.13.57
Zou 0.13.45

**Comment by frankrousseau** [comment]
Thank you for the bug report. It will be fixed in next release.

**Comment by nekopaldee** [comment]
I tested the latest commit (https://github.com/cgwire/kitsu/commit/428d030e8a66185d395b3df2bb0dfad843a96b77) and this problem is fixed.
Thanks for your hard work!
