### ISSUE TITLE
Offsets appear while resizing sticked metadata column

### ISSUE THREAD

**Issue by kaamaurice** [cgwire/kitsu#854]
Offsets and css glitch appear while resizing sticked metadata column (assets and shots).

If we minimize the size of all columns and refresh the page, the rescale work properly.

Kitsu 0.13.57

![output](https://user-images.githubusercontent.com/13371155/163569549-c18eb945-e0a1-4c90-83dc-11aa43f118c9.gif)

**Comment by NicoPennec** [comment]
Thanks for your report @kaamaurice 🙏 
We have fixed the visual bug in a recent Kitsu version.
