### ISSUE TITLE
Drop downs and Blender

### ISSUE THREAD

**Issue by johnnycoolideer** [cgwire/kitsu#857]
Hi there,

I'm having two issues, the first being the drop down option only show one option not all the ones available in the tasks section.

The second is the connection with Kitsu and Blender.  When logging into the server through blender it gives some Python errors but says its connected but I can't seem to link to any shots.

Any ideas?

![Blender7](https://user-images.githubusercontent.com/99082293/163710459-b4bb2936-7ba4-41c0-8313-94c1f4fc1a0a.png)
![Blender8](https://user-images.githubusercontent.com/99082293/163710460-de7d97a0-3bf1-4e20-b6a9-3db649f1643d.png)
![Blender5](https://user-images.githubusercontent.com/99082293/163710463-fc552e40-e1b7-4b21-adb5-656a50e20a15.png)
![Blender6](https://user-images.githubusercontent.com/99082293/163710466-3e5f1b8c-f045-4d35-afe5-3d434cce1c78.png)

**Comment by frankrousseau** [comment]
Ping @EvanBldy

**Comment by johantri** [comment]
@johnnycoolideer I had this same Blender Kitsu add problem before, so i ask the developer (Paul Golter) about this issue last month. Now the problem is solved for me, just make sure you get the latest Blender Kitsu Addon here https://developer.blender.org/diffusion/BSTS/

**Comment by EvanBldy** [comment]
Hi @johnnycoolideer, we don't do support on this plugin for Blender as we don't develop this plugin. You have to ask the developer (Paul Golter from Blender) for help with this. 
Concerning the other issue related to task types and ready_for this is weird normally you can only select task types for shots, can you show all the tasks types related to shots in the settings for this project ?

**Comment by johnnycoolideer** [comment]
Sure thing.

![shot 2](https://user-images.githubusercontent.com/99082293/164723986-b6c5e5ae-d9f4-4bed-9e84-6ba6af895b65.png)
![shots](https://user-images.githubusercontent.com/99082293/164723987-c767731f-7c77-4335-9cef-19ad178859ee.png)

**Comment by johnnycoolideer** [comment]
> @johnnycoolideer I had this same Blender Kitsu add problem before, so i ask the developer (Paul Golter) about this issue last month. Now the problem is solved for me, just make sure you get the latest Blender Kitsu Addon here https://developer.blender.org/diffusion/BSTS/

Thanks @johantri the only issue I have is when I attempt to install that version after cloning it, it doesn't show as an available add on.  What steps did you take to get it to work?

**Comment by johnnycoolideer** [comment]
@johantri You were 100% spot on.  I know it seems like a daft mistake but the documentation tells you to copy the blender_kitsu directory into the addons but there's a blender_kitsu directory within the blender_kitsu directory and THAT is what you need in the addons directory.  Now that issue is solved.

I just need to sort this inability to select different drop down options and I'll be away.  It's probably something obvious.

**Comment by johnnycoolideer** [comment]
Second issue is now sorted, you have to assign all task types and statuses when you initially create the project - there doesn't seem to be a way to assign them retrospectively.

**Comment by frankrousseau** [comment]
You can assign them in the settings of your production if you didn't do it at production creation.

**Comment by johantri** [comment]
@johnnycoolideer Glad you can make the addon to work. Once you have set your Host, Username and Pasword correctly then you are ready to go.

To make your Blender to understand the context of the asset, Paul Golter told me that i have to make my folder hierarchy to be exactly the same like the one in Blender Studio, that's how this addon designed by the way. However even after i match the folder (i use this reference for that https://studio.blender.org/training/pipeline-and-tools/chapter/naming-conventions/ i tried to follow all the naming convention correctly) i still can't make Blender to detect the asset. So he told me to assign my asset manually. I'm thinking that it got something to do with shot_builder addon to create asset and shot that have "identification tag" that connected to Kitsu.

For shot files however, it can detect Kitsu shot list seamlessly, so i can set the frame range, playblast it and send it directly to Kitsu. Note that you can't set your shot files manually in Kitsu, you have to setup your animatic movie files via Blender VSE to chop them into separate scenes and shots, this way Blender will send the "identification tag" for each shot to Kitsu, and Blender will create the shot list in Kitsu for you. https://studio.blender.org/training/pipeline-and-tools/blender-kitsu/

**Comment by animate1978** [comment]
Not sure what this addon did but it completely hosed my Kitsu installation. I had been reading this thread for tips on how to make it work in Blender 2.93.9 and after pulling from the Blender dev git, I restarted Blender, logged  via the addon in and poof... my server is not responsive. I immediately deleted the blender kitsu addon because I have had my Kitsu server running since Nov of last year and I am unsure if any of my data is even there. I get a blank background now.

Any ideas?

Sorry to hijack the thread I just don't know where else to ask...

**Comment by frankrousseau** [comment]
You should open an issue on the Zou repository and consult the https://zou.cg-wire.com/troubleshooting/ section first. It's impossible to help you without knowing more about the error you face.
