### ISSUE TITLE
Running Kitsu from Docker, mail not working

### ISSUE THREAD

**Issue by juangea** [cgwire/kitsu#862]
Hi.

I'm running kitsu with permanente data capabilities from docker, our server is an M1 MacMini, and so far it works great, the only caveat we see is that it cannot send emails.

I'm not sure if we can install kitsu on a Mac M1 (ARM) as bare metal, or on a VM that runs over the M1 (so that means Ubuntu ARM), and docker is working great, so it's the option we picked.

Is there a way to solve the email problem?

**Comment by frankrousseau** [comment]
Hello @juangea,
The Docker image is not aimed at being used in production. It has a demo purpose. I'll ask to @nledez if he can help with your problem.

**Comment by juangea** [comment]
Thanks @frankrousseau .

I made a more detailed explanation of the things I'm doing in this issue (sorry for the duplication):

https://github.com/cgwire/cgwire/issues/30

Also you say it can be used in production in this other issue :) :

https://github.com/cgwire/cgwire/issues/10

TBH so far is working great, and it's an awesome solution for small/medium studios that may not have a dedicated linux server or the funds to hire the cloud solution.

The only caveat I found is the mail one, also having the files available form the host machine (as I explain in the other issue) it's an advantage because I imagine we can access directly to the configuration files, so could be awesome if in the future (maybe not near future) you could support a production ready docker image (maybe just an evolution of the current one, like an LTS docker image or something similar :)

Thanks for the help!

**Comment by nledez** [comment]
@juangea the email is a big topic/problem.
If you want to reduce the "spam topic", you need to configure SPF and DKIM.
Some ISP's block SMTP ports to reduce botnet SPAM.
This is just an example of what could complicate things.
But I will try to find a way to send mail so I can test Kitsu.

**Comment by juangea** [comment]
Keep in mind that I have not configured anything related  to mail, I'm not sure how can I do that, is there some info on how to configure it in the documentation?

**Comment by juangea** [comment]
Using Docker Compose and this image:

https://gitlab.com/mathbou/docker-cgwire

I've been able to correctly configure the email and not it's correctly working, thanks! :)
