### ISSUE TITLE
CSV Export strips padding from sequence and shot

### ISSUE THREAD

**Issue by MrFrangipane** [cgwire/kitsu#863]
Hello,

When exporting a CSV, if sequence naming scheme has a padding ("001", "002", ...) leading zeroes are stripped.

When importing anew this file (after altering it) new shots are created without those zeroes.

This is very problematic when the workflow is `CSV Export` >  `Edit file with comments or details` > `CSV Import`

Thank you

**Comment by frankrousseau** [comment]
Thank you for the report @MrFrangipane, we'll fix that soon!

**Comment by MrFrangipane** [comment]
Thank you so much !

**Comment by EvanBldy** [comment]
Hello @MrFrangipane,
I cannot reproduce this problem, I have tested with sequences and shots like "001", "002" ... there's no problem for me when I do an export. 
For example : 
![image](https://user-images.githubusercontent.com/26860690/165518187-0114d90e-8947-48da-885a-e299d9a12950.png)
With these shots/sequences I have this csv export :
[2022_04_27_kitsu_agent_327_shots.csv](https://github.com/cgwire/kitsu/files/8571984/2022_04_27_kitsu_agent_327_shots.csv)
We can see that the padding is good we we read the file in text mode.
Can you check that it's not your spreadsheet who remove the leading zeroes ?

**Comment by MrFrangipane** [comment]
Hi @EvanBldy 

Thank you so much for your help, and sorry for the late reply.

I was sure that I checked this myself, but it seems not... you're right, opening the .csv with a simple text editor shows that names are stored as strings.

I'm sorry for bothering you with that.

That being said, is it in your roadmap to support [SpreadsheetML](https://docs.microsoft.com/fr-fr/office/open-xml/working-with-spreadsheetml-documents) ? Importing .csv files in Excel while preserving this kind of data is [very tedious](https://answers.microsoft.com/en-us/msoffice/forum/all/keeping-leading-zeros-in-csv-file-format/236e23cb-9a00-4c30-bd2b-267d7a3140ac)

Thank you !

**Comment by EvanBldy** [comment]
Hi @MrFrangipane,
No problem :) 
This is not currently in our roadmap for the moment but you can add it in our [Canny](https://cgwire.canny.io/).
Thanks for the idea 
Have a nice day!
