### ISSUE TITLE
Hours per Day doesn't accept decimals

### ISSUE THREAD

**Issue by awils27** [cgwire/kitsu#864]
Hours per day seems to accept integers only.

![image](https://user-images.githubusercontent.com/68633820/165477867-706314cb-5715-4cb2-87b3-083222baa850.png)

Entering a decimal place results in this error: A server error occurred while saving settings

Not sure if this is intentional or not.

**Comment by frankrousseau** [comment]
It should not return a server error. But yes, we didn't mean to allow decimals here.
