### ISSUE TITLE
An error occurred while creating or update this user. You may have reach your user limit.

### ISSUE THREAD

**Issue by johantri** [cgwire/kitsu#870]
Hi Frank,

I'm still struggling with this issue. However i got different result when installing Kitsu on different Ubuntu machine. I attach the error log for both worked and not working one. I also notice that both Ubuntu use different Python version. Could this be the problem?
![image](https://user-images.githubusercontent.com/13281082/166846542-07f5ac8a-a29d-4bb0-ab34-9bb4a786d0ea.png)
[gunicorn_error (not working).log](https://github.com/cgwire/kitsu/files/8628077/gunicorn_error.not.working.log)
[gunicorn_error (working).log](https://github.com/cgwire/kitsu/files/8628078/gunicorn_error.working.log)

**Comment by frankrousseau** [comment]
From the error logs, it seems it is because you don't have properly configured, the mail server.

**Comment by johantri** [comment]
Hi Frank. They both have the same configuration. Is there another settings for the mail server ? Or something i missed?
![zou service](https://user-images.githubusercontent.com/13281082/168751776-0761506d-7c74-4028-926b-f2f89d788791.png)

**Comment by frankrousseau** [comment]
Hi Johan,

It read that too:

```
smtplib.SMTPDataError: (553, b'Relaying disallowed as no-reply@cg-wire.com')
```

You should use a different default email with your domain name.

**Comment by johantri** [comment]
It doesn't make sense to me because they both have gmail domain and not cg-wire.com (although with different gmail username) and have identical /etc/systemd/system/zou.service configuration, and even when i swap the email on both sides i still can't make it work on Ubuntu machine on the left side (in the screenshot above).

Are there some steps that i need to do when i change the default email? like restarting the Ubuntu or setting something up? I change the MAIL_USERNAME, SECRET_KEY, restart the ngix with the command below and restarting Ubuntu afterward several times but no success :
sudo service zou start
sudo service zou-events start
sudo service nginx restart

**Comment by frankrousseau** [comment]
When you change something to the configuration, you just have to restart `zou` and `zou-events` services. About your problem, it may be due to a connection limitation.

**Comment by frankrousseau** [comment]
I close this because it's a zou issue.

The variable to change is `MAIL_DEFAULT_SENDER`.
