### ISSUE TITLE
Show small thumbnails doesn't have correct tooltip

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#871]
When hovering the button to show small thumbnails the tooltip shows: tasks.small_thumbnails while when hovering to show big thumbnails shows Show big thumbnails

I'm guessing the text isn't added to [src/locales/en.js](https://github.com/cgwire/kitsu/blob/209d0e0943b7b5c298f3d3d05aa19f657c4a7320/src/locales/en.js).

![2022-05-05_09-44-16](https://user-images.githubusercontent.com/49758407/166881874-bbde1a48-6621-4e34-9d45-1d86c79d7bcd.jpg)

**Comment by EvanBldy** [comment]
Hi @EmberLightVFX,
I added the missing translations in this PR : https://github.com/cgwire/kitsu/pull/867
Thanks for the report, have a nice day !
