### ISSUE TITLE
Error occurred while deleting comment after upgrading to 0.14.1

### ISSUE THREAD

**Issue by nekopaldee** [cgwire/kitsu#872]
This error occurred while deleting comment after upgrading to 0.14.1, the comment disappeared after refreshing the page.

Kitsu 0.14.1
Zou 0.14.1

![image](https://user-images.githubusercontent.com/26713157/167247148-952024f6-5819-4939-ab79-a3b13e60cf57.png)
![image](https://user-images.githubusercontent.com/26713157/167247160-d89dd3d7-9662-476a-ba0b-b4432cf0fc4f.png)

**Comment by frankrousseau** [comment]
Thank you @nekopaldee for the reporting.

**Comment by nekopaldee** [comment]
This issue is fixed in 0.14.2, thanks for the hard work!
