### ISSUE TITLE
The language options in the profile page are mapped to the wrong language

### ISSUE THREAD

**Issue by Renovatiopictures** [cgwire/kitsu#890]
![image](https://user-images.githubusercontent.com/96414542/172367380-02580c69-a1df-4586-b433-362ad9640048.png)
![image](https://user-images.githubusercontent.com/96414542/172367454-caede285-d507-46a0-9e03-a0a5d0a4cd40.png)

I changed the language option to Chinese(TW) but the content is Chinese(CN).

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll have a look at that.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
