### ISSUE TITLE
@frame annotation does not match frame in video

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#892]
When using @frame in an annotation, the time is not on the drawing / frame that is shown in the player ( this is further off on longer shots and also depends on the framerate of the video / project )
On shorter shots, this is often off by one frame ( sometimes the frame that @frame generates is correct but the timestamp is not, sometimes it is the other way round ). This means clicking the annotation jumps to the wrong frame and does not display the drawing. Correcting the annotation into something that matches the player will fix that.

Image below is after typing @frame and pressing enter. You can see the missmatch between the current playhead position and the text that was generated.

![grafik](https://user-images.githubusercontent.com/58070351/172585945-a620daac-7cec-4b90-8602-32dc93577ed8.png)

**Comment by frankrousseau** [comment]
Hello could you send us the video that fails? On our side we don't have this issue.

**Comment by tetsuoanimation** [comment]
Sure, here is a test video with 30fps

https://user-images.githubusercontent.com/58070351/175017992-77f9c02c-27c9-4ab0-86b1-7682a4500210.mp4

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by tetsuoanimation** [comment]
I think this was already fixed in Kitsu 0.14.26 :) - ( That's the version we are currently running and it works there - thank you so much :) )
