### ISSUE TITLE
Can't add new Task Status tags and can't modify options in existing tags

### ISSUE THREAD

**Issue by Renovatiopictures** [cgwire/kitsu#896]
After I add a new tag, I can no longer add new tags or modify the options in existing tags.
For example, I want to set "IS ARTIST ALLOWED" to no in DONE tag
![image](https://user-images.githubusercontent.com/96414542/173327776-bd512d6e-ad67-48bc-9969-334d3a0dd70c.png)

 Here is the error message

{"message": "(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"ix_task_status_is_default\"\nDETAIL:  Key (is_default)=(f) already exists.\n\n[SQL: UPDATE task_status SET updated_at=%(updated_at)s, is_default=%(is_default)s WHERE task_status.id = %(task_status_id)s]\n[parameters: {'updated_at': datetime.datetime(2022, 6, 13, 17, 49, 50, 777311), 'is_default': False, 'task_status_id': UUID('3be41f99-ca3b-4f2a-b77e-406fb5c08645')}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)"}

**Comment by keshon** [comment]
Yeah it is also impossible to do anything if you rename pre-existing status at least once (tested on a fresh installation) - you wont be able to rename other statuses anymore.

**Comment by frankrousseau** [comment]
Ping @EvanBldy, this is a big issue. Can you look at it?

**Comment by EvanBldy** [comment]
Hi I have done a fix in the last version of Zou.
Can you try it @Renovatiopictures ?

**Comment by Renovatiopictures** [comment]
Thank you !
Zou 0.14.15 with kitsu 0.14.18-build works fine now.
