### ISSUE TITLE
Zouenv not entered with error when installing 0.14.20

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#907]
Following the new installation instructions, entering zouenv produces the following and doesn't enter the environment. The installation proceeds with one other issue (logged) but Kitsu seems to be running ok still.

kitsu@KITSU:/opt/zou$ sudo virtualenv zouenv
created virtual environment CPython3.6.9.final.0-64 in 106ms
  creator CPython3Posix(dest=/opt/zou/zouenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/kitsu/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
kitsu@KITSU:/opt/zou$

**Comment by Ramel** [comment]
I don't think that `sudo virtualenv zouenv` is a  good idea! You want to sudo because of permissions on "/opt/zou/"?

**Comment by PeteDraper** [comment]
I did a fresh install the other day utilising the current docs on a virtual box. It didn’t throw the issue but also didn’t enter the virtual environment.
