### ISSUE TITLE
Setting (new?) safe directory throws an error on Kitsu installation 0.14.20

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#908]
after cloning Kitsu, I *think* there's a new command that wasn't there before in the documentation, but it's throwing a permissions error:

kitsu@KITSU:/opt$ sudo git clone -b build https://github.com/cgwire/kitsu
Cloning into 'kitsu'...
remote: Enumerating objects: 53602, done.
remote: Counting objects: 100% (3129/3129), done.
remote: Compressing objects: 100% (880/880), done.
remote: Total 53602 (delta 2383), reused 2843 (delta 2242), pack-reused 50473
Receiving objects: 100% (53602/53602), 383.72 MiB | 10.85 MiB/s, done.
Resolving deltas: 100% (42288/42288), done.
kitsu@KITSU:/opt$ cd kitsu
kitsu@KITSU:/opt/kitsu$ git config --global --add safe.directory /opt/kitsu
error: could not lock config file /home/kitsu/.gitconfig: Permission denied

Despite this, Kitsu still seems to be running. This may be due to us not being in the zouenv (am not an expert!) due to the other zouenv issue logged.

**Comment by frankrousseau** [comment]
It seems you messed up with the permission rights. The installation issues should be done on the Zou repository.  I close it there.
