### ISSUE TITLE
Clients can see everything from menu: Shot lists, asset lists, breakdown etc (Bug)

### ISSUE THREAD

**Issue by Chantology** [cgwire/kitsu#911]
We are using the cloud subscription of Kitsu (Version 0.14.18)

With the client account, the client will be directed to the playlists which is good. But he or she is able to switch to the asset list, shot list, breakdown, newsfeed etc.

When clicking to an asset or shot the client is able to see the history and which artist did what. Comments are not shown. 

![Screenshot from 2022-07-04 19-16-49](https://user-images.githubusercontent.com/50327807/177197760-b1e956e6-c271-4777-a9e7-c7ad9de3e0c3.png)

**Comment by frankrousseau** [comment]
Thank you @Chantology for reporting this issue. 

When you say that the client can see people assigned, do you mean he can see them in the comment feed and in the news feed?

I think we can remove them easily from the comment feed. But we have to check with the other customers for hiding the news feed to the customer.

**Comment by Chantology** [comment]
@frankrousseau Please find an image attached. You can see all the names but not the actual content of the comments feed. 
![Screenshot from 2022-07-05 12-06-55](https://user-images.githubusercontent.com/50327807/177305392-e993fad8-4b46-4848-a069-4c3406d8d5df.png)

**Comment by Chantology** [comment]
@frankrousseau using a client test account I can confirm that the client has access to the whole new feed which can be a huge problem. Do you think this can be disabled in the short-term?

**Comment by frankrousseau** [comment]
We released a new version that hides the news-feed menu entry and the user name in the comment section. It will be soon deployed in production on all instances hosted by us. If someone complains about that, we'll look for intermediate solution.
 
NB: It doesn't prevent them to request the server directly. If it's not enough, we will limit the API access too.

**Comment by Chantology** [comment]
@frankrousseau thanks a lot! If you remove the news feed access - will the client still have access to asset list, shot list and the break down?

**Comment by frankrousseau** [comment]
Yes, we consider that it's better if he has an overview of the production progress.
