### ISSUE TITLE
Possibility of turning off video conversion for certain type of files

### ISSUE THREAD

**Issue by robaval** [cgwire/kitsu#914]
We are up to automate uploading playblasts from Blender to Kitsu and we're wondering is it possible to choose one format of that playblast that would not have to be converted by Kitsu with ffmpeg. So it just takes the video that Blender has rendered.

Can we somehow choose what files are converted?

**Comment by frankrousseau** [comment]
Hello @robaval,

You can use the `normailze_movie` flag (and set it to `False`) to avoid any conversion.
