### ISSUE TITLE
Documentation needs updating to refine and include missing installation steps

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#915]
There are still one or two points missing in the installation documentation and some points that can be clearer. The need for the indexes folder and setting permissions is missing, plus setting the db password without interactive prompts reads that you already need to be in psql which throws an error / doesn't apply.

**Comment by frankrousseau** [comment]
ping @nledez, it seems that your recent changes don't work as expected. Can you fix that?

**Comment by fquinto** [comment]
Are you thinking about open documentation repo in order to add some PR to it? I can not find it. Thanks.

**Comment by frankrousseau** [comment]
The source are on a different branch of the Zou repository: https://github.com/cgwire/zou/tree/docs

I close this issue because it's related to the installation and should be opened on the Zou folder.
