### ISSUE TITLE
Csv export stops with wrong field value

### ISSUE THREAD

**Issue by Maxiriton** [cgwire/kitsu#918]
**Context**

Studio name: 3.0 Studio
Kitsu version:  0.14.20
Production type: Feature Film

**Describe the bug**

Hello, 
We heavily rely on spreadsheets import and csv export to generate reports for our management and we  have encountered a strange bug that prevents Kitsu from correctly exporting a csv file. 

If a field has  "#ref!" in the text field, it will stop the csv export at this specific field. This kind of of text can happen if we have uploaded data that was incorrect from our spreadsheet tool. So, one way to fix it is to make sure that we upload correct data to kitsu, however, I don't think it should prevent Kitsu from exporting the whole csv if we need it. 

Thanks,

 - OS: MacOS 12.4
 - Browser Firefox Chrome 
 - Version FF102

**Comment by EvanBldy** [comment]
Hi @Maxiriton, it should be fixed in the last version :) 
Thanks for the report 
Can you try and close the issue if it's okay ?
