### ISSUE TITLE
Can't export csv from timesheets page

### ISSUE THREAD

**Issue by angel-k** [cgwire/kitsu#919]
**Context**

Studio name: FOST
Kitsu version: 0.14.24
Production type: TV Series

**Describe the bug**

In the */timesheets* page, the button *Export Timesheet* does not work anymore.
Vue outputs an error in the browser console (tested on Firefox and Chrome).
CSV exports from other pages in Kitsu work as expected.

**Desktop:**

 - OS: Windows
 - Browser: Firefox & Chrome
 - Version: 102 & 103

**Comment by EvanBldy** [comment]
Hi @angel-k,
Thanks for the report !
It's possible to have the error in the browser console ?

**Comment by angel-k** [comment]
Hi @EvanBldy,
Sure, here is the error from Firefox:
![firefox](https://user-images.githubusercontent.com/25372475/180436322-474562f6-0ced-4eea-979e-dcbbf79bc7ef.JPG)

and from Chrome:
![chrome](https://user-images.githubusercontent.com/25372475/180436350-a6e666dc-0a3b-4200-b0a5-5d78dc56e362.JPG)

It shows every time I click on the export button

Thanks

**Comment by EvanBldy** [comment]
Hi @angel-k, it should be fixed in this PR. 
Can you try and tell me if it works for you ? 
Cordially
