### ISSUE TITLE
Cosmetic issue - typing rec. seq name generates 2 entries of the same

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/kitsu#920]
if you use the reccomended sequence name and enter it in the bottom field, it appears twice. This is aesthetic and doesn't generate two sequences. When re-entering the same panel to create more shots, the seq number is displayed only once
<img width="1012" alt="Screenshot 2022-07-25 at 5 57 35 PM" src="https://user-images.githubusercontent.com/55868068/180781279-38bf2d69-87a5-469a-8792-ab5212109f09.png">
.

**Comment by frankrousseau** [comment]
Thank @PeteDraper for reporting!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
