### ISSUE TITLE
Error occurred when Unactive/Active users

### ISSUE THREAD

**Issue by jeremybep** [cgwire/kitsu#921]
**Context**

Kitsu version: 0.14.26
Production type: tv

**Describe the bug**

When i want to 'unactive' an Artiste from people page an Error occurred.
But it does well job, and after refresh people page selected Artiste is well 'unactive'

**Screenshots**

![unknown](https://user-images.githubusercontent.com/72266507/181785944-33e710fc-f9ec-467c-82e5-8ec8d31736a7.png)

**Desktop (please complete the following information):**

 - OS: Windows10
 - Browser chrome
 - Version 103.0.5060.114

**Comment by frankrousseau** [comment]
Thx @jeremybep for the reporting!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
