### ISSUE TITLE
Compare view doesn't change quality LD/HD

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#923]
When comparing a view with other task types, changing the quality from LD to HD only changes the original clip and not the clip I'm comparing to.

Kitsu version: 0.14.26
Production type: Feature Film

 - OS: Windows 10
 - Browser: Firefox
 - Version: 103

**Comment by EmberLightVFX** [comment]
Just noticed that it only happens in Assets/Shots previews, not in playlists

**Comment by frankrousseau** [comment]
Thanks @EmberLightVFX for the reporting!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Works as expected now!
