### ISSUE TITLE
In/out points don't apply when comparing clips

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#925]
Setting in and out points on a shot in a playlist and then enable compare with other task, only the left video loops on the in/out points. The right video play once but then stops and won't play any longer.

Kitsu version: 0.14.28
Production type: Feature Film

OS: Windows 10
Browser: Firefox
Version: 103

**Comment by frankrousseau** [comment]
Thanks @EmberLightVFX for the reporting!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
