### ISSUE TITLE
In playlists: it plays the same sound over different videos

### ISSUE THREAD

**Issue by FionaProd** [cgwire/kitsu#929]
**Context**

Studio name: ADV Studios
Kitsu version: 0.14.20
Production type: Series mainly, and it seems other projects too

**Describe the bug**

When a person plays a playlist, they hear the sound of the 1st video over the other videos. Sometimes it seems it replaces the sounds entirely, sometimes it plays both. As you can imagine, it's very annoying ; plusit had already occurred before and seemed to have been solved, but now it's come back.
Also, it happens when we compare two versions: sometimes both sounds play which is very difficult as sometimes lengths or timings differ. It'd be way better to be able to mute one or the other (and be able to choose which one).
It seems to be happening mainly when we use the 'space bar' to play/pause, but we're not sure.

We've tried deleting the cache, using different web browser, it makes no difference. When I say 'sometimes', it's because I myself haven't been able to replicate the issue, eben though it's happened to at least 5 different people.

Hopefully there's an answer, thank you.

**Desktop:**

 - OS: Linux Mint, Windows 10
 - Browser: Mozilla Firefox, Chrome
 - Version: ?

**Comment by frankrousseau** [comment]
Thank you @FionaProd for reporting. Is it something that happens in the playlist section too? Someone already reported the issue for on-the-fly playlists. So for that case, it will be fixed in the next release.

**Comment by FionaProd** [comment]
Hi @frankrousseau, that's great to know! I've asked the team on which page it occurs, I'll update you.

I have another bug to report which seems linked : when pausing mid-movie, the sound plays from another shot. It's really annoying when you pause regularly like directors do, here's a video example.

https://user-images.githubusercontent.com/94115194/185371595-884418f3-bf56-4749-a451-de9d7d9db5be.mp4

**Comment by FionaProd** [comment]
Apparently the 1st bug only happens when we generate a playlist, not on the Playlist page. So it's the same thing as what's been previously reported by someone else (I didn't see it in the bug report list, though).
Let me know if you need more info for the other issue.
Thank you.

**Comment by frankrousseau** [comment]
Ok, so it will be fixed in the next release. The bug was reported on our customer ticket system.

**Comment by frankrousseau** [comment]
Thank you for the additional information.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
