### ISSUE TITLE
Make deleted stand out more

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#935]
Per request of Frank, here is my bug report/feature request about deleted shots:

There should be better clarity of deleted shots. Right now only the name and the description has a small line over them. The rest looks exactly the same. When searching a scene-name, deleted shots ends up in the same list as non-deleted and it's very easy to miss that the shot was deleted if you only look on the tasks, that's at least what I do.
I had an artist the other day doing some work on a deleted shot because he missed that the name was crossed over
![1](https://user-images.githubusercontent.com/49758407/186630111-cb96c29a-b120-4c50-9399-698901a49cc1.png)

This is how it currently looks like when you search a scene name
![3](https://user-images.githubusercontent.com/49758407/186630166-b719c8bb-4a8b-4b59-a102-105b19173d5d.png)

My suggestion would be to darken the deleted shots quite a lot so it's highly visible that they are not active
![2](https://user-images.githubusercontent.com/49758407/186630197-308c44b4-8133-47e9-b275-41585e639ef5.jpg)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Waaay better now! Looks perfect!
