### ISSUE TITLE
Suggestion to alter red marker in player's timeline so it won't overlap green progress bar

### ISSUE THREAD

**Issue by keshon** [cgwire/kitsu#942]
It's a minor UI issue: red marks in timeline player overlaps green progress bar and without detailed inspection it's hard to distinguish the actual position.

The problem (it's unclear now if we are on red mark or on a frame before):
![unknown](https://user-images.githubusercontent.com/13551109/189178912-9c5c76d3-8fe2-4291-9002-9355a3ff71fe.png)
![unknown](https://user-images.githubusercontent.com/13551109/189179490-7c042c6e-f9ed-499c-af4e-d07b324a6d1e.png)

The possible solution:
![1](https://user-images.githubusercontent.com/13551109/189179006-a001f061-96dc-4219-b1ea-3e946c097ec2.png)

**Comment by frankrousseau** [comment]
Thx for the report and the suggestion. It will be included in the next release (probably in 2 weeks).

**Comment by frankrousseau** [comment]
It will be fixed in next release.
