### ISSUE TITLE
Looping a shot in playlist takes the in/out points from the next clip

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#946]
Kitsu version: 0.15.8

If you loop a shot that doesn't have the same in/out points as the shot after it in the playlist the in/out will change to the second shot's in/out.

https://user-images.githubusercontent.com/49758407/190668776-24c28324-d235-4bda-bcd1-9a0f2aa225fd.mp4

**Comment by frankrousseau** [comment]
Thank you fro reporting. It will be fixed in next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
The bug has kind of bin fixed.
It plays correct but there is still some UI bugs to iron out.

I can drag the end-line even longer than the length of the clip but if I set it to where the clip ends and play, when looping back to the shot (or manually go to another shot and back) where the shot before has the end-line somewhere else than in the end, the end-line ends up at the same location even tho it should be in the end.
It's easier to show with a video so here is one:

https://user-images.githubusercontent.com/49758407/204543516-cca01332-466a-4303-b279-adcba8788bea.mp4

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Works as intended! Thanks for the fix!
