### ISSUE TITLE
Deleted shots shows up as normal tasks under people page.

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#947]
Kitsu version: 0.15.8

**Describe the bug**

When viewing a persons page, deleted shots shows up under their personal page if they have an assignment to the deleted task.
There is nothing showing if the shot has bin deleted or not compared to the shots page.

My suggestion would be to show the deleted shot but make it obvious that it has bin deleted. Being able to hide the deleted shots from the list could be a good feature.
For the task-counter below the list I would suggest showing the amount of active tasks and tasks on deleted shots instead of the current total for both active and deleted shots.

**Screenshots**

![2022-09-18_15-27-40](https://user-images.githubusercontent.com/49758407/190904665-5fe54b04-d118-4146-b1a2-f5431168bd5c.jpg)

**Comment by frankrousseau** [comment]
We will go for a simpler solution: do not display tasks link to deleted elements at all.

**Comment by frankrousseau** [comment]
It will be included to the next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Fixed!
