### ISSUE TITLE
Nr of shots-value includes deleted shots

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#948]
Kitsu version: 0.15.8

The number in the bottom of the shots page that shows how many shots there are shows active but also deleted shots.
The task page doesn't include deleted shots in its calculation (maybe because it counts tasks?) but the people page do (it calculate shots).

My suggestion is to show the active amount of shots but also show the amount of deleted next to it, eg 395 shots (45 deleted).
![2022-09-19_13-40-18](https://user-images.githubusercontent.com/49758407/191011430-938a3757-4e30-4c84-a4f8-f3af76ce1330.jpg)

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Fixed but, when you delete a shot the number of shot doesn't update. You have to reload the page for it to update.
If you restore a shot tho, then the amount of shots gets updated.
I can totally live with a reload, just wanted you to know :)
