### ISSUE TITLE
Assigning already assigned person to task sends out new notification

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#949]
Kitsu version: 0.15.8

Maybe an edge-case but I can see this happening to more people.
We have a rendered-task in our production that we set to Done when the shot is ready to be added to the edit.
We do this way as the first render needs to be manually added to the timeline while updates can automatically be updated in the timeline.

Any how. We have one person assigned to all of these rendered-task so he knows when it's time to add newly created shots to the timeline. We added a couple of shots the other day scattered in different shots. For ease I selected all the tasks, even those he was assigned to and assigned him again.
This ended up with 400+ notifications going to him when there should maybe have bin 20.

My other thought was to filter all tasks not assigned to anyone and set to Todo but you can't filter tasks that's set to Todo (maybe another bug?)

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in next release.
