### ISSUE TITLE
Task Types reordering

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#95]
**Issue**

Can't reorder existing Task Types.

**Description**

When trying to reorder the built-in task types, for example ```Texture``` to priority 3, nothing happens. I assume this is because ```Modeling``` already has priority 3.

**Expected Behaviour**

When a priority number is available in the dropdown list, you should be able to choose it. Or display a warning why the change has not been processed.

Another idea would be to only show the priority numbers that are available. For example:

1 - Concept
2 - Texture
3 - Modeling

When you want to add another Task Type, you would only have the options of ```4-10```, since that is the free numbers. Another example:

1 - Concept
3 - Texture
4 - Modeling

When adding a Task Type you would get the options ```2, 5-10```.

**Comment by frankrousseau** [comment]
Thank you @tokejepsen, thank you for reporting. You're right the UI on this point is weak. I add it to the to-do list.

**Comment by BigRoy** [comment]
I believe currently you are able to assign the same Priority for multiple Task Types. Is that correct? :)

I gave it a quick go and I noticed I had some Task Types that both had Priority `1`. 

To be entirely clear. This was both in Assets and in Shots, so Assets had two Task Types with the same priority and Shots had two different Task Types that had the same priority. e.g.

```
# Assets
concept 1
rnd 1
model 2

# Shots
edit 1
storyboard 1
animatic 2
```

**Comment by frankrousseau** [comment]
Yes you can do it. In that case the priority is determined from the alphabetical order. It's definitely something to improve!

**Comment by frankrousseau** [comment]
Ok it's now fixed. You can drag n drop task types!
