### ISSUE TITLE
Issue with "gazu.asset.all_asset_types_for_project(project_dict) "

### ISSUE THREAD

**Issue by nicolasdorey** [cgwire/kitsu#951]
Studio name: NKI
Kitsu version: 0.14.18
Production type: NA

`asset_types = gazu.asset.all_asset_types_for_project(project_dict)`
=> It only returns the dict of one asset_type even if I have more asset_types in my project.
If I'm using `gazu.asset.all_asset_types()` , it returns a list of my different asset_types. But for all projects. So it returns me asset_types I'm not using in some projects.

![unknown](https://user-images.githubusercontent.com/88095524/191923909-543efb21-a579-4031-98e6-2bd4e5e55af3.png)
![unknown](https://user-images.githubusercontent.com/88095524/191923935-7272e73e-34b3-41c2-9d7d-05a21fa84213.png)
_(reads_gazu = gazu but in an external file)_

 - OS: Windows 10
 - Browser: Chrome

**Comment by frankrousseau** [comment]
Can you open this issue in https://github.com/cgwire/gazu ?
