### ISSUE TITLE
Not possible to remove frames-value

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/kitsu#952]
Kitsu version: 0.15.8

I accidentally added frames to a shot and it's impossible to remove the value.
If I try and edit it in the shots list it defaults to 0.
If I edit the shot and remove the frames and save it does get removed but when I reload the page the old value is back.
Shouldn't it be possible to remove the frames value?

**Comment by EmberLightVFX** [comment]
it's also not possible to set the value to 0. Setting it to 0 will revert it to what ever value was set before.
Nothing could be 0 frames long so I understand that it's reversing to what ever value was set before, but I still feel the possibility to remove the value at least should be possible

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Fixed!
