### ISSUE TITLE
Tasks creation/deletion inconsistency with asset types workflow changes

### ISSUE THREAD

**Issue by Tilix4** [cgwire/kitsu#956]
**Context**

Studio name: Normaal
Kitsu version: 0.14.26
Production type: TV Show

**Describe the bug**

Removing a task type from an asset type's workflow doesn't remove the created tasks on the assets from this type created before the workflow change neither prevents the task to be created.
Steps:
- Change workflow of the asset type to reduce the possibilities (e.g `Concept` only for `Character`)
- Create an asset from the type you limited the workflow (e.g `Character`)
- Hover the task of a task type which is not in the workflow or try to query it from gazu API, you'll get it.

Expected:
- The tasks of task types removed from a workflow of an asset type not to be created at the asset creation.
- Delete all tasks of the assets for which the type's workflow has been modified, following the removed task types.

**Screenshots**

I still can hover the task and see its tooltip (the pointer is invisible but next to the tooltip)
![image](https://user-images.githubusercontent.com/22875539/193319712-647e3bcd-1946-461f-88c6-cdbcfc544e86.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04
 - Browser Firefox

**Comment by frankrousseau** [comment]
Thank you for the report. But this one is a little bit tedious. If someone does a mistake, it may lead to lose a lot of data.

**Comment by Tilix4** [comment]
> Thank you for the report. But this one is a little bit tedious. If someone does a mistake, it may lead to lose a lot of data.

I understand, my proposal is may not be fully applied.  
At least can be implemented: 
- The tasks of task types removed from a workflow of an asset type not to be created at the asset creation.

Also, I found this issue because `gazu.task.all_tasks_for_asset` still returns these tasks which should not be available. Could we add an argument like `compatible_with_workflow = True`?

**Comment by frankrousseau** [comment]
> The tasks of task types removed from a workflow of an asset type not to be created at the asset creation.

It should already works like that. It sounds like a bug.

> Also, I found this issue because gazu.task.all_tasks_for_asset still returns these tasks which should not be available. Could we add an argument like compatible_with_workflow = True

Ok, we'll check that.

**Comment by frankrousseau** [comment]
> The tasks of task types removed from a workflow of an asset type not to be created at the asset creation.
The bug will be fixed in next release.

> Also, I found this issue because gazu.task.all_tasks_for_asset still returns these tasks which should not be available. Could we add an argument like compatible_with_workflow = True
Can you open an issue on Gazu for this?

**Comment by frankrousseau** [comment]
> The tasks of task types removed from a workflow of an asset type not to be created at the asset creation

It should be fixed. Can you try again?
