### ISSUE TITLE
Suggestion for reduced number of clicks

### ISSUE THREAD

**Issue by mottosso** [cgwire/kitsu#96]
Hi @frankrousseau,

I've got an idea for how to reduce the number of clicks on the site, and improve visibility of what's available on the page for newcomers.

![image](https://user-images.githubusercontent.com/2152766/42085878-894f3b16-7b89-11e8-8cca-ce8141b99b7e.png)

In a nutshell, it moves the most important parts of the (normally hidden) sidebar onto the top, in the form of icons. Primary icons could be e.g. Shots, Assets and People. Things you expect to be clicked all the time, things that won't need a description or title even. Perhaps the name of the page could show up on hover, for example. The core concept is that un-hiding that sidebar is tedious. Especially on a desktop where space isn't an issue.

I had a look at implementing this myself, but only got as far as building and launching the site locally and then the number of abstractions between function and content threw me.. If you have any pointers of where to start, I might be able to have a closer look, otherwise consider this just a suggestion.

**Comment by frankrousseau** [comment]
Great suggestion!

What you want to do mainly is to add shortcuts to the topbar.
In the code it means to copy this:

https://github.com/cgwire/kitsu/blob/master/src/components/Sidebar.vue#L27-L63
https://github.com/cgwire/kitsu/blob/master/src/components/Sidebar.vue#L27-L63 (to generate links, we use Vue.js getters)

to this:

https://github.com/cgwire/kitsu/blob/master/src/components/Topbar.vue#L33


Whatever I will think about it, you are not the first person to ask this.
It's almost like HTML!

**Comment by mottosso** [comment]
Implemented in https://github.com/cgwire/kitsu/pull/109#event-1734804622 I think

**Comment by frankrousseau** [comment]
Yep, I will release it soon

**Comment by frankrousseau** [comment]
We changed the whole navigation scheme which covers your point. Thank you for your issue!
