### ISSUE TITLE
Missing "description" field in POST request data when creating new episode for TV Show

### ISSUE THREAD

**Issue by jgilhutton** [cgwire/kitsu#967]
**Context**

Studio name: Naolito Animation Studios
Kitsu version: v0.15.16
Production type: TV Show

**Describe the bug**

While having a TV show production and trying to create new shots, we'll be able to create new episodes, sequences and shots.
If we try to create an episode, afte clicking on Add, Kitsu will stay there doing nothing and the episode will never be created.
The server is issuing a 400 code with the following response:
`"Missing required parameter in the JSON body or the post body or the query string"`
Problem is that we are missing the description field on the POST data:
`{"name":"Episode Name"}` should be `{"name":"Episode Name","description":"Episode Description"}`

**Screenshots**
Api response:
![imagen](https://user-images.githubusercontent.com/12903414/199591819-ed50ea6c-ac92-4fb1-9d47-5fdef21543c8.png)
POST data:
![imagen](https://user-images.githubusercontent.com/12903414/199591941-7c6ace80-cc90-4d3a-8ac1-4af388273c7e.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: FIrefox

**Comment by EvanBldy** [comment]
Hi @jgilhutton,
Thanks for the report :)
I will be fixed with this PR https://github.com/cgwire/zou/pull/538
Can you close if it's okay for you ?

**Comment by jgilhutton** [comment]
Thanks!
I'm closing this issue.
