### ISSUE TITLE
Documentation for custom actions

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#97]
I could only find a mention of custom actions in the documentation.

What are custom actions and how about they meant to be used?

**Comment by frankrousseau** [comment]
* personid
* personemail
* projectid
* currentpath (current url path)
* currentserver (host of the current server)
* selectedTaskIds
* entity_type (asset or shot)

**Comment by tokejepsen** [comment]
I tried running a [server](https://gist.github.com/mdonkers/63e115cc0c79b4f6b8b3a6b797e485c7) to listen for requests, and have configured a custom action in Kitsu.
Using the docker image with Docker Toolbox and I can't seem to get it to work. It returns ```405 Not Allowed``` on ```http://127.0.0.1:8080``` and ```http://192.168.99.100:8080```

**Comment by tokejepsen** [comment]
Forgot to say that I using this commands for Docker:
```
docker run --name avalon-tracker -d --rm \
    -v avalon-tracker:/var/lib/postgresql \
    -v avalon-tracker:/opt/zou/zou/thumbnails \
    -p 80:80 \
    -p 8080:8080 \
    avalon/tracker
```

**Comment by frankrousseau** [comment]
The request sent is a POST request I think. Is it what is expected on your service side? 

It may be due too to the fact you don't use the same domain for both applications.

**Comment by tokejepsen** [comment]
> Is it what is expected on your service side?

I'm pretty sure it is.

> It may be due too to the fact you don't use the same domain for both applications.

I'm a complete novice on web development. I'm guessing you mean its because I'm not listening on a proper web address like ```http://example.com:8080```?

**Comment by frankrousseau** [comment]
Web browsers don't like when things from a webdomain are targeting another domain. They consider it as an attack. So it's possible they prevent you to use a post request to your IP if it doesn't match the IP of you kitsu installation.

**Comment by flablog** [comment]
Hi there, 
it might help, but this is what I usually catch on my custom actions, using a Tornado web server : 

```
class ActionHandler(tornado.web.RequestHandler):
    def get(self):
        self.write('action not available without context')
    def post(self):
        selection_raw = self.get_argument('selection')
        selection = selection_raw.split(',')
        currentpath = self.get_argument('currentpath')
        currentserver = self.get_argument('currentserver')
        entity_type = self.get_argument('entity_type')
        personemail = self.get_argument('personemail')
        personid = self.get_argument('personid')
        projectid = self.get_argument('projectid')


```

In my case, this service is running on port 8889, but I don't care as Nginx is doing the rooting from a subdomain on port 80. But I can call this with the ip and port directly without problem.

**Comment by tokejepsen** [comment]
Thanks for that @flablog 

How are you running Kitsu? Through Docker?

I tried your tornado snippet, but still no luck. I don't think its the server, but how data is coming out of Docker.

**Comment by flablog** [comment]
I'm not using a docker instance. So it might be related ? I've not tried it.

I'm using the pip install as discribed in the documentation, on a virtual
machine.
No issue on having the custom action on another server, through a subdomain
or using an IP directly.
Then in production, the tornado instance with the custom tools is on the
same VM as Kitsu



Le lun. 9 juil. 2018 à 12:02, Toke Jepsen <notifications@github.com> a
écrit :

**Comment by tokejepsen** [comment]
Sorry this took me so long, but I have finally tested it with a bottle server and it work with Docker!

**Comment by tokejepsen** [comment]
For anyone struggling with this, here's a breakdown.

Requirements:

- Python (any version should work)
- A running instance of Kitsu (Using Docker might be easiest; https://github.com/cgwire/cgwire)

Download the [two python scripts](https://github.com/cgwire/kitsu/files/4197519/bottle_server.zip), and run `python {path to server.py}`.

In Kitsu create a custom action with the url: `http://localhost:90`. Select any task and run the custom action.
This should print the post request in the server console, and it'll look something similar to this:
```
{'personid': 'b01bae1e-f829-458a-a1eb-131bb66628cc', 'personemail': 'admin@example.com', 'projectid': 'fa4d7f04-b8e0-4518-8dbc-2f24997ca76e', 'currentpath': '/productions/fa4d7f04-b8e0-4518-8dbc-2f24997ca76e/assets', 'currentserver': 'localhost', 'selection': '95c171e1-dfff-498f-93e3-548a739e3202', 'entitytype': 'asset'}
```

**Comment by aboellinger** [comment]
> Requirements:
> 
> * Python (any version should work)
> * A running instance of Kitsu (Using Docker might be easiest; https://github.com/cgwire/cgwire)
> 
> Download the [two python scripts](https://github.com/cgwire/kitsu/files/4197519/bottle_server.zip), and run `python {path to server.py}`.

To start building quick integrations from a nodal interface with limited coding you can also spawn a [Node-Red](https://nodered.org/) server (docker image available).

**Comment by tokejepsen** [comment]
Very interesting @aboellinger !

Have you had a go at it? Maybe you could share a json flow as example?

**Comment by aboellinger** [comment]
Not for Kitsu integrations yet.
I had done test for integrations such as gitlab outgoing webhook into node-red, reorganizing the payload and forward it to a slack. 
I'll let you know when I come up with a useful use case in kitsu ;)

**Comment by frankrousseau** [comment]
Finally, it's available: https://kitsu.cg-wire.com/custom-actions/

Sorry for the delay and thank you for your patience!
