### ISSUE TITLE
Loose control over "Action widget"

### ISSUE THREAD

**Issue by mdk-man** [cgwire/kitsu#970]
**Context**

Studio name: Andarta / Madlab
Kitsu version: 0.15.17
Production type: 

**Describe the bug**

The new action widget (replacement of the action bar) can pop over the comment/review area when it's set at its maximum size. In this configuration user looses interaction with the widget and can't close it (especially when it pops over a video). User has to minimize the comment area to be able to move the popup to the left side of the screen and then (re)maximize the comment area (since closing the widget closes the comment area). If user could close the widget and keep the comment/review region available it would be nice.. (not sure if it's a bug or if it's by design)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser FF 
 - Version 106.5

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by frankrousseau** [comment]
Oups, the bug came back. I will fix it for the next release.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by mdk-man** [comment]
I confirm, it's fixed now 👍
Thank you Frank, and all the team :)
