### ISSUE TITLE
Playlist timeline has scrollbars

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#976]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.15.22
Production type: Short Film

**Describe the bug**

The timeline in the Playlists page has scrollbars that don't dissappear. 

**Screenshots**

![grafik](https://user-images.githubusercontent.com/58070351/203299645-32274ef4-91f2-4ba1-a975-f92d6ae2665a.png)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: All ( tested: Chrome, Firefox )

**Comment by EvanBldy** [comment]
Hi @tetsuoanimation,
Thanks for the report.
It should be fixed in the last version can you try and close if it's okay ?
Have a nice day
