### ISSUE TITLE
Selecting entities

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/kitsu#98]
**Issue**

Selecting entities is not very intuitive.

**Description**

When selecting entities you have to select the ```Status``` field.

**Expected Behaviour**

Selecting the ```Status``` field might make sense when modifying that property, but selecting the ```Status``` field when running custom actions.

Personally I would opt for being able to select the entire row.

**Comment by frankrousseau** [comment]
Ok thank you  for reporting.

**Comment by frankrousseau** [comment]
Moved to: https://cgwire.canny.io/asset-and-shot-tables/p/allow-to-multiselect-assets-or-shots-to-delete-them
