### ISSUE TITLE
Basically impossible to see that the Date-field is not entered (especially in light theme) + Please set Start Date field to valid by default

### ISSUE THREAD

**Issue by Friksel** [cgwire/kitsu#983]
**Describe the bug**

After filling everything in the form to add a new production the 'Please fill all the form' button doesn't work and doesn't change it's text so it looks like it never enables. I tried everything several times, including filling in the optional Assets and Shots inputs.
All items of the form also show a checkbox, except for the 'Set your production parameters' part; this shows in green, but without a checkbox-fill. Everything in there is entered fine and I even switched all values to another value and back just to be sure an internal update is triggered if it's working that way internally.

**Screenshots**
Entry to form:
![image](https://user-images.githubusercontent.com/3089978/206897009-55ca5382-da4c-4f7c-b03d-38e4a6aeeb9e.png)

Production parameters (the only part that doesn't show the green check, but IS green) - all other items are showing a green check, also the optional ones:
![image](https://user-images.githubusercontent.com/3089978/206896883-befcae3e-6f8d-4e95-83af-a69bb01fb3cc.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser [e.g. chrome, safari]: Ms Edge (= chromium) (latest, Version 108.0.1462.46)
 - Kitsu version: 0.15.24

**Comment by Friksel** [comment]
I think I found the issue, which was a little easier to see in Dark Mode:

When in Production Parameters you leave the Start Date to be on today (so don't change it) the button never gets activated. 

When the date is not explicitely set it has a different border around the date field to indicate it's not set yet, but in light theme that's basically impossible to notice. That's a little easier to see in dark mode.

Also I wouldn't expect that we need to explicitely set the Start date when the start date is already set to the right date (if we start 'today' it is, so I guess that happens a lot). So IMO it should always accept the start date field to be already valid when not having changed it and only wait for the user to enter the End Date to make sure we have a time span between them.

So to conclude I'd say:
- Make the disabled border style of the date fields in comparisson with the enabled style better noticable
- Always enable the Start Date field as it's set to 'today' and today seems like a perfectly fine value I'd say we can expect to use for new productions

Other than this; looking forward to start using this in a new project. Thanks for all the great work!

**Comment by frankrousseau** [comment]
Hello @Friksel,

Thank you for this detailed issue. We really want that people set the start and end dates because it has many impacts on the scheduling. I'm going to make the placeholders lighter to make it obvious they should be filled.

**Comment by Friksel** [comment]
Hi @frankrousseau , Thanks for the response. I understand. Perhaps it would be an idea to leave the dates empty to show users they always need to be explicitely set? That said tho, I think having a better contract between the placeholders and the filled in text would definitely be a great help. 
Great tool btw. Looks great overall and for the part I used it so far it works pretty great! Thanks for all the hard work (and for now enjoy the holidays)!

**Comment by frankrousseau** [comment]
I fixed the style. Can you try again?
