### ISSUE TITLE
Native ARM64 Docker Image

### ISSUE THREAD

**Issue by matteoveglia** [cgwire/kitsu#985]
**Context**

Studio name: Undisclosed
Kitsu version: Latest
Production type: VFX

**Describe the bug**

There's no arm64 build of Kitsu on DockerHub, would be great if part of the build system included building for arm64 so I don't need to build manually on every release.
ARM machines are getting increasingly performant and I'm able to run an 80-core 512GB VPC in Oracle Cloud for a 1/3 to 1/4 cost as an AMD/Intel (respectively) counterpart.
https://www.oracle.com/ca-en/cloud/compute/arm/

**Screenshots**

![image](https://user-images.githubusercontent.com/1258632/207185085-13bba496-e4fd-4d50-a3bc-6b9d305e4b30.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: Latest

**Comment by frankrousseau** [comment]
Hello @matteoveglia,

Can you please open this issue on the right repository? https://github.com/cgwire/cgwire

**Comment by matteoveglia** [comment]
Oh shoot, sorry about that I didn't realise the docker image was it's own repo; will do that now!
