### ISSUE TITLE
Building a playlist fails

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#986]
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.15.28
Production type: Short Film

**Describe the bug**

Building a video from a playlist fails with both methods. 
Might be relateds to this zou bug: https://github.com/cgwire/zou/issues/551

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome / Firefox

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in the next release.
