### ISSUE TITLE
Changing a metadata delete metadata in another column

### ISSUE THREAD

**Issue by Maxiriton** [cgwire/kitsu#987]
**Context**

Studio name: 3.0 Studio
Kitsu version: Kitsu 0.15.19 
Production type: Feature Film

We heavily rely on metadata to help us organize shots and we've stumble upon a very strange bug : we have a 'frames' column that we extensively use to store the precise number of frame for each shot. 
Since a few weeks, we've noticed that  when editing a metadata, it 'll erase the frame metadata. 

**Screenshots**

For example, here is  an example with a shot of 147 frames. 

<img width="777" alt="image" src="https://user-images.githubusercontent.com/10707113/208446098-c8d39a79-a13b-4f10-a9f2-f81461074926.png">

I then edit the BG Lieux column with a new value. If I refresh the page, I'll get : 

<img width="877" alt="image" src="https://user-images.githubusercontent.com/10707113/208446422-6a3740d9-8fa1-438c-9f53-7bbb25c99a4a.png">

Let me know if you need more information ! :)
Thanks,

Henri

**Desktop (please complete the following information):**

 - OS: Tested on macOS 13.0.1
 - Browser Firefox 
 - Version 107

**Comment by EvanBldy** [comment]
Hi @Maxiriton, 
I think it's already fixed can you try with the last version of Kitsu ? (0.15.29)
Cordially

**Comment by EvanBldy** [comment]
It's fixed with this commit : https://github.com/cgwire/kitsu/commit/5f3d0a650b8430abe55990cb8c7a3dcab20472b1
