### ISSUE TITLE
Comment drawing don't stay deleted

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#999]
**Context**

Studio name: gwen
Kitsu version : 0.15.40
Production type: short film

**Describe the bug**

When we draw a comment on the enlarged version of the comment panel, we go to another task and return to the first. If we delete a drawing, change the task and come back again, the drawing is still displayed.

The same thing happens if we delete a drawing and go to fullscreen. In fullscreen, the drawing is still displayed.

But if we draw something and delete it immediately, it won't reappear.

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome
 - Version: 109.0.5414.75 (Build officiel) (64 bits)

**Comment by frankrousseau** [comment]
Checked with @gwendupre
